### ISSUE TITLE
n8n crashes because of excluded nodes in config file

### ISSUE THREAD

**Issue by dhayab** [n8n-io/n8n#10332]
### Bug Description

Hi n8n team,

One of the latest releases causes issues with my config. It seems related to the list of excluded nodes I set up in my custom config file:

```json
{
  /* ... */
  "nodes": {
    "exclude": "[\"n8n-nodes-base.activeCampaign\",\"n8n-nodes-base.affinity\" ...]"
  }
}
```

This has worked properly up until today, when I updated the n8n docker image to the latest version. Here is the relevant part of the container log:

```
2024-08-08T13:39:43.868955950Z Loaded config overwrites from /home/node/.n8n/settings.json
2024-08-08T13:39:48.125525930Z Last session crashed
2024-08-08T13:39:58.137815659Z Initializing n8n process
2024-08-08T13:39:58.145018677Z TypeError: this.excludeNodes.push is not a function
2024-08-08T13:39:58.145153959Z     at LoadNodesAndCredentials.init (/usr/local/lib/node_modules/n8n/dist/LoadNodesAndCredentials.js:70:31)
2024-08-08T13:39:58.145212638Z     at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/BaseCommand.js:71:89)
2024-08-08T13:39:58.145260512Z     at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/start.js:140:9)
2024-08-08T13:39:58.145304439Z     at Start._run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/command.js:301:13)
2024-08-08T13:39:58.145353558Z     at Config.runCommand (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/config/config.js:424:25)
2024-08-08T13:39:58.145412969Z     at run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/main.js:94:16)
2024-08-08T13:39:58.145458352Z     at /usr/local/lib/node_modules/n8n/bin/n8n:65:2
2024-08-08T13:39:58.146094352Z Error: Exiting due to an error.
```

This issue disappears if I remove the `nodes.exclude` key from the config.

### To Reproduce

1. Create a custom config file
2. Start n8n with `N8N_CONFIG_FILES`
3. Observe crash

### Expected behavior

n8n initializes with the custom configuration properly

### Operating System

Docker

### n8n Version

1.53.2 using the Docker image (this issue might also appear in earlier versions?)

### Node.js Version

20.15.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dhayab,

Thanks for the report, The internal ticket for looking into this is `N8N-7548`. I suspect it is related to the recent changes with our config.

**Comment by netroy** [comment]
Can you please try changing the config file to this instead

```json
{
  /* ... */
  "nodes": {
    "exclude": ["n8n-nodes-base.activeCampaign","n8n-nodes-base.affinity" ...]
  }
}
```

We updated the config to parse the JSON array when passed in from `env` variables, but looks like we updated the code that reads from the file to expect the actual array, instead a stringified version of it.

This is the correct behaviour, and should have been like from the start, but we should have made this change in v2.0, since this is a breaking change.

**Comment by dhayab** [comment]
Using the parsed JSON string worked fixed the issue, thanks! I'll let you close the issue at your convenience.
