### ISSUE TITLE
OAUTH2 Generic credential repeatedly fails with Airtable

### ISSUE THREAD

**Issue by leesilverman** [n8n-io/n8n#11028]
### Bug Description

This issue was first noted in https://community.n8n.io/t/airtable-oauth2-credential-setup-failing-due-to-pkce-error-with-code-verifier/29940/6.  I already posted this in the forum this morning, but I've had to reauthenticate with Airtable a dozen times today and it's preventing me from sharing this workflow with my client so we can test it.  

When first connecting or reconnecting, I frequently but don't always get the error
```
{
  "error": "invalid_request",
  "error_description": "The \"code_verifier\" must only contain characters that are in: [A-Z] / [a-z] / [0-9] / \"-\" / \".\" / \"_\""
}
```
Reconnecting fixes it.  However, if the workflow hasn't run for a few hours and has to re-authenticate, it fails at least 1 out of 3 times.  That failure causes the credential to be rejected and I have to reconnect manually.

This is making it impossible to deploy this airtable workflow to testing, let alone production.

Just to answer the obvious question, the reason I'm not using the built in Airtable Oauth credential is that I need the webhook management scope and I can't find a way to add that scope to the built in airtable oath2 credential.  Someone should open a separate issue for that.

### To Reproduce

First go through all the steps to create a successful Oauth2 connection with the built in credential.  That'll ensure that all of the dependencies have been met. 

Then try to create a new credential using the generic OAth2 credential setup.  If it connects right away, try to reconnect.  It'll fail about 1 in 3 or 1 in 4 times.

Once it's working, leave the workflow idle for a few hours and try again.  Most likely it'll fail, and you'll get an email from Airtable saying that your access has been revoked.

### Expected behavior

Once you make an OAuth2 connection it should persist for weeks or months, not just an hour or two.

### Operating System

Amazon Linux 2003

### n8n Version

1.59.4

### Node.js Version

22.something

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @leesilverman,

We have created an internal ticket to look into this which we will be tracking as "GHC-270"

**Comment by Joffcom** [comment]
Hey @leesilverman 

Please try not to open duplicate issues, I will mark the forum topic as closed and locked and we can handle this here.

**Comment by leesilverman** [comment]
Sorry about that @Joffcom.  I thought this was a minor annoyance so I posted to the forum, then realized it had a much bigger impact.

**Comment by Joffcom** [comment]
Hey @leesilverman,

If it is already reported chances are we are aware of it, Opening a second issue won't increase any kind of priority. In this case it looks like we have an old issue for this which we are tracking as `NODE-1722`, At the moment it is in backlog but I will add this issue to it and see if it moves it.

**Comment by leesilverman** [comment]
FYI, I've been able to use Airtable's personal access tokens as a workaround so I've been able to put these workflows into production and this issue is no longer a showstopper for me.  But it should still get fixed sooner rather than later - OAUTH2 is a pretty widespread system, so it's critical to have a really robust implementation.

**Comment by leesilverman** [comment]
Just noting that I also encountered this problem using the Airtable OAUTH2 credential type.  It resolved the second time I tried to establish the connection, but I'm going to avoid using that credential if I can because I assume the connection will not last long.

**Comment by jambronner** [comment]
I'm also facing this issue. I'm no longer able to connect to Airtable with a personal access token or oAuth2. After retrying, I can eventually get a successful connection with oAuth, but when i try to test the actual node, I see an 'invalid_request' error, showing:

NodeApiError: Your request is invalid or could not be processed by the service at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1284:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2074:20) at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:27:12) at Object.apiRequestAllItems (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:37:24) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/record/search.operation.js:171:32) at Object.router (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/router.js:48:30) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/AirtableV2.node.js:21:16) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51
