### ISSUE TITLE
Queue Mode Fails

### ISSUE THREAD

**Issue by maipal-c** [n8n-io/n8n#11124]
### Bug Description

In Queue mode, some executions wont trigger

### To Reproduce

1. make sure have access to external redis-cluster with (6 nodes - 3 shards with 1 replica each on k8s in my case)
2. make sure have access to external postgresql db (RDS in my case)
3. n8n official helm chart with official arm image (1.56.2) with 1 main pod , 2 workers pods & 1 webhook pods
4. put a kafka trigger on any kafka topic
5. receiving 3-5 messages per seconds on kafka topic trigger
6. 1-5 out of 10K executions fails with error below

data object of execution (from network tab - http://localhost:8010/rest/executions/102813 then response.data.data)
```
[
   {
      "resultData": "1"
   },
   {
      "error": "2",
      "runData": "3"
   },
   {
      "message": "4",
      "stack": "5"
   },
   {},
   "Cannot read properties of null (reading 'data')",
   "Error: Cannot read properties of null (reading 'data')\n    at Queue.onFailed (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/job.js:516:18)\n    at Queue.emit (node:events:519:28)\n    at Queue.emit (node:domain:488:12)\n    at Object.module.exports.emitSafe (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/utils.js:50:20)\n    at EventEmitter.messageHandler (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/queue.js:476:15)\n    at EventEmitter.emit (node:events:519:28)\n    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/cluster/ClusterSubscriber.js:160:30)\n    at EventEmitter.emit (node:events:519:28)\n    at DataHandler.handleSubscriberReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:80:32)\n    at DataHandler.returnReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:47:18)"
]
```

kafka trigger node object
```
{
	"1": {
		"parameters": {
			"topic": "<topic_name>",
			"groupId": "<grp_id>",
			"useSchemaRegistry": false,
			"options": {
				"jsonParseMessage": true
			}
		},
		"id": "6c2db656-45e1-414f-adea-eeafe5cfe38f",
		"name": "Kafka Trigger",
		"type": "n8n-nodes-base.kafkaTrigger",
		"typeVersion": 1.1,
		"position": [
			60,
			240
		],
		"credentials": {
			"kafka": {
				"id": "H738I7rANzImXhSW",
				"name": "Kafka account"
			}
		}
	}
}
```

### Expected behavior

the execution should process atleast initial kafka trigger node. or even on without processing kafka trigger node it commits offset to kafka, which leads to skip the single message processing.

very critical issue for fintech payment related topics

### Operating System

k3s on amazon linux 2023 

### n8n Version

1.56.2

### Node.js Version

no idea

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @maipal-c,

We have created an internal ticket to look into this which we will be tracking as "GHC-293"

**Comment by Joffcom** [comment]
Hey @maipal-c 

What error do you see in the n8n logs and have you tried a newer version to rule out any possible fixes?

Can you also provide a link to the official helm chart you have used?

**Comment by Joffcom** [comment]
That isn't an official n8n helm chart it is community made but likely won't be the cause.

If you can share the logs from n8n it would be helpful as at the moment, the one line on its own doesn't really mean anything but maybe there is more if you set the log level to debug.

Are you also able to share a minimal workflow that reproduces this so we can work out the priority.

**Comment by Joffcom** [comment]
Do you have more logs? Just selected lines may be hiding something so we would need more of the output.

Out of interest do you have an enterprise license as well or are you using the community edition?

**Comment by Joffcom** [comment]
Hey @maipal-c,

I have assigned this to one of the internal teams to pick up and prioritise, It could be that they pick this up quickly or they may see it is as a low priority issue as it is only 5 failure out of 10k executions which is something like a 0.05% failure rate which is pretty good.

For now have you tried tweaking the auto commit options and parallel processing to see that changes anything?
