### ISSUE TITLE
zep integration not working

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11120]
### Bug Description

I tried to connect zep memory, but this does not work anymore since they broke their contracts in v1 and this was seemingly not communicated well.

### To Reproduce

1. create an AI Agent workflow
2. add zep memory and test connection (I am using zep@v1.0.1 from their docker compose setup)
3. observe errors in n8n container:
```
NodeApiError: The resource you are requesting could not be found
AxiosError: Request failed with status code 404
```

### Expected behavior

connection to success

### Operating System

Docker

### n8n Version

1.60.1

### Node.js Version

Docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-289"

**Comment by wodor** [comment]
zep integration expects 0.17 or later, but zep released 1.x now which clearly is BC breaking (at least for self hosted version)
``` 
n8n  | You are using an incompatible Zep server version. Please upgrade to 0.17.0 or later.
n8n  | Error adding memory:  NotFoundError: Memory not found for session test-9afeedfc-8399-4cce-9978-bac2bcca98a7.
n8n  |     at /usr/local/lib/node_modules/n8n/node_modules/@getzep/zep-js/dist/utils.js:60:31
n8n  |     at Generator.next (<anonymous>)
n8n  |     at fulfilled (/usr/local/lib/node_modules/n8n/node_modules/@getzep/zep-js/dist/utils.js:5:58)
n8n  |     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
n8n  |   code: undefined,
n8n  |   responseData: undefined
```

**Comment by wodor** [comment]
it would be great to have it at hand in n8n again, it looks like really straightforfard data store (and more, but it would be enough if n8n just integrates vector store)

**Comment by Joffcom** [comment]
Hey @wodor,

At the moment we are waiting for the Zep team to do an update so we can update.

**Comment by lpadula** [comment]
any news?

**Comment by timstew** [comment]
It looks like newer versions of lanngchain are supporting newer versions of zep now:

@getzep/zep-cloud: ^1.0.6
@getzep/zep-js: ^0.9.0

is the issue that n8n needs to move to newer versions of langchain?

**Comment by pogman1234** [comment]
It looks like the issue seems to be local. I recently installed zep similarly (local via docker compose, using their ./zep up command), and the credential test points to api/**v1**/collections versus api/**v2**/collections. It looks like in the code both the integration and the test connection automatically appends to the url /api/v1/collections when zep has updated their setup to v2.

**Comment by simple10** [comment]
I ran into the same issue. Zep CE 1.0.2 (latest) dropped support for the api/v1 endpoints. The version of zep-js installed in n8n via n8n-node-langchain is v0.9.0 which only supports zep's api/v1 endpoints.

Out of curiosity, I tried redirecting api.getzep.com to the local docker zep CE instance and turned on the Cloud option in the n8n zep node. When Cloud option is enabled, langchain uses zep-cloud SDK that calls api.getzep.com/api/v2. Unfortunately, the zep-cloud SDK and Zep CE docker server are not compatible. Most likely because zep dropped features in the CE version.

The only quick fix is to downgrade your local Zep CE server to 0.27.2 to serve the api/v1 endpoints. But this version doesn't use the newer graphiti temporal graph features.

I guess we'll just need to for langchain and n8n to upgrade to the latest zep-js SDK that supports api/v2. Please let me know where to submit a pull request if there's any way I can help move this along.

**Comment by edvinPL** [comment]
Bump, Zep would be awesome for n8n.

**Comment by slayoffer** [comment]
Cant wait for Zep api/v2 in N8n. Cant use is as a RAG

**Comment by bonsalldavid** [comment]
My n8n pipeline remains broken until this is done. Any further updates on it?

**Comment by shalalalaw** [comment]
> My n8n pipeline remains broken until this is done. Any further updates on it?

[Zep sunset support for the CE version](https://blog.getzep.com/announcing-a-new-direction-for-zeps-open-source-strategy/)

**Comment by Joffcom** [comment]
This was released with [n8n@1.69.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.69.0) (as it was mentioned in description of this released [PR#11803](https://github.com/n8n-io/n8n/pull/11803)) or set in the branch name
