### ISSUE TITLE
FTP Node: normalizeFtpItem: Cannot create property 'modifyTime' on string

### ISSUE THREAD

**Issue by tautv** [n8n-io/n8n#11159]
### Bug Description

When trying to LIST '/' of this one specific FTP, I get errors:

>TypeError: Cannot create property 'modifyTime' on string '-rw-rw-rw-  1              generic      12663348 Oct 04 01:32 Complete Catalog 04.zip'
    at normalizeFtpItem (/Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-nodes-base/nodes/Ftp/Ftp.node.ts:105:17)
    at /Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-nodes-base/nodes/Ftp/Ftp.node.ts:700:10
    at Array.forEach (<anonymous>)
    at Object.execute (/Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-nodes-base/nodes/Ftp/Ftp.node.ts:699:22)
    at Workflow.runNode (/Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-workflow/src/Workflow.ts:1382:8)
    at /Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-core/src/WorkflowExecute.ts:1168:27
    at /Users/tautv/.npm/_npx/a8a7eec953f1f314/node_modules/n8n-core/src/WorkflowExecute.ts:1888:11

Looks like this specific FTP is returning a string instead of an object?
<img width="1319" alt="Screenshot 2024-10-08 at 12 28 01" src="https://github.com/user-attachments/assets/57373909-de04-429a-9978-bfee8e65d2a4">

Everything works fine if I try to directly download this file.
<img width="843" alt="Screenshot 2024-10-08 at 12 28 50" src="https://github.com/user-attachments/assets/47c0c519-7f45-47f0-8940-e9550682df27">

If I list insides of a sub-folder there - everything works fine.
<img width="750" alt="Screenshot 2024-10-08 at 12 29 37" src="https://github.com/user-attachments/assets/23c40dc3-0af6-4bdb-9383-9a500f530fc8">

### To Reproduce

Unfortunatelly can't give access to this. It's an FTP form a client in production. I have no contact with them either.

### Expected behavior

All other FTP servers I tried work flawlessly:
<img width="927" alt="Screenshot 2024-10-08 at 12 31 20" src="https://github.com/user-attachments/assets/4372edbe-974f-47c2-92cc-90427ca35dc2">

### Operating System

MacOS 14.6.1

### n8n Version

1.61.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @tautv,

We have created an internal ticket to look into this which we will be tracking as "GHC-295"

**Comment by tautv** [comment]
Hey @Joffcom 
Don't currently have FileZilla installed - would need to ask sys admin.
I'm mostly using Python/Finder to connect to the FTP servers.

All the info I was able to get from the connection:
>'211-Extensions supported:
CLNT
AUTH TLS
PBSZ
PROT
MDTM
MFMT
MLST type*;size*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;perm*;
PASV
REST STREAM
STOU
SIZE
EPRT
EPSV
UTF8
XCRC "Filename" SP EP
XMD5 "Filename" SP EP
XSH1 "Filename" SP EP
211 End.'

>'215 UNIX Type: L8'

>'230 User ****** logged in.'

Not sure if this is of any help?

**Comment by tautv** [comment]
Hey @Joffcom,

A little update - tried with FileZilla, but there seems to be an issue there too.
Can't connect to it:
```
Status:      	Connecting to **.***.***.***:21...
Status:      	Connection established, waiting for welcome message...
Status:      	Initializing TLS...
Status:      	TLS connection established.
Command: 	USER ******
Response: 	534 Policy Requires SSL
Error:         	Could not connect to server
Status:      	Waiting to retry...
Status:      	Connecting to **.***.***.***:21...
Status:      	Connection established, waiting for welcome message...
Response: 	220 FTP server ready.
Command: 	AUTH TLS
Response: 	234 Switch over to TLS-based communication.
Status:      	Initializing TLS...
Status:      	TLS connection established.
Command: 	USER ******
Response: 	534 Policy Requires SSL
Error:         	Could not connect to server
```

The FTP owner hasn't responded to any queries as of yet.

Everything seems to work ok with Python's standard 'ftplib', with few std output adjustments, I managed to incorporate this back into a workflow:
<img width="1059" alt="Screenshot 2024-10-17 at 11 51 32" src="https://github.com/user-attachments/assets/eacb6ed0-38ed-41e6-81b2-fad1cdbb1ce3">

I'll try to get more answers from FTP owner, but wouldn't hold my breath on it.

P.S. n8n FTP node for 'DOWNLOAD' works perfectly fine, it's just the 'LIST' that fails, and only for the root '/' dir of the ftp.

**Comment by tautv** [comment]
Hi @Joffcom, 

It's the strangest thing! We work with hundreds of FTPs, but not a single one has this issue.
With FileZilla I've tried all the configs it gives, event tried SFTP on this, but nothing worked.
I'll keep trying to get some more info from the FTP owner.

If I get a chance, I'll try to craft a plain socket connection to test some things, maybe I can find something of relevance.
I'll also try messing around with some ftp commands. Maybe their LIST command on the FTP is custom; I'll try and see if things like MLSD work there.

For the moment we'll have to live with a python solution to get the LIST from it, then pass it back to n8n.

Though I cannot share this connection, by any chance there's something I can do from my side with n8n? 
I can build an n8n from source and try messing with javascript side, but I lack knowledge in javascript - anything you can recommend? Something that would also help you guys?

**Comment by Joffcom** [comment]
Hey @tautv, 

I think the biggest thing would be finding out what FTP server they use, I have tried a bunch of the ones I have access to including some trial version of the managed file transfer applications I dealt with years ago but they all appear to be working as expected.

I am wondering if maybe it is a some dated AS400 system with a custom parser but LIST should be fairly standard, I have changed this internally from a bug to an enhancement request as we seem to work with everything else so this will likely be a change for one specific provider.

**Comment by tautv** [comment]
Thanks @Joffcom.
I'll keep investigating until I find something.
There's a chance the FTP server this client uses is custom made/modified. It's very hard getting any answers from them.

If there's anything I'm able to do from my side - give me a shout, please.

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
