### ISSUE TITLE
All airtable requests are failing

### ISSUE THREAD

**Issue by jambronner** [n8n-io/n8n#11377]
### Bug Description

Hi - I'm having an issue with my airtable requests. Whether it's a trigger or node, I'm getting the error "INVALID_REQUEST" on all workflows that use airtable. I have tried to update my personal access token and use oAuth2 credentials, but I'm not sure if the issue is happening at the credentials level or at the workflow level. I have also updated to the latest version of n8n but this did not fix the issue.

All of my airtable workflows were functional up until about 3 hours ago when the errors started occurring. 

Full error details:

From Airtable

> Error code
> 
> 422
> 

Full message

{ "error": { "type": "INVALID_REQUEST" } }

Other info

Node type

n8n-nodes-base.airtable

Node version

2.1 (Latest)

n8n version

1.63.4 (Self Hosted)

Time

10/23/2024, 12:00:39 PM

Stack trace

NodeApiError: Your request is invalid or could not be processed by the service at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1284:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2074:20) at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:27:12) at Object.apiRequestAllItems (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:37:24) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/record/search.operation.js:171:32) at Object.router (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/router.js:48:30) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/AirtableV2.node.js:21:16) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51

### To Reproduce

1. Create any airtable node or trigger
2. Test step
3. Receive "INVALID_REQUEST" error.

### Expected behavior

The node processing successfully as it did before the bug.

### Operating System

Ubuntu Linux 22.04.2

### n8n Version

1.63.4

### Node.js Version

2.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jambronner,

We have created an internal ticket to look into this which we will be tracking as "GHC-341"

**Comment by Joffcom** [comment]
Hey @jambronner 

Did it stop working before you upgraded or after?

Do you remember which version you were using when it was working?

**Comment by jambronner** [comment]
Hi, thanks for your help.

It stopped working before I upgraded. I received alerts of all my workflows
failing so I figured upgrading might fix the issue. But even after
upgrading, the issues remained.

I don't remember which version I was on unfortunately, but I last upgraded
about 1 month ago, so I was on a fairly recent version.

**Comment by Joffcom** [comment]
Hey @jambronner,

I have taken a look on my self hosted n8n instance and the node appears to be working fine so I don't currently think this is an issue with n8n itself. Have you checked in Airtable to make sure you are not hitting their API limits or base size limits?
