### ISSUE TITLE
Migration "MigrateIntegerKeysToString1690000000001" failed, error: Duplicate column name 'tmp_id'

### ISSUE THREAD

**Issue by ysmo** [n8n-io/n8n#11612]
### Bug Description

docker-compose.yml

version: "3.8"
services:
  n8n:
    image: n8nio/n8n:1.67.0
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=*****
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=*****
      - DB_MYSQLDB_USER=*******
      - DB_MYSQLDB_PASSWORD=*****
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=*****
      - N8N_BASIC_AUTH_PASSWORD=*****
    ports:
      - "5678:5678"
    restart: always

Error:

2024-11-07 16:17:56 Initializing n8n process
2024-11-07 16:17:56 n8n ready on 0.0.0.0, port 5678
2024-11-07 16:17:56 Migrations in progress, please do NOT stop the process.
2024-11-07 16:17:56 Starting migration MigrateIntegerKeysToString1690000000001
2024-11-07 16:17:56 Migration "MigrateIntegerKeysToString1690000000001" failed, error: Duplicate column name 'tmp_id'
2024-11-07 16:17:56 There was an error running database migrations
2024-11-07 16:17:56 Error: There was an error running database migrations
2024-11-07 16:17:56     at Start.exitWithCrash (/usr/local/lib/node_modules/n8n/dist/commands/base-command.js:115:49)
2024-11-07 16:17:56     at /usr/local/lib/node_modules/n8n/dist/commands/base-command.js:76:62
2024-11-07 16:17:56     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-07 16:17:56     at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/base-command.js:76:9)
2024-11-07 16:17:56     at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/start.js:150:9)
2024-11-07 16:17:56     at Start._run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/command.js:301:13)
2024-11-07 16:17:56     at Config.runCommand (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/config/config.js:424:25)
2024-11-07 16:17:56     at run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/main.js:94:16)
2024-11-07 16:17:56     at /usr/local/lib/node_modules/n8n/bin/n8n:71:2
2024-11-07 16:17:56 

### To Reproduce

error

### Expected behavior

error

### Operating System

macos docker

### n8n Version

1.67.0

### Node.js Version

v20.18.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ysmo,

Are you upgrading or is this a new install? You can also remove the `N8N_BASIC_AUTH_x` env options as they have not been used for around a year now.

If this is a new install I would recommend using Postgres as MySQL is still planned to be removed in the future which is why we no longer document it.

**Comment by ysmo** [comment]
OK, I'm a new installer.

It has been changed to Postgres and works normally.
