### ISSUE TITLE
N8N form node, freezes when clicking Next

### ISSUE THREAD

**Issue by easydigi** [n8n-io/n8n#11732]
### Bug Description

The form node behaves unstably when using the Next page functionality.

In test mode, it can switch pages, but it will freeze after testing for a period of time.
With the official link after the form is published, it almost always freezes when navigating.

![101731565595_ pic](https://github.com/user-attachments/assets/ab7f897e-9178-437f-8add-7ca151fb9930)

The console occasionally reports errors:

```
n8n        | Referenced node is unexecuted
n8n        | ExpressionError: Referenced node is unexecuted
n8n        |     at createExpressionError (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/WorkflowDataProxy.js:474:20)
n8n        |     at ensureNodeExecutionData (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/WorkflowDataProxy.js:713:31)
n8n        |     at Object.get (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/WorkflowDataProxy.js:812:29)
n8n        |     at findExtendedFunction (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/Extensions/ExpressionExtension.js:281:56)
n8n        |     at Proxy.extend (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/Extensions/ExpressionExtension.js:292:27)
n8n        |     at Proxy.eval (eval at getFunction (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+tournament@1.0.5/node_modules/@n8n/tournament/src/FunctionEvaluator.ts:13:16), <anonymous>:6:47)
n8n        |     at FunctionEvaluator.evaluate (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+tournament@1.0.5/node_modules/@n8n/tournament/src/FunctionEvaluator.ts:20:13)
n8n        |     at Tournament.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+tournament@1.0.5/node_modules/@n8n/tournament/src/index.ts:45:25)
n8n        |     at evaluateExpression (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/ExpressionEvaluatorProxy.js:113:16)
n8n        |     at Expression.renderExpression (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-workflow@file+packages+workflow/node_modules/n8n-workflow/dist/Expression.js:228:70)
n8n        | 
n8n        | There was a problem executing the workflow
n8n        | Error: There was a problem executing the workflow
n8n        |     at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/webhooks/webhook-helpers.js:508:15)
n8n        |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
n8n        | 
n8n        | Cannot read properties of undefined (reading 'data')
n8n        | TypeError: Cannot read properties of undefined (reading 'data')
n8n        |     at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/webhooks/webhook-helpers.js:277:66)
n8n        |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### To Reproduce

```
{
  "nodes": [
    {
      "parameters": {
        "formTitle": "step1",
        "formFields": {
          "values": [
            {
              "fieldLabel": "id"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.formTrigger",
      "typeVersion": 2.2,
      "position": [
        -80,
        -120
      ],
      "id": "4a24d844-26e2-4978-b9ae-bf0e8aa45e1a",
      "name": "On form submission",
      "webhookId": "4359201b-12ca-428b-af70-b2dca374f685"
    },
    {
      "parameters": {
        "formFields": {
          "values": [
            {
              "fieldLabel": "id2"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.form",
      "typeVersion": 1,
      "position": [
        340,
        -20
      ],
      "id": "e6e1484d-6c5a-4528-89ce-5b4ce8f08ad9",
      "name": "Form",
      "webhookId": "34913d88-68b7-4680-8447-90be3e88ebee"
    }
  ],
  "connections": {
    "On form submission": {
      "main": [
        [
          {
            "node": "Form",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

### Expected behavior

After clicking submit, it can navigate to the next page.

### Operating System

Docker

### n8n Version

1.67.1～1.68.0

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @easydigi,

We have created an internal ticket to look into this which we will be tracking as "GHC-441"

**Comment by Joffcom** [comment]
Hey @easydigi,

I am not able to reproduce this on 1.68.0, Were you able to hit the same issue with 1.68.0 as well?

**Comment by easydigi** [comment]
> Hey @easydigi,
> 
> I am not able to reproduce this on 1.68.0, Were you able to hit the same issue with 1.68.0 as well?

I am using version 1.68.0 in QUEUE mode. My environment is as follows:

Works x2
Webhooks x2
Main x1
nginx used as the frontend proxy

**Comment by easydigi** [comment]
After investigation, the issue is more easily reproduced when two Webhooks are set up, approximately 3 to 4 times out of every 10 attempts. The backend debug information is as follows:

`webhook-2     | 2024-11-17T15:53:30.930Z | debug | Received webhook "POST" for path "4359201b-12ca-428b-af70-b2dca374f685" {"file":"live-webhooks.js","function":"executeWebhook"}
webhook-2     | 2024-11-17T15:53:30.950Z | debug | Execution added {"executionId":"7754","file":"active-executions.js","function":"add"}
webhook-2     | 2024-11-17T15:53:30.952Z | info  | Enqueued execution 7754 (job 5706) {"scopes":["scaling"],"executionId":"7754","jobId":"5706","file":"scaling.service.js","function":"addJob"}
webhook-2     | 2024-11-17T15:53:30.952Z | debug | Started execution of workflow "workflow 12" from webhook with execution ID 7754 {"executionId":"7754","file":"webhook-helpers.js","function":"executeWebhook"}
webhook-2     | 2024-11-17T15:53:30.961Z | debug | Received waiting-form "GET" for execution "7754" {"file":"waiting-forms.js","function":"logReceivedWebhook"}
n8n-worker-2  | 2024-11-17T15:53:30.966Z | info  | Worker started execution 7754 (job 5706) {"scopes":["scaling"],"executionId":"7754","jobId":"5706","file":"job-processor.js","function":"processJob"}
n8n-worker-2  | 2024-11-17T15:53:30.971Z | debug | Workflow execution started {"workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-2  | 2024-11-17T15:53:30.972Z | debug | Start processing node "On form submission" {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-2  | 2024-11-17T15:53:30.972Z | debug | Running node "On form submission" started {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-2  | 2024-11-17T15:53:30.972Z | debug | Running node "On form submission" finished successfully {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-2  | 2024-11-17T15:53:30.973Z | debug | Start processing node "Form" {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-2  | 2024-11-17T15:53:30.973Z | debug | Running node "Form" started {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-2  | 2024-11-17T15:53:30.974Z | debug | Queued worker execution status for execution 7754 (job 5706) is "waiting" {"scopes":["scaling"],"file":"job-processor.js","function":"additionalData.setExecutionStatus"}
n8n-worker-2  | 2024-11-17T15:53:30.974Z | debug | Running node "Form" finished successfully {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-2  | 2024-11-17T15:53:30.974Z | debug | Save execution progress to database for execution ID 7754  {"executionId":"7754","nodeName":"Form","file":"save-execution-progress.js","function":"saveExecutionProgress"}
n8n-worker-2  | 2024-11-17T15:53:30.981Z | debug | Workflow execution will wait until Wed Jan 01 3000 00:00:00 GMT+0000 (Coordinated Universal Time) {"workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-2  | 2024-11-17T15:53:30.981Z | debug | Executing hook (hookFunctionsSaveWorker) {"executionId":"7754","workflowId":"wZRZe1a5AFP3WFb2","file":"workflow-execute-additional-data.js","function":"workflowExecuteAfter"}
n8n-worker-2  | 2024-11-17T15:53:30.982Z | debug | Save execution data to database for execution ID 7754 {"executionId":"7754","workflowId":"wZRZe1a5AFP3WFb2","finished":false,"stoppedAt":"2024-11-17T15:53:30.981Z","file":"shared-hook-functions.js","function":"updateExistingExecution"}

n8n-worker-2  | 2024-11-17T15:53:30.985Z | info  | Worker finished execution 7754 (job 5706) {"scopes":["scaling"],"executionId":"7754","jobId":"5706","file":"job-processor.js","function":"processJob"}
flows_n8n     | 2024-11-17T15:53:30.986Z | info  | Execution 7754 (job 5706) finished successfully {"scopes":["scaling"],"workerId":"worker-eug7FQvR2onKy5L5","executionId":"7754","jobId":"5706","file":"scaling.service.js"}
webhook-2     | 2024-11-17T15:53:30.987Z | info  | Execution 7754 (job 5706) finished successfully {"scopes":["scaling"],"workerId":"worker-eug7FQvR2onKy5L5","executionId":"7754","jobId":"5706","file":"scaling.service.js"}
webhook-2     | 2024-11-17T15:53:30.990Z | debug | Execution finalized {"executionId":"7754","file":"active-executions.js","function":"finalizeExecution"}
webhook-2     | 2024-11-17T15:53:30.991Z | debug | Execution removed {"executionId":"7754","file":"active-executions.js"}`


The frontend received a 500 error, with the specific content as follows:

`
500 Internal Server Error
{"code":0,"message":"Cannot read properties of undefined (reading 'pop')"}`

**Comment by easydigi** [comment]
Below are the logs from a normal operation, which appear to be Webhook requests. Sometimes, these requests occur earlier than the Worker startup time.

`webhook-2     | 2024-11-17T16:17:42.079Z | debug | Received webhook "GET" for path "4359201b-12ca-428b-af70-b2dca374f685" {"file":"live-webhooks.js","function":"executeWebhook"}
webhook-2     | 2024-11-17T16:17:56.279Z | debug | Received webhook "POST" for path "4359201b-12ca-428b-af70-b2dca374f685" {"file":"live-webhooks.js","function":"executeWebhook"}
webhook-2     | 2024-11-17T16:17:56.299Z | debug | Execution added {"executionId":"7770","file":"active-executions.js","function":"add"}
webhook-2     | 2024-11-17T16:17:56.301Z | info  | Enqueued execution 7770 (job 5722) {"scopes":["scaling"],"executionId":"7770","jobId":"5722","file":"scaling.service.js","function":"addJob"}
webhook-2     | 2024-11-17T16:17:56.302Z | debug | Started execution of workflow "Workflow 12" from webhook with execution ID 7770 {"executionId":"7770","file":"webhook-helpers.js","function":"executeWebhook"}
n8n-worker-1  | 2024-11-17T16:17:56.305Z | info  | Worker started execution 7770 (job 5722) {"scopes":["scaling"],"executionId":"7770","jobId":"5722","file":"job-processor.js","function":"processJob"}
n8n-worker-1  | 2024-11-17T16:17:56.309Z | debug | Workflow execution started {"workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.310Z | debug | Start processing node "On form submission" {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.311Z | debug | Running node "On form submission" started {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.311Z | debug | Running node "On form submission" finished successfully {"node":"On form submission","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.311Z | debug | Start processing node "Form" {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-1  | 2024-11-17T16:17:56.312Z | debug | Running node "Form" started {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.312Z | debug | Queued worker execution status for execution 7770 (job 5722) is "waiting" {"scopes":["scaling"],"file":"job-processor.js","function":"additionalData.setExecutionStatus"}
n8n-worker-1  | 2024-11-17T16:17:56.313Z | debug | Running node "Form" finished successfully {"node":"Form","workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}

n8n-worker-1  | 2024-11-17T16:17:56.313Z | debug | Save execution progress to database for execution ID 7770  {"executionId":"7770","nodeName":"Form","file":"save-execution-progress.js","function":"saveExecutionProgress"}
webhook-2     | 2024-11-17T16:17:56.313Z | debug | Received waiting-form "GET" for execution "7770" {"file":"waiting-forms.js","function":"logReceivedWebhook"}
n8n-worker-1  | 2024-11-17T16:17:56.320Z | debug | Workflow execution will wait until Wed Jan 01 3000 00:00:00 GMT+0000 (Coordinated Universal Time) {"workflowId":"wZRZe1a5AFP3WFb2","file":"LoggerProxy.js","function":"exports.debug"}
n8n-worker-1  | 2024-11-17T16:17:56.320Z | debug | Executing hook (hookFunctionsSaveWorker) {"executionId":"7770","workflowId":"wZRZe1a5AFP3WFb2","file":"workflow-execute-additional-data.js","function":"workflowExecuteAfter"}
n8n-worker-1  | 2024-11-17T16:17:56.321Z | debug | Save execution data to database for execution ID 7770 {"executionId":"7770","workflowId":"wZRZe1a5AFP3WFb2","finished":false,"stoppedAt":"2024-11-17T16:17:56.320Z","file":"shared-hook-functions.js","function":"updateExistingExecution"}

n8n-worker-1  | 2024-11-17T16:17:56.324Z | info  | Worker finished execution 7770 (job 5722) {"scopes":["scaling"],"executionId":"7770","jobId":"5722","file":"job-processor.js","function":"processJob"}
flows_n8n     | 2024-11-17T16:17:56.325Z | info  | Execution 7770 (job 5722) finished successfully {"scopes":["scaling"],"workerId":"worker-ALkwD4CDkJ21o6O5","executionId":"7770","jobId":"5722","file":"scaling.service.js"}
webhook-2     | 2024-11-17T16:17:56.325Z | info  | Execution 7770 (job 5722) finished successfully {"scopes":["scaling"],"workerId":"worker-ALkwD4CDkJ21o6O5","executionId":"7770","jobId":"5722","file":"scaling.service.js"}
webhook-2     | 2024-11-17T16:17:56.329Z | debug | Execution finalized {"executionId":"7770","file":"active-executions.js","function":"finalizeExecution"}
webhook-2     | 2024-11-17T16:17:56.329Z | debug | Execution removed {"executionId":"7770","file":"active-executions.js"}
webhook-2     | 2024-11-17T16:17:57.377Z | debug | Received waiting-form "GET" for execution "7770" {"file":"waiting-forms.js","function":"logReceivedWebhook"}
webhook-2     | 2024-11-17T16:17:57.407Z | debug | Received waiting-form "GET" for execution "7770" {"file":"waiting-forms.js","function":"logReceivedWebhook"}
flows_n8n     | 2024-11-17T16:17:59.011Z | debug | Querying database for waiting executions {"scopes":["waiting-executions"],"file":"wait-tracker.js","function":"getWaitingExecutions"}
`

**Comment by Joffcom** [comment]
Hey @easydigi,

In your set up do you have your load balancer set up to make sure all test requests only go to the main instance and the productions only go to the webhook workers?

**Comment by easydigi** [comment]
> Hey @easydigi,
> 
> In your set up do you have your load balancer set up to make sure all test requests only go to the main instance and the productions only go to the webhook workers?
Yes, I used load balancing, and the Webhook uses a different domain name from the main instance:

In the testing environment, the first page of the form is triggered through the main instance (using the domain name of the main instance). However, when redirecting to the form-waiting page, it automatically switches to the Webhook's domain name. Generally, this doesn't cause errors in the testing environment.

In the production environment, it's confirmed that the same Webhook is used. In the production environment, if you don't immediately click "submit" on the first page but wait for a few seconds, the likelihood of an error occurring is significantly reduced. However, if you click submit immediately, the probability of an error increases greatly. Moreover, when one form-waiting page hasn't been clicked and more form-waiting pages are triggered, the probability of errors also increases.

**Comment by easydigi** [comment]
nginx ->  traefik-->
                            ->Main                - domain:n8n.xxx.com
                            ->Works x2
                            ->Webhook x2.  - domain:api.xxx.com

**Comment by Joffcom** [comment]
@easydigi out of interest and unrelated to this issue directly... Why are you using 2 reverse proxies? I would make sure you have n8n_proxy_hops set to 2 just to cover any other odd issues that may be happening that you have not noticed yet.

**Comment by easydigi** [comment]
> @easydigi out of interest and unrelated to this issue directly... Why are you using 2 reverse proxies? I would make sure you have n8n_proxy_hops set to 2 just to cover any other odd issues that may be happening that you have not noticed yet.

1. This is the environment of my home server. From an actual needs perspective, I might not even require load balancing, but I want to build my learning environment using a load balancing approach that appears to have better performance.
2. My reason for using Traefik is that when I dynamically expand the number of Webhooks, Traefik can automatically discover them. In contrast, Nginx's proxy must pre-configure Docker hostnames or IP addresses.
3. The 80/443 ports of my server are already occupied by Nginx, and I am more familiar with Nginx's forwarding rules and restrictions. Therefore, I have not completely replaced Nginx with Traefik. I still have a large number of rules written in Nginx's configuration file, including SSL certificates, which are also placed at the Nginx layer.

**Comment by easydigi** [comment]
> I can confirm that the problem persists even with a simple form submit and response setup.
> 
> First node collects a single field "Name" and the second node provides a greeting response like `Hello {{ $json.Name }}`. It works in the test mode but when the workflow is activated the production form fails after the submission.
> 
> ![image](https://private-user-images.githubusercontent.com/107574310/393863948-052cbd98-fd5a-4ffd-8acd-200887735610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTU0MTksIm5iZiI6MTczMzgxNTExOSwicGF0aCI6Ii8xMDc1NzQzMTAvMzkzODYzOTQ4LTA1MmNiZDk4LWZkNWEtNGZmZC04YWNkLTIwMDg4NzczNTYxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNzE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWFkNzVhNjFhOGVmMzgzOWFjM2YyYWRiZDJhNWNlNzg1NDhkYWJlZWU3MjllM2YxOTY2N2NhOGVmY2JkZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0whhVYROFcomb7_11QTGGoLKBN_OIEIuGB9CcQO2R1M)
> 
> Browser network tab shows the initial POST succeeds but the GET request to the `form-waiting` endpoint responds with 500 with the following error.
> 
> ```json
> {"code":0,"message":"Cannot read properties of undefined (reading 'disabled')"}
> ```
> 
> Manually navigating to the form waiting endpoint provides the correct response.
> 
> ![image](https://private-user-images.githubusercontent.com/107574310/393867998-7fe79b02-4b27-41de-8c9c-8bf82bfc5564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTU0MTksIm5iZiI6MTczMzgxNTExOSwicGF0aCI6Ii8xMDc1NzQzMTAvMzkzODY3OTk4LTdmZTc5YjAyLTRiMjctNDFkZS04YzljLThiZjgyYmZjNTU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNzE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2U1NDIwNTEwMjUwMWVmMjZiNjM5ZDVlYjM3ODNiMWUzNDEyMmJjNjQ3Mjk3Mzc2MDYyMGVkY2Q1Njk0NWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u8DYhhYfydGVAJd_b2IuODdVA45X7ic1MgwzYuXioXM)
> 
> Strangely enough, putting a 2 seconds delay between the nodes solved the issue. It looks like there's a queue issue somewhere but I have no idea on how to debug the issue.
> 
> ![image](https://private-user-images.githubusercontent.com/107574310/393868642-935b5ecb-59f4-4459-80c9-c2a70dacc64c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTU0MTksIm5iZiI6MTczMzgxNTExOSwicGF0aCI6Ii8xMDc1NzQzMTAvMzkzODY4NjQyLTkzNWI1ZWNiLTU5ZjQtNDQ1OS04MGM5LWMyYTcwZGFjYzY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNzE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjk2ODkzODU4YWFlOWRmODUxZDVlNGQ0M2JjYmQwNDA4MmVmZjg4MzJkNWQzNWMwNmZjZWI3ZjdkOWFhODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VSJyWIuMLVqf2nmb_9M2TtS07nRuePezen8LHZdhwZI)

Your method is effective!

**Comment by nepomuc** [comment]
Unfortunately @MarleTangible 's hack doesn't work for me. Still an infinite pending/waiting status:
![image](https://github.com/user-attachments/assets/8bc25106-d9a0-422d-88c7-bf119b3ee14b)
When I'm calling the /form-waiting/123456 url manually I also don't get a response. The request is also pending forever.

**Comment by nepomuc** [comment]
Btw there's also a discussion about the same topic here: https://community.n8n.io/t/bug-report-n8n-forms-next-form-page-not-triggering/60938/19

**Comment by vbarrier** [comment]
So sad, that it makes the form node feature almost not usable at the moment.

**Comment by FlorianWilhelm** [comment]
Being able to submit the form in order to get specific information for the next, is a necessary feature for a lot of use-cases we are dealing with. 

Is anyone already working on this? Any theories what the problem is?

**Comment by washcroft** [comment]
Same issue, to resolve it (temporary workaround) adding a 1 second Wait node before the next form page seem to do the trick.

**Comment by nepomuc** [comment]
> Same issue for us. To resolve it (temporary workaround) **adding a 1 second Wait node before the next form page seem to do the trick**.
> 
> Somebody above said this trick didn't work, but it definitely does for us. Perhaps related to: [#12636](https://github.com/n8n-io/n8n/pull/12636)

Unfortunately it doesn't work on my setup :/ I've tried all the workarounds I was able to find, but none of them work. So I had to let go of n8n forms and switched to formbricks in the meantime. Of course this is suboptimal. Still hoping that this issue will be resolved soon. :)

**Comment by akhudolev** [comment]
Having same issue with big Workflow, small one works as expected. n8n works in queue mode with workers

**Comment by imnamanmodi1** [comment]
+1

```
- n8nVersion: 1.76.1
- platform: nginx
- database: postgres
- executionMode: queue
- n8n: 1
- webhooks: 2
- workers: 2
- redis: 1
- license: community
```

**Comment by jhonathas** [comment]
+1 

Version 1.84.0

**Comment by Joffcom** [comment]
This should be resolved now, can anyone share a minimal workflow that reproduces this issue along with their n8n configuration so we can try to reproduce it?

**Comment by vbarrier** [comment]
Hello @Joffcom, Indeed seems to work well since the 1.8.x version
