### ISSUE TITLE
Can't delete nodes when importing templates

### ISSUE THREAD

**Issue by Louis-pa** [n8n-io/n8n#11868]
### Bug Description

I often cannot delete any nodes (even when duplicating it) when starting from a template

### To Reproduce

Import template
try to delete node

### Expected behavior

I would expect to be able to delete nodes

### Operating System

mac

### n8n Version

last

### Node.js Version

20.x

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Louis-pa,

We have created an internal ticket to look into this which we will be tracking as "GHC-491"

**Comment by Joffcom** [comment]
Hey @Louis-pa,

I have just tried to reproduce this but I am able to delete nodes, Can you provide some more information.

1) Which template are you using?
2) Which version of n8n are you running?
3) Which browser are you using?
4) Are you using the new canvas?

**Comment by Joffcom** [comment]
@Louis-pa what happens when you try to delete a node? Do you see any errors or does it just not do anything? If you check your browser console does it show any errors?

Are you also connecting directly to your n8n instance or are you going through a reverse proxy, If you are going through a reverse proxy which one are you using?

**Comment by Louis-pa** [comment]
I got this in console : TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at deleteConnectionsByNodeId (:5678/assets/NodeVie…NfOOUof.js:33479:48)
    at deleteNode (:5678/assets/NodeVie…CNfOOUof.js:32886:5)
    at onDeleteNode (:5678/assets/NodeVie…CNfOOUof.js:34375:7)
    at callWithErrorHandling (:5678/assets/index-40I5DMGP.js:2169:19)
    at callWithAsyncErrorHandling (:5678/assets/index-40I5DMGP.js:2176:17)
    at emit (:5678/assets/index-40I5DMGP.js:7027:5)
    at onDeleteNode (:5678/assets/NodeVie…CNfOOUof.js:31877:7)
    at callWithErrorHandling (:5678/assets/index-40I5DMGP.js:2169:19)
    at callWithAsyncErrorHandling (:5678/assets/index-40I5DMGP.js:2176:17)
    
    
    Nothing really happen when I try to delete a node, expect in console. 
    
    I'm connecting directly to my n8n instance, it runs locally for now.

**Comment by MiloradFilipovic** [comment]
Hey @Louis-pa,
I also tried importing quite a few workflows to my local instance using Arc browser on Mac and couldn't reproduce. I have a few more questions:

1. How are you importing a template? By clicking the `Use Workflow` button on the website or copying the template JSON?
2. Is the error happening when you try to delete a node via keyboard shortcut or clicking delete button for the node?

Thanks in advance

**Comment by mutdmour** [comment]
@Louis-pa Hello. I am helping look into this. Would be great if you can answer @MiloradFilipovic's questions and also share the template you tried to template please. Thanks!

**Comment by mutdmour** [comment]
Actually found the issue in our error traces.
Here's how to reproduce: 
1. Open template at /workflows/templates/2320
2. Try to delete node 

Will have fix soon

**Comment by Louis-pa** [comment]
Great !! Sorry for the late reply, I didn't have time to work back on it (and it wasn't a big issue as the flow was running properly anyway

Thanks a lot
