### ISSUE TITLE
SFTP Connection Error in n8n Workflow

### ISSUE THREAD

**Issue by ptn-aviation** [n8n-io/n8n#11911]
### Bug Description

We are encountering an issue in our n8n workflow where the system fails to establish an SFTP connection with private key, resulting in the following error message being logged multiple times:

end: No SFTP connection available
Error: end: No SFTP connection available

Error Stack Trace:

at fmtError (/usr/local/lib/node_modules/n8n/node_modules/ssh2-sftp-client/src/utils.js:55:18)
at haveConnection (/usr/local/lib/node_modules/n8n/node_modules/ssh2-sftp-client/src/utils.js:319:20)
at /usr/local/lib/node_modules/n8n/node_modules/ssh2-sftp-client/src/index.js:1226:11
at new Promise (<anonymous>)
at SftpClient.end (/usr/local/lib/node_modules/n8n/node_modules/ssh2-sftp-client/src/index.js:1217:12)
at Object.sftpConnectionTest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Ftp/Ftp.node.js:411:36)
at CredentialsService.test (/usr/local/lib/node_modules/n8n/dist/credentials/credentials.service.js:248:16)
at CredentialsController.testCredentials (/usr/local/lib/node_modules/n8n/dist/credentials/credentials.controller.js:111:16)
at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26

### To Reproduce

Integrate the SFTP node in the n8n workflow.
Configure the SFTP credentials using valid url, username, private key
Trigger the workflow to execute.
Observe the error messages logged regarding the lack of an SFTP connection.

### Expected behavior

The workflow should successfully connect to the SFTP server and execute without error.

### Operating System

docker (self-hosted)

### n8n Version

1.68.1

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ptn-aviation,

We have created an internal ticket to look into this which we will be tracking as "GHC-506"

**Comment by Joffcom** [comment]
Hey @ptn-aviation,

Is your key in SSH2 or OpenSSH format? Do you also know what type of SSH / SFTP server you are connecting to?

**Comment by ptn-aviation** [comment]
Hello,
the Key is in OpenSSH Format, Example Key (not used by anything!)

-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAA...
-----END OPENSSH PRIVATE KEY-----

I just copy & paste it into the node configuration

I am not sure of what type of SSH/SFTP this is, unfortunately. Is there something I can check with ssh shell maybe?

Thanks!

**Comment by Joffcom** [comment]
Hey @ptn-aviation,

I have just given it a quick test using SFTP with OpenSSH and it has worked as expected 🤔

Does the server use an allow list for connections or anything like that?

**Comment by ptn-aviation** [comment]
I just checked it with plain sftp command and you're right. Seems like that there is a IP blacklist or something.

Thanks for the hint!
