### ISSUE TITLE
HTTP Request with  Auth set to OAuth2 API Client Credentials is not working

### ISSUE THREAD

**Issue by artsiommiksiuk** [n8n-io/n8n#11957]
### Bug Description

On cloud version of n8n (1.66.0) I'm getting "Unable to sign without access token" when using HTTP Request node with OAuth2 Generic setup.

![Untitled](https://github.com/user-attachments/assets/6ebf1e0f-3db9-42bd-89c4-308d1778f014)

While on self-hosted docker n8n (1.69.2), the same configuration works fine. I'm starting to receive responses from my target API, and don't have any "Unable to sign without access token".

### To Reproduce

1. Create HTTP Request node.
2. Configure it as per screenshot above.
3. Create OAuth2 Credentials.
  3.1 Grant Type: Client Credentials
  3.2 Client ID: ...
  3.3 Client Secret: ...
  3.4 Scope: <empty>
  3.5 Authentication: Header
  3.6 Ignore SSL Issues: false
4. Test the HTTP Request node.

### Expected behavior

I'm not getting "Unable to sign without access token", and instead has the same behaviour as on self hosted docker version.

### Operating System

MacOS 14.5

### n8n Version

1.66.0

### Node.js Version

20.11.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @artsiommiksiuk,

We have created an internal ticket to look into this which we will be tracking as "GHC-523"

**Comment by eyeswideopen** [comment]
same issue here

**Comment by Joffcom** [comment]
@artsiommiksiuk this is going to be tricky to work out what is going on, Is the API you are using public so we can check it? Other services appear to be ok so I suspect this is either a misconfiguration or a non-standard implementation of OAuth.

**Comment by Joffcom** [comment]
Hey @artsiommiksiuk,

As we haven’t heard back from you, we’re going to close this issue to keep things organized. But don’t worry—if you have more information or need further assistance, you’re welcome to reopen the issue anytime or create a new one. We’re always happy to help! 😊

Thanks for reaching out and have a great day!

**Comment by HT-Moh** [comment]
I am having same issue with Twitter API 

n8n Version1.74.1

```

NodeApiError: Unable to sign without access token at ExecuteContext.twitterApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Twitter/V2/GenericFunctions.js:41:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Twitter/V2/TwitterV2.node.js:171:40) at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:632:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:872:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1206:20
```

![image](https://github.com/user-attachments/assets/29786f40-986c-4a56-b3c9-1f6ae8bc2f7f)
