### ISSUE TITLE
Airtable nodes fail if table name is switched. Work only for one table with witch it was created / ran first.

### ISSUE THREAD

**Issue by NanisTe** [n8n-io/n8n#12046]
### Bug Description

I duplicated a working workflow with Airtable nodes which Create or Update a table record. I had to switch those to a duplicated airtable table (AirTEST) to test something.

I switched the tables in the node. Had manually mapped from start with some columns with expressions.

Running a test workflow lets fail airtable nodes with error below. Switching back to the original tables everything works fine. Rebuilding the nodes from scratch pointing to AirTEST work fine. But suddenly switching back to the original Airtable table fails with same error. It seems one can not switch between those tables within the node. Although airtable nodes are exactly the same and permissions actually work for both situations.

```
{
  "errorMessage": "Forbidden - perhaps check your credentials?",
  "errorDescription": "Invalid permissions, or the requested model was not found. Check that both your user and your token have the required permissions, and that the model names and/or ids are correct.",
  "errorDetails": {
    "rawErrorMessage": [
      "403 - {\"error\":{\"type\":\"INVALID_PERMISSIONS_OR_MODEL_NOT_FOUND\",\"message\":\"Invalid permissions, or the requested model was not found. Check that both your user and your token have the required permissions, and that the model names and/or ids are correct.\"}}"
    ],
    "httpCode": "403"
  },
  "n8nDetails": {
    "nodeName": "Create / Update Customer",
    "nodeType": "n8n-nodes-base.airtable",
    "nodeVersion": 2.1,
    "resource": "record",
    "operation": "upsert",
    "itemIndex": 0,
    "time": "4.12.2024, 16:20:57",
    "n8nVersion": "1.64.3 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: Forbidden - perhaps check your credentials?",
      "    at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1305:19)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2095:20)",
      "    at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:27:12)",
      "    at Object.batchUpdate (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/transport/index.js:89:24)",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/record/upsert.operation.js:83:32)",
      "    at Object.router (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/actions/router.js:48:30)",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/v2/AirtableV2.node.js:21:16)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51"
    ]
  }
}
```

### To Reproduce

1. Create Airtable credentials
2. Create two identical airtable tables. (actually one base in airtable is older and I cloned it. I dont know if tables in airtable have versions)
3. Build a Airtable node which creates or updates a record in one of the tables. Run it.
4. Switch to the other table in the node and run it again.
5. It should give you an error.

Used Docker image sha256:97cd6e02b70cca9181911b6be1d98ab5ddb4849249249030fcb910a64fdf4ad6

### Expected behavior

I expact to be able to clone an airtable table to test some things and therefore being able to switch between tables in Airtable nodes in n8n.

### Operating System

n8n Docker Image

### n8n Version

1.64.3

### Node.js Version

docker image sha256:97cd6e02b70cca9181911b6be1d98ab5ddb4849249249030fcb910a64fdf4ad6

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @NanisTe,

We have created an internal ticket to look into this which we will be tracking as "GHC-558"

**Comment by Joffcom** [comment]
Hey @NanisTe,

How are you changing between the tables? One thing we do know is the fields may have unique ids so if you don't refresh the column field so it pick up the values for the new table it will fail.

**Comment by NanisTe** [comment]
Hi @Joffcom 

I am changing airtable base byID and I am using the right IDs of the airtable bases. I just came into this issue again. I had a working node. I changed from FromList selection to ByID and it fails.
