### ISSUE TITLE
docker image is broken

### ISSUE THREAD

**Issue by albjeremias** [n8n-io/n8n#12088]
### Bug Description

```
app_1  | ENOENT: no such file or directory, mkdir '/home/node/.n8n/binaryData'
app_1  | Error: ENOENT: no such file or directory, mkdir '/home/node/.n8n/binaryData'
app_1  |     at Object.mkdir (node:internal/fs/promises:858:10)
app_1  |     at assertDir (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/BinaryData/utils.js:27:9)
app_1  |     at FileSystemManager.init (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/BinaryData/FileSystem.manager.js:21:9)
app_1  |     at BinaryDataService.init (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/BinaryData/BinaryData.service.js:66:13)
app_1  |     at Start.initBinaryDataService (/usr/local/lib/node_modules/n8n/dist/commands/base-command.js:184:9)
app_1  |     at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/start.js:170:9)
app_1  |     at Start._run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/command.js:301:13)
app_1  |     at Config.runCommand (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/config/config.js:424:25)
app_1  |     at run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/main.js:94:16)
app_1  |     at /usr/local/lib/node_modules/n8n/bin/n8n:71:2
```

### To Reproduce

docker-compose.yml
```
services:
  app:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "5678:5678"
```

`$ docker-compose up`

### Expected behavior

i expect to n8n to start without any errors

### Operating System

ubuntu

### n8n Version

latest

### Node.js Version

20

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @albjeremias,

We have created an internal ticket to look into this which we will be tracking as "GHC-577"

**Comment by albjeremias** [comment]
> Hey @albjeremias,
> 
> We have created an internal ticket to look into this which we will be tracking as "GHC-577"

where do I see the internal ticket? and why you delete all basic UNIX tools on your docker image? such as "whoami" "id" "cat" "grep" "apk" makes no sense.

**Comment by Joffcom** [comment]
Hey 

It is an internal ticket so it isn't something you would be able to see but it helps us link things together so we can reply back once we have looked.

We include a few of the basic Unix tools in the image however we use Alpine which is cut down to save space, whoami and apk should work did you get an error when trying?

**Comment by albjeremias** [comment]
well to be fair, and following the official [documentation](https://docs.n8n.io/hosting/installation/docker/#prerequisites) i get this errors:
```
# docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (audit)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (base-command)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (execute-batch)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (execute)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (start)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (webhook)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (worker)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (export:credentials)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (export:workflow)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (import:credentials)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (import:workflow)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (ldap:reset)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (license:clear)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (license:info)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (list:workflow)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (mfa:disable)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (update:workflow)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
(node:6) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (user-management:reset)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Error parsing n8n-config file "/home/node/.n8n/config". It does not seem to be valid JSON.
See more details with DEBUG=*
 ›   Error: command start not found
```


and using docker-compose.yml, runing the cat command, or any of those listed above:
```
 docker-compose run app cat /etc/passwd
Creating n8nnoserversnomastersnet_app_run ... done
No encryption key found - Auto-generated and saved to: /home/node/.n8n/config
 ›   Error: command cat not found
ERROR: 2
```

**Comment by albjeremias** [comment]
damn, sorry was some issue with creating the volume. closing
