### ISSUE TITLE
onedrive download fails with error 401

### ISSUE THREAD

**Issue by mrrudy** [n8n-io/n8n#12225]
### Bug Description

other onedrive operations up to get a file work, however when trying to download error 401 is thrown. using same credentials, self-hosted instance.  other users seemed to report [similar issue](https://community.n8n.io/t/cant-download-files-from-one-drive/61346/7).
```
{
  "errorMessage": "Authorization failed - please check your credentials",
  "errorDescription": "Unauthenticated",
  "errorDetails": {
    "rawErrorMessage": [
      "401 - \"{\\\"error\\\":{\\\"code\\\":\\\"unauthenticated\\\",\\\"message\\\":\\\"Unauthenticated\\\"}}\""
    ],
    "httpCode": "401"
  },
  "n8nDetails": {
    "nodeName": "Microsoft OneDrive1",
    "nodeType": "n8n-nodes-base.microsoftOneDrive",
    "nodeVersion": 1,
    "resource": "file",
    "operation": "download",
    "time": "13.12.2024, 21:44:23",
    "n8nVersion": "1.71.3 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: Authorization failed - please check your credentials",
      "    at ExecuteContext.microsoftApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Microsoft/OneDrive/GenericFunctions.ts:47:9)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDrive.node.ts:121:22)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1394:8)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1173:27",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1894:11"
    ]
  }
}
```

### To Reproduce

add Microsoft OneDrive download file node, put as ID either static string id (from OneDrive URL) or get it from previous node like getChildren: folder (which works with the same credentials without issues). 

### Expected behavior

file download into data binary field

### Operating System

debian 12.8

### n8n Version

1.71.3

### Node.js Version

v18.19.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mrrudy,

We have created an internal ticket to look into this which we will be tracking as "N8N-7963"

**Comment by tiagocaus** [comment]
UP

**Comment by ShireenMissi** [comment]
Hi @tiagocaus, 
I tried to reproduce the issue on n8n version 1.75.1, but I couldn't. Could you please try upgrading your n8n version and testing again? If the issue persists, feel free to reopen this one or create a new issue.
Thank you 🙏

**Comment by ljp-solutions** [comment]
I still see this exact issue in 1.75.2 (Cloud):

{
  "errorMessage": "Authorization failed - please check your credentials",
  "errorDescription": "Unauthenticated",
  "errorDetails": {
    "rawErrorMessage": [
      "401 - \"{\\\"error\\\":{\\\"code\\\":\\\"unauthenticated\\\",\\\"message\\\":\\\"Unauthenticated\\\"}}\""
    ],
    "httpCode": "401"
  },
  "n8nDetails": {
    "nodeName": "Microsoft OneDrive2",
    "nodeType": "n8n-nodes-base.microsoftOneDrive",
    "nodeVersion": 1,
    "resource": "file",
    "operation": "download",
    "time": "17/01/2025, 15:41:42",
    "n8nVersion": "1.75.2 (Cloud)",
    "binaryDataMode": "filesystem",
    "stackTrace": [
      "NodeApiError: Authorization failed - please check your credentials",
      "    at ExecuteContext.microsoftApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/OneDrive/GenericFunctions.js:34:15)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/OneDrive/MicrosoftOneDrive.node.js:97:40)",
      "    at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:632:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:890:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1224:20"
    ]
  }
}

**Comment by ljp-solutions** [comment]
thanks @Joffcom for re-opening

For reference for your engineers, I can use the same credentials to copy, rename and delete files. The only action that does not work is Download.

**Comment by janober** [comment]
Fix got released with [`n8n@1.79.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.79.0)
