### ISSUE TITLE
Migration script crash : AddMockedNodesColumnToTestDefinition1733133775640

### ISSUE THREAD

**Issue by mbakgun** [n8n-io/n8n#12304]
### Bug Description

```
User settings loaded from: /root/.n8n/config
Last session crashed
Initializing n8n process
n8n ready on 0.0.0.0, port 5678
Migrations in progress, please do NOT stop the process.
Starting migration AddMockedNodesColumnToTestDefinition1733133775640
Migration "AddMockedNodesColumnToTestDefinition1733133775640" failed, error: BLOB, TEXT, GEOMETRY or JSON column 'mockedNodes' can't have a default value
There was an error running database migrations
Error: There was an error running database migrations
    at Start.exitWithCrash (/usr/local/lib/node_modules/n8n/dist/commands/base-command.js:116:49)
    at /usr/local/lib/node_modules/n8n/dist/commands/base-command.js:87:62
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/base-command.js:87:9)
    at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/start.js:160:9)
    at Start._run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/command.js:301:13)
    at Config.runCommand (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/config/config.js:424:25)
    at run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/main.js:94:16)
    at /usr/local/lib/node_modules/n8n/bin/n8n:71:2

BLOB, TEXT, GEOMETRY or JSON column 'mockedNodes' can't have a default value
QueryFailedError: BLOB, TEXT, GEOMETRY or JSON column 'mockedNodes' can't have a default value
    at Query.onResult (/usr/local/lib/node_modules/n8n/node_modules/@n8n/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.execute (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
```

### To Reproduce

Update the Docker image and run n8n cointainer. 

### Expected behavior

When Watchtower received the latest update, it couldn't run the migration script for MySQL.

I expect n8n to start up.

```
Watchtower updates on 1c4dc7c3eb8a
Found new [docker.n8n.io/n8nio/n8n:latest](http://docker.n8n.io/n8nio/n8n:latest) image (139317e73218)
Stopping /n8n (d3eb3033430c) with SIGTERM
Creating /n8n
Removing image 352529759efc
```

### Operating System

Ubuntu Linux 22.04

### n8n Version

latest

### Node.js Version

	20.18.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mbakgun,

We have created an internal ticket to look into this which we will be tracking as "N8N-7992"

**Comment by burivuhster** [comment]
@mbakgun can you please share which version of MySQL you use?

**Comment by mbakgun** [comment]
> @mbakgun can you please share which version of MySQL you use?

```
ubuntuserver% mysql -V
mysql  Ver 8.0.40-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
```

**Comment by mbakgun** [comment]
And also, when the update came yesterday, I encountered error 1.72.1 (on the latest); before that, version 1.71.2 was installed and was running well.

**Comment by Ttipi** [comment]
I have the same problem with the same logs. 
The latest working version for me is 1.71.3
N8N is installed in docker under Ubuntu 24.04.1 and MySQL is on version 8.0.40-0ubuntu0.24.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by Ttipi** [comment]
> Hi @Ttipi , I believe the n8n team will include that merged fix in the next release of n8n. Meanwhile, I transitioned from my Ubuntu server to a Mac Mini device. During this process, I included PostgreSQL within my Docker Compose containers to work with n8n. And I'm happy with that :) Just wanted to tell..
> 
> Since PostgreSQL is recommended, I prefer to proceed this way.

Thank you, pleased that it works for U, but I only got a MySQL server... I'll wait to upgrade so

**Comment by janober** [comment]
Fix got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)
