### ISSUE TITLE
Qdrant collections can't be listed in a hosted environement

### ISSUE THREAD

**Issue by nicolas-geysse** [n8n-io/n8n#12381]
### Bug Description

Hello,
I may create, list, and anything I want using http request node to connect a Cloud version but also a hosted version of Qdrant.
In the n8n Qdrant node, I may list the collections directly without any problems, but it fails for the hosted version.
![Capture d'écran 2024-12-27 005856](https://github.com/user-attachments/assets/7b219594-b6f8-4f7a-9879-8b32685375f1)
![Capture d'écran 2024-12-27 005928](https://github.com/user-attachments/assets/a9ea19c8-04de-4e06-b2f3-d8719c1b3a0b)
![hosted](https://github.com/user-attachments/assets/16d61b07-8292-4d0d-b056-22b5613c7a56)

### To Reproduce

1.Host an instance of Qdrant in your infrastructure.
2.Create your credentials, the connection with the credentials is working fine
3.Use the Qdrant node to list collections.
4. :(
5. Do that with the Cloud version of Qdrant
6.  :) 

### Expected behavior

As my connection between n8n and my hosted version of Qdrant, it should handle the same way the Cloud version.

### Operating System

?

### n8n Version

1.72.1

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @nicolas-geysse,

We have created an internal ticket to look into this which we will be tracking as "N8N-8014"

**Comment by Joffcom** [comment]
Hey @nicolas-geysse 

Just to check are you using localhost as the host address for your local qdrant instance?

**Comment by nicolas-geysse** [comment]
Hello @Joffcom 
No, it's hosted on Railway (Qdrant as n8n), proxied with Cloudflare.

**Comment by HT-Moh** [comment]
I have the same issue with Qdrant, my instance works, but when using n8n node for Qdrant credentials are green but I can not list the collections.

```bash
curl 'https://myqdrant_host_name/collections' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.7' \
  -H 'api-key: mytoken=' \
  -H 'content-type: application/json' \
  -H 'priority: u=1, i' \
  -H 'x-inference-proxy: true'
{"result":{"collections":[{"name":"contacts"}]},"status":"ok","time":0.00001614}
```

**Comment by jeanpaul** [comment]
@nicolas-geysse Ah, maybe it's something else... I tried a bit more and came to the conclusion that there might be an issue with saving the credential if you change the URL after you've entered the API key. Can you try re-entering your API key in the credential and saving it? You may need to use the three-dot menu near "Qdrant Collection" to refresh the list: 
<img width="479" alt="image" src="https://github.com/user-attachments/assets/9d4e147d-0939-47cb-b075-1ca51efaac77" />

**Comment by nicolas-geysse** [comment]
@jeanpaul Hello, I don't see anything special in my setup...I wonder if that might be related to IP v4 and v6 (not supported with n8n, but with Qdrant)
I've seen this topic that seems related
[](https://github.com/qdrant/qdrant/issues/5545)
I have this in my logs :
```
fetch failed

TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchJson (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:135:22)
    at /usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:46:26
    at handler (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:156:16)
    at /usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:32:24
    at handler (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:156:16)
    at fetchUrl (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:162:22)
    at Object.fun [as getCollections] (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:168:20)
    at QdrantClient.getCollections (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:836:26)
    at LoadOptionsContext.qdrantCollectionsSearch (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/nodes/vector_store/shared/methods/listSearch.js:51:22)
    at DynamicNodeParametersController.getResourceLocatorResults (/usr/local/lib/node_modules/n8n/dist/controllers/dynamic-node-parameters.controller.js:37:16)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
 
Connect Timeout Error
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/node_modules/undici/lib/core/connect.js:186:24)
    at /usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/node_modules/undici/lib/core/connect.js:133:46
    at Immediate._onImmediate (/usr/local/lib/node_modules/n8n/node_modules/@qdrant/js-client-rest/node_modules/undici/lib/core/connect.js:174:9)
    at processImmediate (node:internal/timers:483:21)
```

**Comment by jeanpaul** [comment]
@nicolas-geysse did you see my comment on re-adding your credential? If that's the issue, there should be a fix released soon. If that doesn't, we should look into it some more.

**Comment by nicolas-geysse** [comment]
@jeanpaul yes, I did that, same result. But it's getting weirder as if I set an empty API key in the credentials, the connection is allowed ! If I enter anything, it also works !
So I double checked the API key, it does exists, and I've tested this node into n8n :

```
async function execute() {
    const baseUrl = "https://myhostedqdrant";
    const apiKey = "myAPIkey";

    const options = {
        uri: `${baseUrl}/collections`,
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'api-key': apiKey
        },
        json: true,
        timeout: 15000
    };

    try {
        const data = await this.helpers.request(options);
        
        return [{
            json: {
                status: "success",
                collections: data,
                endpoint: baseUrl
            }
        }];

    } catch (error) {
        return [{
            json: {
                status: "error",
                message: error.message,
                endpoint: baseUrl,
                errorDetails: error.response ? error.response.data : null
            }
        }];
    }
}

return execute();
```

With an empty API key, or anything, it doesn't work. With the correct API key, no problem, I do have the list of my collections.

**Comment by jeanpaul** [comment]
We're aware that the credential-test (on the credential-screen) is not working as expected (it's requesting the wrong path that always succeeds, whether or not you provided correct credentials). However, if you added your API key again to the credential, saved it, and refreshed the collection-list while still coming up empty, I'm unsure of how to reproduce your issue. It might be that your host or cloudflare are doing something different (blocking the request maybe?)

**Comment by nicolas-geysse** [comment]
@jeanpaul I'd agree with your point if the custom code node given previously was not running smoothly on the same n8n instance that does not list the collections with the n8n Qdrant vector store...

In the .env I've added
NODE_FUNCTION_ALLOW_EXTERNAL=@qdrant/js-client-rest
to do so, and, here it works perfectly fine, so it does not seems to be a network issue here :(

I suspect that the node code might be more consistent in the IPv6 handling than the qdrant vector store node ? (I've recreated the credentials, refreshed, multiple times...)

Maybe it is on the Qdrant side that might handle connections in a more robust way on the cloud version ?
Or I'm doing something wrong, but I'm missing what...

If you use a n8n in queue mode with Qdrant locally, there's no issue for you I suppose ?

**Comment by jeanpaul** [comment]
I didn't try queue mode, but that shouldn't have any effect on retrieving the collections. The collection search method in n8n uses the `@qdrant/js-client-rest` method as well, so I don't know what could be the issue. Could you try and connect with an HTTP-node to your qdrant server and retrieve the collections? Please use "include response headers and status" from the Response option.

**Comment by nicolas-geysse** [comment]
@jeanpaul it works ! Something I see is that the port 6333 must not be set in that case.
![collection](https://github.com/user-attachments/assets/b39cb06f-d577-44f9-a6f9-f05257a1968c)

**Comment by nicolas-geysse** [comment]
I've created a tunnel with cloudflare :
Zero Trust > Networks > Tunnels

Deleted the CNAME entry

Created into Railway :
Connect to your service over TCP using a proxied domain and port
railway.proxy:12345 -> :6333

And it finally works but...In the log of n8n:
Api key is used with unsecure connection.

I think I may dig to internally share the service directly into Railway to connect n8n / Qdrant to avoid all this.

I also think this might be related:
https://github.com/qdrant/qdrant/issues/3890

**Comment by jeanpaul** [comment]
Hi @nicolas-geysse, glad to hear this resolved the issue. If you don't use TLS for the connection, it is indeed not a secured connection.

Thanks for reporting back.

**Comment by jeanpaul** [comment]
I don't know how well the qdrant SDK plays with TLS. The n8n code uses the SDK version that's supplied via LangChain. It could be an upstream issue, but I'm not able to help you out with that, sorry.

**Comment by RossoSwap** [comment]
Hello! How can I use then the Qdrant Vector Store if I have Qdrant on Railway?

**Comment by nicolas-geysse** [comment]
Hello,
I ended up deploying it in the the same environment, then I use the private url, so all is internal and all is working perfectly fine. (initially I had it in a different environment)

**Comment by HT-Moh** [comment]
The timeout issue still persist with last docker image 1.78.1

qdrant works : 
```
 curl 'https://qdrant.domain.ch/collections' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'api-key: ffhfgfjfjfj='

{"result":{"collections":[{"name":"star_charts"},{"name":"assistant_contacts"},{"name":"tweets"}]},"status":"ok","time":0.000011624
```

```
n8n ready on 0.0.0.0, port 5678
n8n detected that some packages are missing. For more information, visit https://docs.n8n.io/integrations/community-nodes/troubleshooting/
Collaboration features are disabled because push is configured unidirectional. Use N8N_PUSH_BACKEND=websocket environment variable to enable them.
Version: 1.78.1
================================
Start Active Workflows:
================================
- "Assistant" (ID: aphvO9uFMEy0qKfr)
=> Started
Editor is now accessible via:
http://localhost:5678/
fetch failed
Connect Timeout Error
```

**Comment by leorebok** [comment]
In version 1.79.2, I also encounter the issue where collections are not listed when using Qdrant self-host.

The credentials authenticate correctly.
But when I try to list the collections, the log says: 

`fetch failed
connect ECONNREFUSED <IP>:6333.`

In the credentials I configure n8n to access the domain https://qdrant.domain.com  (I have a reverse proxy for the Docker containers), but I don't know how n8n tries to obtain the collections with the IP and port if I never told them.

Additionally, there is a URL validation that doesn't allow entering the Docker service name.

**Comment by HT-Moh** [comment]
I fixed the issue by changing the domain to point to the qdrant service, in my case http://qdrant.qdrant.svc.cluster.local:6333

**Comment by leorebok** [comment]
Yes, thanks! After a lot of research and testing, that way also worked for me: http://<service_name>:6333.

However, I couldn't get it to work with Qdrant self-hosted over HTTPS, but this solution still helped me.

**Comment by ndgayan** [comment]
Still not working on Qdrant self-hosted over HTTPS using docker. The connection info is below.

For example, the Qdrant URL is https://qdrant.example.com with an API key.

After digging deeper, the JS Library's URL should look like this -> https://www.npmjs.com/package/@qdrant/js-client-rest

Code in JS Library -> https://github.com/qdrant/qdrant-js/blob/1c43b2db971367ece3788c4b6c368a1604b29530/packages/js-client-rest/src/qdrant-client.ts#L72

FYI: No access issues to the collection. I tested using the HTTP request node, and it is working fine.

**Comment by james-potter** [comment]
I believe the problem is with qdrant/js-client-rest.  After doing some testing with the following code

```
const { QdrantClient } = require("@qdrant/js-client-rest");
const dotenv = require("dotenv");
dotenv.config();

async function testQdrant() {
    try {
        const qdrant = new QdrantClient({
            url: process.env.QDRANT_URL, // e.g., "http://your-qdrant-server:6333"
            apiKey: process.env.QDRANT_API_KEY,  // Optional, if authentication is needed
            checkCompatibility: false
        });

        const collections = await qdrant.getCollections();
        console.log("Collections:", collections);
    } catch (error) {
        console.error("Error fetching collections:", error);
    }
}

testQdrant();
```

If I open port 6333 on the firewall it can connect to QDrant and N8N can also connect.  Works when QDrant configured as HTTP or HTTPS this way.
When port is closed and connecting via proxy it fails in code and N8N.

CURL commands work via proxy without a problem, so from this it would indicate it is the js-client-rest that has the problem.

I've raised an issue on the js-client-rest github: https://github.com/qdrant/qdrant-js/issues/94
