### ISSUE TITLE
500 Response when loading GET /rest/users

### ISSUE THREAD

**Issue by majdalsado** [n8n-io/n8n#12407]
### Bug Description

The home page which shows a list of workflows is failing to load due to a 500 error on the GET /rest/users endpoint.

I'm deploying the latest n8nio/n8n image from Docker, running on Railway. It was working fine before today.

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/d197ecfd-2b9a-420e-b4b8-eee6ad127b55" />

# Debug info

## core

- n8nVersion: 1.72.1
- platform: npm
- nodeJsVersion: 20.18.0
- database: postgres
- executionMode: scaling
- concurrency: -1
- license: enterprise (production)
- consumerId: f2de1842-26ba-43c3-854f-64f5fd6dc636

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2024-12-30T20:31:33.385Z

### To Reproduce

1. Go to home page
2. Workflow list fails to load
3. Console shows a failed request to /rest/users which returns a 500 error.

### Expected behavior

For the workflow list to show

### Execution mode

main (default)

Server side error:

> TypeError: Invalid URL
> 
>     at new URL (node:internal/url:806:29)
> 
>     at UserService.addInviteUrl (/usr/local/lib/node_modules/n8n/dist/services/user.service.js:71:21)
> 
>     at UserService.toPublic (/usr/local/lib/node_modules/n8n/dist/services/user.service.js:60:31)
> 
>     at /usr/local/lib/node_modules/n8n/dist/controllers/users.controller.js:77:93
> 
>     at Array.map (<anonymous>)
> 
>     at UsersController.listUsers (/usr/local/lib/node_modules/n8n/dist/controllers/users.controller.js:77:53)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
> 
>     at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26

**Comment by Joffcom** [comment]
Hey @majdalsado,

We have created an internal ticket to look into this which we will be tracking as "N8N-8025"

**Comment by netroy** [comment]
Do you have `N8N_EDITOR_BASE_URL` or `WEBHOOK_URL` env variables set? if yes, can you if which ever of these is set, the value is a valid url, starting with a `http://` or `https://` ?

**Comment by netroy** [comment]
looking at the URL from the screenshot, I see that you have `N8N_EDITOR_BASE_URL` set to `primary-production-3464.up.railway.app`. Can you please remove that, and restart your instance?

**Comment by majdalsado** [comment]
Both `N8N_EDITOR_BASE_URL` and `WEBHOOK_URL` were set. I've removed the `N8N_EDITOR_BASE_URL` which seems to fix it. Any clue why that is? It was working fine before.

**Comment by Joffcom** [comment]
Hey @majdalsado,

You only need `N8N_EDITOR_BASE_URL` set if you are using 2 different URLs but they need to be the complete fqdn including protocol. If you had `N8N_EDITOR_BASE_URL` set to just `primary-production-3464.up.railway.app` it should always have failed so it could be that a recent change has corrected this.

For now though as it seems like you are up and running I will get this one closed, Let us know if you have any other questions.

**Comment by tamutus** [comment]
Same problem, same solution! I expect we went through similar forum posts trying to get the webhook URL to work on Railway.
