### ISSUE TITLE
(Almost) every night webhooks unhook

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1881]
**Describe the bug**
Every night webhooks unhook: previously active workflows fail to take calls. They are still marked as active in the UI. 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/193115/121479116-00448780-c9ca-11eb-827f-df7fbd4bc9ef.png" style="float:right">

**To Reproduce**
This problem happens sporadically intensively. I.e. it doesn't happen for a long time, then it happens every day.

When a "parent" workflow tries to call the webhooks, this happens:

```json
﻿﻿{
  "status": "rejected",
  "reason": {
    "name": "StatusCodeError",
    "statusCode": 404,
    "message": "404 - {\"code\":404,\"message\":\"The requested webhook \\\"POST export-results-daily\\\" is not registered.\",\"stack\":\"ResponseError: The requested webhook \\\"POST export-results-daily\\\" is not registered.\\n    at ActiveWorkflowRunner.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/ActiveWorkflowRunner.js:74:23)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\n    at async /usr/local/lib/node_modules/n8n/dist/src/WebhookServer.js:62:24\"}",
    "error": {
      "code": 404,
      "message": "The requested webhook \"POST export-results-daily\" is not registered.",
      "stack": "ResponseError: The requested webhook \"POST export-results-daily\" is not registered.\n    at ActiveWorkflowRunner.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/ActiveWorkflowRunner.js:74:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /usr/local/lib/node_modules/n8n/dist/src/WebhookServer.js:62:24"
    },
    "options": {
      "timeout": 3600000,
      "headers": {
        "accept": "application/json,text/*;q=0.99"
      },
      "method": "POST",
      "uri": "http://localhost:5678/webhook/export-results-daily",
      "gzip": true,
      "rejectUnauthorized": true,
      "body": {
         "censured": true
       },
      "json": true,
      "simple": true,
      "resolveWithFullResponse": false,
      "transform2xxOnly": false
    },
    "response": {
      "statusCode": 404,
      "body": {
        "code": 404,
        "message": "The requested webhook \"POST export-results-daily\" is not registered.",
        "stack": "ResponseError: The requested webhook \"POST export-results-daily\" is not registered.\n    at ActiveWorkflowRunner.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/ActiveWorkflowRunner.js:74:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /usr/local/lib/node_modules/n8n/dist/src/WebhookServer.js:62:24"
      },
      "headers": {
        "x-powered-by": "Express",
        "access-control-allow-origin": "http://localhost:8080",
        "access-control-allow-methods": "GET, POST, OPTIONS, PUT, PATCH, DELETE",
        "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, sessionid",
        "content-type": "application/json; charset=utf-8",
        "content-length": "495",
        "etag": "W/\"1ef-0FBCwfXjbMnD/PVBQJRiFz/ac8c\"",
        "vary": "Accept-Encoding",
        "date": "Thu, 10 Jun 2021 04:31:00 GMT",
        "connection": "close"
      },
      "request": {
        "uri": {
          "protocol": "http:",
          "slashes": true,
          "auth": null,
          "host": "localhost:5678",
          "port": "5678",
          "hostname": "localhost",
          "hash": null,
          "search": null,
          "query": null,
          "pathname": "/webhook/export-results-daily",
          "path": "/webhook/export-results-daily",
          "href": "http://localhost:5678/webhook/export-results-daily"
        },
        "method": "POST",
        "headers": {
          "accept": "application/json,text/*;q=0.99",
          "accept-encoding": "gzip, deflate",
          "content-type": "application/json",
          "content-length": 195
        }
      }
    }
  }
}
```

(I've removed the sensitive data from the headers and body above)

Meanwhile in the logs:

```
n8n-69f647d67c-rxk8m n8n ERROR RESPONSE
n8n-69f647d67c-rxk8m n8n ResponseError: The requested webhook "POST export-results-daily" is not registered.
n8n-69f647d67c-rxk8m n8n     at ActiveWorkflowRunner.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/ActiveWorkflowRunner.js:74:23)
n8n-69f647d67c-rxk8m n8n     at runMicrotasks (<anonymous>)
n8n-69f647d67c-rxk8m n8n     at processTicksAndRejections (internal/process/task_queues.js:93:5)
n8n-69f647d67c-rxk8m n8n     at async /usr/local/lib/node_modules/n8n/dist/src/WebhookServer.js:62:24 {
n8n-69f647d67c-rxk8m n8n   errorCode: 404,
n8n-69f647d67c-rxk8m n8n   httpStatusCode: 404
n8n-69f647d67c-rxk8m n8n }
```

In the editor, the hooks looks OK

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/193115/121477196-d4c09d80-c9c7-11eb-8d9c-f2f08a78f969.png">

ometimes we use the designer-mode "Execute" from different laptops, while the workflow is active: from two different sessions run the workflow visually a bunch of times, not saving it, not changing its active state.

We sometimes run these flows manually, while they are active but without saving: Create a workflow with a hook and a shared header secret, activate it, call it with a Request node from another flow, it should work; then go to the child flow, run it manually, now go back to the parent caller and try calling the child's hook.

I just tested this and it works, but this is all that we do, and the webhooks stop working at some point.

**Expected behavior**

If the UI says a workflow is active, it should be active.

**Environment (please complete the following information):**
 - OS: COS
 - n8n Version: 0.123.1
 - Node.js Version: whatever the container has
 - Database system: postgres
 - Operation mode: google says nothing about what this means

**Additional context**
There are no other logs applicable; neither in the execution logs, container logs, nor caller logs. It reproduces frequently for us, but not deterministically and we can't "create a repro" for that reason.

**Comment by haf** [comment]
Same as https://github.com/n8n-io/n8n/issues/1873

**Comment by janober** [comment]
Did that solve your problem @haf?

**Comment by haf** [comment]
Yes

**Comment by janober** [comment]
That is great to hear. Then close this issue.
