### ISSUE TITLE
MS SQL Server Insert does not handle empty cells as NULL values

### ISSUE THREAD

**Issue by laurens-novyx** [n8n-io/n8n#1915]
**Describe the bug**
When the Microsoft SQL node is used with the operation INSERT it gives an error when a field is left empty.

**To Reproduce**
1. Create a Microsoft SQL Node
2. Choose the INSERT operation
3. Make sure there are one or more empty values in the input data
4. Try to insert the data into the database

**N8N Error**
RequestError: **Incorrect syntax near ','.**
    at handleError (/usr/local/lib/node_modules/n8n/node_modules/mssql/lib/tedious/request.js:374:15)
    at Connection.emit (events.js:315:20)
    at Parser.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:315:20)
    at Parser.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:315:20)
    at addChunk (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Parser.Readable.push (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Parser.Transform.push (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:139:32)

**Expected behavior**
The input data should be inserted into the database.

**Proposed solution**
Empty fields should not be left empty in the SQL-query. They should contain the value NULL so the SQL query going to Microsoft SQL goes from:
INSERT INTO table_name (field_1, field_2) VALUES ('test', )
to:
INSERT INTO table_name (field_1, field_2) VALUES ('test', _NULL_)

**Environment (please complete the following information):**
 - OS: GCloud Container Optimized OS (Docker image)
 - n8n Version  0.123.1
 - Database system: SQLite
 - Operation mode: own

**Additional context**
I think the fix can be made in the function _extractValues_ of:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Microsoft/Sql/GenericFunctions.ts

**Comment by BHesseldieck** [comment]
Is handled here: #1929 and [here](https://community.n8n.io/t/mssql-insert-missing-basic-functionality-null-handling-escape-quotes-string-processing/6435)
