### ISSUE TITLE
MS SQL Server Insert mistakenly interprets a string for an exponential number

### ISSUE THREAD

**Issue by laurens-novyx** [n8n-io/n8n#1920]
**Describe the bug**
When trying to input a string containing numbers and a single "e" the SQL Server node interprets this string as a exponential number (, which can be too large).

**To Reproduce**
1. Create a Microsoft SQL Node
2. Choose the INSERT operation
3. Make sure one of the values is: 5767e365-de98-4cf2-bd08-94f52ccbee56
4. Try to insert the data into the database
5. This will not work because the first part of the string contains a part with only numbers and the letter 'e'. Even though the rest of the string **does** contain other characters.

**N8N Error**
RequestError: **The floating point value '5767e365' is out of the range of computer representation (8 bytes).**
    at handleError (/usr/local/lib/node_modules/n8n/node_modules/mssql/lib/tedious/request.js:374:15)
    at Connection.emit (events.js:315:20)
    at Parser.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:315:20)
    at Parser.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:315:20)
    at addChunk (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Parser.Readable.push (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Parser.Transform.push (/usr/local/lib/node_modules/n8n/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:139:32)

**Expected behavior**
The input data should be inserted into the database.

**Environment:**
 - OS: GCloud Container Optimized OS (Docker image)
 - n8n Version  0.123.1
 - Database system: SQLite
 - Operation mode: own

**Additional context**
None.

**Comment by Md-Ridoy** [comment]
Ho

**Comment by BHesseldieck** [comment]
Thanks @laurens-novyx for your extensive work with the MS SQL Node! We highly apprecate it!

We use our [community forum](https://community.n8n.io/) for tracking bugs and new feature requests etc. and don't use Github issues. Could you gather your opened issues in a post/thread in our forum? We will denn add it to our process 😊 

Thanks a lot!

**Comment by laurens-novyx** [comment]
Hi Ben,

Thanks for your message. I have created a new thread in the community forum.
See: https://community.n8n.io/t/mssql-insert-missing-basic-functionality-null-handling-escape-quotes-string-processing/6435 <https://community.n8n.io/t/mssql-insert-missing-basic-functionality-null-handling-escape-quotes-string-processing/6435>

Kind regards,
Laurens

**Comment by BHesseldieck** [comment]
Thank you so much! You are amazing!
