### ISSUE TITLE
TypeError in HTTP Request node

### ISSUE THREAD

**Issue by Fx4-X** [n8n-io/n8n#1928]
**Describe the bug**
Getting "TypeError: str.replace is not a function" while using header "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"

it did work  until "application/x-www-form-urlencode" (char 32) adding anything after it generate the error 

**error**
`TypeError: str.replace is not a function
    at Querystring.rfc3986 (/usr/local/lib/node_modules/n8n/node_modules/request/lib/querystring.js:43:14)
    at Request.json (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:1287:30)
    at Request.init (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:406:10)
    at Request.RP$initInterceptor [as init] (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/n8n/node_modules/request/index.js:53:10)
    at Object.request (/usr/local/lib/node_modules/n8n/node_modules/request/index.js:100:12)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest.node.js:809:51)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:492:37)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:424:62`

**To Reproduce**
`{
  "name": "My workflow",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "requestMethod": "POST",
        "url": "https://example.com/ajaxCompanyList",
        "allowUnauthorizedCerts": true,
        "responseFormat": "string",
        "options": {},
        "bodyParametersUi": {
          "parameter": []
        },
        "headerParametersUi": {
          "parameter": [
            {
              "name": "Content-Type",
              "value": "application/x-www-form-urlencoded; charset=UTF-8"
            }
          ]
        },
        "queryParametersUi": {
          "parameter": []
        }
      },
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "position": [
        480,
        300
      ],
      "typeVersion": 1
    }
  ],
  "connections": {
    "HTTP Request": {
      "main": [
        []
      ]
    },
    "Start": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {}
}`

**Expected behavior**
expect a html output

**Environment (please complete the following information):**
 - OS: docker n8nio/n8n:0.125.0
 - n8n Version: 0.125.0

**Additional context**

**Comment by edlinklater** [comment]
When manually setting the Content-Type using Headers, n8n doesn't know that you are doing a form post and formats the key/value pairs as JSON.

You can avoid this by setting the Content-Type using the built-in option:

![image](https://user-images.githubusercontent.com/1176635/125837508-379c704e-b5f2-4568-b012-f464fc1d322c.png)

This alone will not include the `charset=UTF-8`, however you can still override that using the Headers. So the overall configuration would be:

![image](https://user-images.githubusercontent.com/1176635/125838099-c23f404a-7d88-41ca-a966-c0c93cb69ddb.png)

**Comment by ivov** [comment]
@Fx4-X Are you still facing this issue?

**Comment by ivov** [comment]
Closing for now. Feel free to comment here and we will reopen.
