### ISSUE TITLE
ERROR: End of data reached (data length = 1218705, asked index = 1218713). Corrupted zip ?

### ISSUE THREAD

**Issue by dariusj18** [n8n-io/n8n#2244]
**Describe the bug**
Spreadsheet file throws error when using Read as String option

**To Reproduce**
1. Create a Workflow
2. Use Read Binary Node and set to read an xlsx file
3. Use Spreadsheet File Node
4. Set Property Read as String to true
5. Execute workflow

**Expected behavior**
No error

**Environment (please complete the following information):**
 - OS: n8nio/n8n image
 - n8n Version 0.139.1
 - Node.js Version v14.15.5
 - Database system postgresql 11
 - Operation mode own

**Additional context**

```
Error: End of data reached (data length = 1218705, asked index = 1218713). Corrupted zip ?
    at Uint8ArrayReader.checkIndex (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:272:19)
    at Uint8ArrayReader.checkOffset (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:263:14)
    at Uint8ArrayReader.readData (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:1562:10)
    at Uint8ArrayReader.readString (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:321:49)
    at ZipEntries.readBlockEndOfCentral (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:2198:39)
    at ZipEntries.readEndOfCentral (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:2286:14)
    at ZipEntries.load (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:2344:14)
    at new ZipEntries (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:2168:14)
    at JSZipSync.module.exports [as load] (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:581:18)
    at new JSZipSync (/usr/local/lib/node_modules/n8n/node_modules/xlsx/jszip.js:528:14)
```

**Comment by dariusj18** [comment]
Nevermind, I see now that REad as String is to read the file as a string and isn't related to reading the spreadsheet data.
