### ISSUE TITLE
Airtable sort brakes request

### ISSUE THREAD

**Issue by arrowcircle** [n8n-io/n8n#2319]
**Describe the bug**
When I add any sort field to airtable list node, it shows error with request.

```txt
{"message":"Request failed with status code 422","name":"Error","stack":"Error: Request failed with status code 422\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}

NodeApiError: Your request is invalid or could not be processed by the service
    at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/GenericFunctions.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Airtable/Airtable.node.js:523:36)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:447:47
```

**To Reproduce**
1. Setup "list airtable node" with limit 10.
2. Add sort option, enter any sort field with ASC
3. execute node

**Expected behavior**
I expect to see sorted result without any errors

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 with docker
 - n8n Version 0.143.0
 - Node.js Version same as in the official docker image
 - Database system: Postgres
 - Operation mode: own

**Comment by janober** [comment]
Thanks for reporting. I can reproduce this issue. Will have a look.
