### ISSUE TITLE
AWS ERROR: Forbidden - perhaps check your credentials?

### ISSUE THREAD

**Issue by gurumark** [n8n-io/n8n#2581]
Hi, 
I get the following when I use AWS SES node:

ERROR: Forbidden - perhaps check your credentials?
`
{
"message": "Request failed with status code 403",
"name": "Error",
"stack": "Error: Request failed with status code 403 at createError (/config/.npm/_npx/a8a7eec953f1f314/node_modules/axios/lib/core/createError.js:16:15) at settle (/config/.npm/_npx/a8a7eec953f1f314/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/config/.npm/_npx/a8a7eec953f1f314/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
} 
`

My credentials are correct. I tripple checked them. I am able to send email using the same credentials via aws-cli:
`
aws ses send-email \
  --from "admin@exx.com" \
  --destination "ToAddresses=user@exx.com" \
  --message "Subject={Data=from ses,Charset=utf8},Body={Text={Data=ses says hi,Charset=utf8},Html={Data=,Charset=utf8}}"
`

Here is my OS details:
`
bash-5.1$ uname -a
Linux fd3978df9c7e 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 GNU/Linux
`
`
 n8n Version: 0.153.0 
`
Thank you.

**Comment by mutdmour** [comment]
Did you double check the region?

**Comment by gurumark** [comment]
I created a policy that does not limit on the region:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "sns:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ses:*",
            "Resource": "*"
        }
    ]
}
`
It should be global in scope. Am I missing something here?

**Comment by gurumark** [comment]
I checked the region and my connection is fine:
![Screenshot](https://user-images.githubusercontent.com/1859151/146979629-201135f6-1e70-41dc-bea1-9f4005ba03e7.png)

**Comment by mutdmour** [comment]
I just did a quick test (version 0.152.0 and 0.153.0).
1. first used a user with administrator access, always got a response from SES
2. removed administrator access, got forbidden error
3. added your policy as an inline policy, got response again
Can you double check that the aws profile you are using in the cli is definitely same as the one you are using with n8n? If they are, that helps eliminate that it's a permissions issue. Also are other AWS services working with the same credential?

**Comment by gurumark** [comment]
I use the same credentials for both aws-cli and n8n. 
Iam user is an API user and does not have any access to the AWS dashboard if it makes any difference. 
I created another wf with only start and aws s3 nodes. Using the same credentials, I was able to get a response it from aws-cli but not from n8n which errored out:
`
"Cannot read property 'main' of undefined"
`

**Comment by mutdmour** [comment]
`cannot read "main of undefined" sounds like a n8n issue. Console access should affect programmatic access. 
Can you try other operations in both s3 and ses? Like template get with a random name or template delete. Can you share a screenshot of SES node parameters returning 404 (sensitive information blurred out) so I could try to reproduce it?

**Comment by gurumark** [comment]
This is the one I get 403:
![Screenshot (1)](https://user-images.githubusercontent.com/1859151/147096756-de32b15f-ea1b-45d1-ab61-acaf05422b90.png)
 
I got the same result when I tried ses other operation. I haven't tried s3 operation. I have feeling that 403 is not the real error but a side effect.

**Comment by mutdmour** [comment]
Ya I think you are right. Probably has to do with how the request is encoded. If you enable debugging
`export N8N_LOG_LEVEL=debug` you should get a log from axios detailing the request

```
2021-12-22T17:00:25.403Z | debug    | Proxying request to axios {"originalConfig":{"headers":{"Host":"email.us-east-2.amazonaws.com","X-Amz-Date":"20211222T170025Z","Authorization":"AWS4-HMAC-SHA256 Credential=*******************/20211222/us-east-2/ses/aws4_request, SignedHeaders=host;x-amz-date, Signature=74dcdf897165d967f4eebc18ae98dd5397feeb5bef6df92d36f1994117136abe","accept":"*/*"},"method":"POST","uri":"https://email.us-east-2.amazonaws.com/?Action=DeleteTemplate&TemplateName=test"},"parsedConfig":{"headers":{"Host":"email.us-east-2.amazonaws.com","X-Amz-Date":"20211222T170025Z","Authorization":"AWS4-HMAC-SHA256 Credential=**********************/20211222/us-east-2/ses/aws4_request, SignedHeaders=host;x-amz-date, Signature=74dcdf897165d967f4eebc18ae98dd5397feeb5bef6df92d36f1994117136abe","accept":"*/*"},"url":"https://email.us-east-2.amazonaws.com/?Action=DeleteTemplate&TemplateName=test","method":"POST"},"file":"NodeExecuteFunctions.js","function":"proxyRequestToAxios"}
```

If you try this, what do you get? Any obvious encoding issues? If you replicate this request in Postman or with curl, do you get the same error?

**Comment by gurumark** [comment]
@mutdmour I am not familiar with debugging schemes of N8N. I don't know how to replicate this request with curl or Postman either. So if you provide step by step instructions, it will be great.

**Comment by mutdmour** [comment]
Hello. Sorry have been on vacation.
To do this:
1. Before you start n8n, run this in your console `export N8N_LOG_LEVEL=debug`
2. Start n8n however you usually start it (npx or docker) in the same environment
3. Now run the node with the same configuration, that should give you something similar to the log below
```
2021-12-22T17:00:25.403Z | debug    | Proxying request to axios {"originalConfig":{"headers":{"Host":"email.us-east-2.amazonaws.com","X-Amz-Date":"20211222T170025Z","Authorization":"AWS4-HMAC-SHA256 Credential=*******************/20211222/us-east-2/ses/aws4_request, SignedHeaders=host;x-amz-date, Signature=74dcdf897165d967f4eebc18ae98dd5397324eeb5bef6df92d36f1994117136abe","accept":"*/*"},"method":"POST","uri":"https://email.us-east-2.amazonaws.com/?Action=DeleteTemplate&TemplateName=test"},"parsedConfig":{"headers":{"Host":"email.us-east-2.amazonaws.com","X-Amz-Date":"20211222T170025Z","Authorization":"AWS4-HMAC-SHA256 Credential=**********************/20211222/us-east-2/ses/aws4_request, SignedHeaders=host;x-amz-date, Signature=74dcdf897165d967f4eebc18ae1234d5397feeb5bef6df92d36f1994117136abe","accept":"*/*"},"url":"https://email.us-east-2.amazonaws.com/?Action=DeleteTemplate&TemplateName=test","method":"POST"},"file":"NodeExecuteFunctions.js","function":"proxyRequestToAxios"}
```
4. Now in PostMan, create a Post request and add the url
<img width="896" alt="Screenshot 2022-01-06 at 12 49 23" src="https://user-images.githubusercontent.com/4711238/148378654-4dc942dd-8e23-4bdd-a547-e19e53a42c54.png">
5. Now under Headers, just copy the `headers` object under `parsedConfig` and paste it into the first empty key. Postman should automatically convert that to formatted rows 
<img width="898" alt="Screenshot 2022-01-06 at 12 51 47" src="https://user-images.githubusercontent.com/4711238/148379064-e7c04d1a-1e50-436f-9b8c-b7804e70b010.png">

**Comment by gurumark** [comment]
@mutdmour I cannot reproduce this issue any more. I was using npx n8n to start the process withing a container. After starting n8n in its own container using the image available, I don't have this issue. Thanks for your help.
