### ISSUE TITLE
Notion node gets stuck in loading state

### ISSUE THREAD

**Issue by brapifra** [n8n-io/n8n#2722]
**Describe the bug**
Whenever I try to use the notion node to get some pages from a database, it just gets stuck loading forever, despite the fact that the pages have been successfully retrieved.

**To Reproduce**
1. Create a new workflow
2. Add `Notion (Beta)` node
3. Configure the notion node to get all the database pages as shown below:
![image](https://user-images.githubusercontent.com/17855450/150939327-fb08ce73-b1f0-440f-94cc-7d8d21c2ffba.png)
4. See error:
![image](https://user-images.githubusercontent.com/17855450/150943549-bcf8bd0d-b516-41de-b8b7-e7b187c8e391.png)
![image](https://user-images.githubusercontent.com/17855450/150943711-a76edeed-b9cd-4cef-9776-e504cb71773f.png)

**Expected behavior**
It should stop showing the loading spinner and continue the workflow execution.

**Environment (please complete the following information):**

 - OS: Ubuntu
 - n8n: 0.159.1
 - Node.js: 14.16.0
 - Database system: SQlite
 - Operation mode: own

**Comment by Joffcom** [comment]
Hey @brapifra,

That is odd I have been using the notion node heavily over the past week or so and have not had this happen yet. Do you get this issue every time you try to use the node?

It may be worth checking out the [Community Forum](https://community.n8n.io) to see if anyone else has the same issue.

**Comment by brapifra** [comment]
Yes @Joffcom 
And now it's even worse with the latest version of n8n (0.162.0).

Whenever I try to save a workflow with that node, I get a 502 error and the server simply stops working and needs to be restarted.
This is what I see in the logs:
```bash
2|n8n  | /home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:32
2|n8n  |             nodeType.description.properties.forEach((property) => {
2|n8n  |                                             ^
2|n8n  | TypeError: Cannot read properties of undefined (reading 'forEach')
2|n8n  |     at /home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:32:45
2|n8n  |     at Array.forEach (<anonymous>)
2|n8n  |     at Object.generateNodesGraph (/home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:15:20)
2|n8n  |     at InternalHooksClass.onWorkflowSaved (/home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/dist/src/InternalHooks.js:53:63)
2|n8n  |     at /home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/dist/src/Server.js:473:76
2|n8n  |     at async /home/user/.volta/tools/image/packages/n8n/lib/node_modules/n8n/dist/src/ResponseHelper.js:89:26
```

**Comment by Joffcom** [comment]
Hey @brapifra,

A 502 error is normally a bad gateway, Do you have a reverse proxy in front of n8n? For the error in the log it looks unrelated to the notion node. Is it only the notion node that you see the issue with?

As a test can you set the N8N_DIAGNOSTICS_ENABLED environment variable to false?

**Comment by brapifra** [comment]
Well, yes.
That's the error that my reverse proxy returns after the server fails. But I have tried it without the reverse proxy and it still fails anyway.

I have tried to set `N8N_DIAGNOSTICS_ENABLED` to false too but no luck. I can save any other workflows without problems, but if I use the notion node, it fails. @Joffcom :confused:

**Comment by Joffcom** [comment]
That is a bit odd, Which reverse proxy are you using? I am not able to reproduce this with Traefik or nginx.

**Comment by brapifra** [comment]
You shouldn't need to use any reverse proxy to reproduce the issue. It also fails even when I don't use it.
This is what  I see in the console log:
```
The connection to http://***.**.***.**:5678/rest/push?sessionId=it4h5n8q3l was interrupted while the page was loading.
```
The connection gets interrupted because of the Telemetry error I mentioned above.

It fails if I try to edit the title:

![demoissue](https://user-images.githubusercontent.com/17855450/152970202-14c92a7c-d5ed-4c46-8e97-b0773a3111fc.gif)

It works if I remove the notion.so node and save:
![demo_working](https://user-images.githubusercontent.com/17855450/152970651-238f9ea5-300d-42c0-b4e2-3e7e003321d9.gif)

**Comment by Joffcom** [comment]
That is possibly the strangest issue I have seen, So without the notion node do you still get the Telemetry error? In theory with the environment variable set to false it shouldn't be trying to send the request.

I have tried a few different instances of n8n now and I just can't reproduce this one, I also can't see any other complaints of the same issue.

That message about the API server being down though I have seen before and it was down to the URL being used for the vue app.

Are you able to share exactly how you are launching n8n including the environment variables (replace any usernames, passwords and domain names)

**Comment by brapifra** [comment]
Yes, that's correct. When I remove the notion node from the workflow, it saves without throwing that Telemetry error on the server.

Here is the `ecosystem.config.js` file I use to run n8n with pm2:
```javascript
module.exports = {
  apps : [
      {
        name: "n8n",
        script: "n8n",
        max_memory_restart: "1G",
        env: {
          "N8N_BASIC_AUTH_ACTIVE": true,
          "N8N_BASIC_AUTH_USER": "hello",
          "N8N_BASIC_AUTH_PASSWORD": "world",
          "WEBHOOK_URL": "https://something.com/",
          "VUE_APP_URL_BASE_API": "https://something.com/",
          "GENERIC_TIMEZONE": "Europe/Madrid",
          "N8N_DIAGNOSTICS_ENABLED": false
        }
      }
  ]
}

```

**Comment by Joffcom** [comment]
When you tried direct did you change the vue app url to use the local IP instead of the fqdn?

I will set up an instance using PM2 this week and see if that does anything different.

So just to confirm as well, even with that config option to disable the telemetry you are still seeing the message about telemetry?

**Comment by brapifra** [comment]
* Yes, I'm still getting the Telemetry error with `"N8N_DIAGNOSTICS_ENABLED": false`
* Yes, I'm still getting the error after changing the vue app url to use the local IP.

**Comment by PSPanesar** [comment]
I have the same issue using the Notion node with either n8n from the command line on Mac or with the Desktop App. The error trace is the same as that shown by the submitter

**Comment by Joffcom** [comment]
Hey @PSPanesar,

What version of n8n were you trying with? I am still not able to reproduce this one.

**Comment by PSPanesar** [comment]
Hi, im on version 0.163.1. 
im running on a Mac and the same issue occurs if on npm or the desktop version.

**Comment by Joffcom** [comment]
Hey @PSPanesar & @brapifra,

Are you both still seeing this issue on the latest release?

**Comment by netroy** [comment]
@Joffcom [I tried fixing this telemetry issue](https://github.com/netroy/n8n/commit/e1144b6c8519d8dbabe66d1360a230b1e74299e8) yesterday.  
if you folks want, I can finish the change, and send a PR.

**Comment by Joffcom** [comment]
I will run it past the core dev team and see what they think. PRs for core components tend to take longer to merge as there is more testing and checking than node PRs need.
