### ISSUE TITLE
Webhook Worker/Processor throwing error when updated to 0.164.0

### ISSUE THREAD

**Issue by Jaime-KD** [n8n-io/n8n#2848]
**Describe the bug**
I have n8n in a scalable set up with seperate worker and webhook processors, updated to 0.164.0 and found that the webhook processors were now throwing an error when called see error log:
`(node:606526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/n8n/.nodejs_global/lib/node_modules/n8n/dist/src/WebhookServer.js:31:34
    at Layer.handle [as handle_request] (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:137:13)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at /home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:281:22
    at param (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:360:14)
    at param (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:416:3)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:275:10)
    at /home/n8n/.nodejs_global/lib/node_modules/n8n/dist/src/WebhookServer.js:142:13
    at Layer.handle [as handle_request] (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:323:13)
    at /home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:341:12)
    at next (/home/n8n/.nodejs_global/lib/node_modules/n8n/node_modules/express/lib/router/index.js:275:10)
(node:606526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
`
I downgraded to 0.163.0 and it works fine again.

**To Reproduce**
1. Set up webhook processor on latest n8n version
2. Call webhook endpoint

**Expected behavior**
Webhooks to handle incoming requests and not throw error

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version 0.164.0
 - Node.js Version v14.19.0
 - Database system Postgres
 - Operation mode queue

**Comment by janober** [comment]
Thanks a lot for reporting. Will have a look.

**Comment by janober** [comment]
The issue got fixed and released with `n8n@0.164.1`.

The docker build will however take around 30-40 min.

Sorry for not catching this before the release!

**Comment by janober** [comment]
Is now available.
