### ISSUE TITLE
Error when running the Notion node

### ISSUE THREAD

**Issue by jlengstorf** [n8n-io/n8n#2872]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `n8n-workflow@0.84.0` for the project I'm working on.

When running the Notion node, I get the following error when I try to load:

```
ERROR RESPONSE
TypeError: Cannot read properties of undefined (reading 'select')
    at Object.getPropertySelectValues (/Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n-nodes-base/dist/nodes/Notion/v2/NotionV2.node.js:92:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n/dist/src/ResponseHelper.js:89:26
/Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:32
            nodeType.description.properties.forEach((property) => {
                                            ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at /Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:32:45
    at Array.forEach (<anonymous>)
    at Object.generateNodesGraph (/Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js:15:20)
    at InternalHooksClass.onWorkflowPostExecute (/Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n/dist/src/InternalHooks.js:97:71)
    at /Users/blitz/github/jlengstorf/n8n-automation/node_modules/n8n/dist/src/WorkflowRunner.js:60:76
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm pretty sure I didn't solve this the Right Way™, but I figured I'd share what fixed it.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js b/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js
index 49ab637..14dde9e 100644
--- a/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js
+++ b/node_modules/n8n-workflow/dist/src/TelemetryHelpers.js
@@ -29,7 +29,7 @@ function generateNodesGraph(workflow, nodeTypes) {
         }
         else {
             const nodeType = nodeTypes.getByName(node.type);
-            nodeType.description.properties.forEach((property) => {
+            nodeType?.description?.properties?.forEach((property) => {
                 if (property.name === 'operation' ||
                     property.name === 'resource' ||
                     property.name === 'mode') {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Joffcom** [comment]
Hey @jlengstorf,

I have not come across Patch Package before but when it updates a package does it update the entire project? Updating just one component could cause issues so it could be worth making sure everything is updating and checking to see if the same issue exists.

**Comment by jlengstorf** [comment]
@Joffcom I manually edited `node_modules`, and `patch-package` allows me to apply my fix to my project whenever I run `npm install` — basically a way to kinda-sorta fork the module without having to fully fork it

I upgraded to `n8n@0.164.1` and I still get the same error. It clears up if I apply the patch.

**Comment by Joffcom** [comment]
Hey @jlengstorf,

I see it now, So it is a console output when you see the error rather than something in the UI. I think this may actaully be fixed in https://github.com/n8n-io/n8n/pull/2750 I have just pulled the latest source and gave it a run and I don't get the same issue anymore.

**Comment by Joffcom** [comment]
Hey @jlengstorf,

Any chance you can test with the latest release and see if you still have the issue?

**Comment by jlengstorf** [comment]
looks like that fixed it! I was able to run the Notion node without my patch in `0.165.1` and got no errors

thanks!

**Comment by S1lander** [comment]
@Joffcom I am having the same problem:
```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /home/silas/.nodejs_global/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Notion/GenericFunctions.ts:993:10
    at Array.forEach (<anonymous>)
    at extractDatabaseMentionRLC (/home/silas/.nodejs_global/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Notion/GenericFunctions.ts:980:14)
    at Object.execute (/home/silas/.nodejs_global/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Notion/v2/NotionV2.node.ts:251:31)
    at Workflow.runNode (/home/silas/.nodejs_global/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1284:31)
    at /home/silas/.nodejs_global/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1018:44
```
