### ISSUE TITLE
Strava Trigger errors on aspect_type Delete

### ISSUE THREAD

**Issue by pholcroft** [n8n-io/n8n#2941]
Once a trigger is received from Strava the node connects to the strava api to retrieve the details about the object specified in the trigger. This logic doesn't work when it is a delete as the object no longer exists.

I believe the issue is at the location below, not only should it check if resolveData is true, but also if the aspect_type != delete
https://github.com/n8n-io/n8n/blob/2e7dcd3c3a21e37c7a9d1f0acec0c85b91c58344/packages/nodes-base/nodes/Strava/StravaTrigger.node.ts#L265

Error:
`Error: Request failed with status code 404
        at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)
        at IncomingMessage.emit (events.js:327:22)
        at IncomingMessage.EventEmitter.emit (domain.js:467:12)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)`

This issue is hard to avoid as Strava only allows one subscription so you are forced to use wildcard * object and events for the trigger. 
Also for some reason Strava triggers the same delete multiple times and create's twice? It's not clear why this happens.

I have attached a snippet of the log below with debug level enabled.
I also setup netcat to capture all the raw triggers from strava to a file over a few minutes after creating and deleting an activity
[strava_n8n.log](https://github.com/n8n-io/n8n/files/8189392/strava_n8n.log)
[strava_webhooks_received.txt](https://github.com/n8n-io/n8n/files/8189393/strava_webhooks_received.txt)
.

**Comment by Joffcom** [comment]
Hey @pholcroft,

We are tracking this one internally as `NODE-175`, Looking at the response it looks like a potential fix would be to just ignore the resolve setting if the `aspect_type` is `delete`.

I will see if I can fit in a fix for this later this week so we can get this one closed.

**Comment by Joffcom** [comment]
Hey @pholcroft,

I have just put in a fix for this here: https://github.com/n8n-io/n8n/pull/6277 once reviewed this will be merged and then available in a future release.

For now I am going to mark this one as closed 👍🏻

**Comment by janober** [comment]
Fix got released with [`n8n@0.230.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.230.1)
