### ISSUE TITLE
Github node throws error when listing all files within a folder

### ISSUE THREAD

**Issue by onegambler** [n8n-io/n8n#2996]
**Describe the bug**
When trying to use the Github node to retrieve the list of files within a folder I am getting an error `ERROR: Could not get parameter "additionalParameters"!` with the stacktrace:

```
Error: Could not get parameter "additionalParameters"!
    at getNodeParameter (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/NodeExecuteFunctions.js:858:15)
    at Object.getNodeParameter (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/NodeExecuteFunctions.js:1078:24)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Github/Github.node.js:1773:59)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:526:37)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:451:62
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1. Go to a workflow
2. Create a github node
3. Have correct crentials
4. In Resource select `File`
5. In Operation select `List`
6. In RepositoryOwner have the correct owner
7. In Repository Name have the correct name - in my case `n8n`
8. In Path have an existing path within the repo - in my case `workflow`

**Expected behavior**
Return a list of all the files contained in the specified path.

**Environment (please complete the following information):**
 - OS:  Ubuntu Linux 18.04, via Docker
 - n8n Version 0.168.1
 - Docker image: n8nio/n8n

**Comment by Joffcom** [comment]
Hey @onegambler,

Thanks for reporting this one, We had another report on our Discord server the other day as well. I am currently working on fixing the credential test issue we have with the Github node at the moment and I am going to fix this at the same time.
