### ISSUE TITLE
AWS Lambda timeout issue

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#3301]
**Describe the bug**
Hello, seems, the lambda node in n8n has a built-in timeout set to 5 min despite the settings of the lambda function in the AWS. I've configured a dummy lambda to invokes for 12 minutes. From AWS console everything is working fine, but from n8n workflow I'm getting the timeout error:
```
{
"message": "timeout of 300000ms exceeded",
"name": "Error",
"stack": "Error: timeout of 300000ms exceeded at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:303:16) at RedirectableRequest.emit (node:events:527:28) at Timeout.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:164:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)",
"code": "ECONNABORTED"
}
```

**To Reproduce**
1. Create a lambda function in AWS (python 3.6+):
```py
import time

def lambda_handler(event, context):
    time.sleep(12*60)
    return {
        'statusCode': 200,
        'body': 'waited for 12 mins'
    }

```
2. Push the deploy button
3. Configure the timeout to the 15 minutes (max for lambda function)
4. Run it via n8n workflow with empty json `{}`
5. See error

**Expected behavior**
After 12 of minutes the worflow will return some data

**Environment (please complete the following information):**
 - OS: docker
 - n8n Version 0.176.0

**Comment by Joffcom** [comment]
Hey @barn4k,

It looks like this isn't specific to the node and it could be where we have a 30000ms timeout for the Axios config, I suspect this value was chosen for performance.

This will likely need a feature request created, Maybe so we can add it as a config option so it can be higher if needed. Out of interest how often do you use a Lambda function that runs for over 5 minutes?

**Comment by barn4k** [comment]
hi @Joffcom 

Once a day. A have a lambda function that invokes other lambda functions asynchronously (from 100 to 250 functions simultaneously) and collects their outputs into one s3 object. So it works with calling 100 functions (execution time - 3-4 mins ), but not works with 250 (execution time - 7-8 mins ). 

Use case: we have about 30k of Azure groups and we need to get all members for each group. MS Graph API can't retrieve group members indirectly, so we need to get ID of the group and then we should call the group members API endpoint. It's not fast, so MS provides us a batch method to send up to 20 sub-requests in one request. So using this function for 30k groups will invokes lambda node for 1500 times ( + 30 calls for getting all group IDs, as one call can retrieve up to 999 group ID). I've checked this behavior, it worked, but spent about 1.5 hours to execute the flow.

![1](https://user-images.githubusercontent.com/15629670/168616815-0b11b405-baf9-4074-b28a-faf0774eb0df.png)

We also have a bunch of functions that can work about 5-10 minutes (mostly functions related to MS Graph that collects users, groups, applications from Azure and is written in python).

And what is with the performance? The lambda node only invokes the desired lambda function and waits for the output, there should not be any performance impact

**Comment by Joffcom** [comment]
Hey @barn4k,

From what I can see it is a global 5 minute timeout so it isn't just for Lambda it is all nodes that use Axios for the transport, While the workflow is running it is consuming resources so if the value was higher and the workflows were scheduled to run every minute or on a webhook it is going to consume a lot more.

I can see this isn't the case with your workflow above but it is a general thing that someone on our end had to think about and make a call on.

If you wanted to build your own version a quick version without exposing it to the config would be to try changing the default timeout we use under `packages/core/src/NodeExecuteFunctions.ts` where it has `axios.defaults.timeout = 300000;` I have asked internally if we have an option to change this through config but I can't see anything in the code.

**Comment by barn4k** [comment]
As a working solution / workaround, can you define an ENV variable to set the axios timeout? So it would not breaks after the upgrading process

**Comment by Joffcom** [comment]
Hey @barn4k,

At the moment it doesn't look to be the case but that is how I would expect it to work and is what I will put on the feature request.

**Comment by arladmin** [comment]
Ran into the same issue, with several other nodes: Discord, Telegram, Airtable.

It seems a bit baffling that the workflow's Timeout setting is not being respected at the node level.
A lot of my workflows have failed in the past few hours, creating a serious unexpected and unresolvable downtime, possibly due to some (unknown) network issues.

Nodes' timeout should naturally be equal to the workflow's timeout, because:
1. A user is not given the option to set Nodes' timeout individually
2. Some nodes might naturally take more time to finish due to large data or any other similar reason
3. There might be intermittent network issues which can be covered to a good extent, if larger timeout settings are used.

**Comment by Joffcom** [comment]
As this is a feature request I am going to mark this one as closed for now, As of now there has been no change to how this works.
