### ISSUE TITLE
Baserow Node Not pulling lists from baserow. 

### ISSUE THREAD

**Issue by draglabs** [n8n-io/n8n#3685]
**Describe the bug**
However over the last few weeks this feature has been failing, it started intermittent and now simply does not work. 
 
**To Reproduce**
1. Create a Baserow account, with a database and a table inside. 
2. Add the Baserow node in N8N 
3. Work in the node to locate your list of databases, tables and fieldnames. 

**Expected behavior**
Normally the Baserow node retrieves a list of databases tables and rows from Baserow making it much easier to utilize Baserow. 

**Environment (please complete the following information):**
 - OS: [Ubuntu With Cloudron]
 - n8n Version [e.g. 0.185.0] 
 - Node.js Version [16.5]
 - Database system [PostGres]
 - Operation mode [default?]

**Additional context**
Over the last few weeks the problem has existed in different forms. 
Sometimes it works if it has input data, rarely it works without input data created by running the previous node. 

When node runs this error is output to the console. 

{"code":0,"message":"The resource you are requesting could not be found","hint":"","context":{},"name":"NodeApiError","cause":{"message":"404 - {\"error\":\"URL_TRAILING_SLASH_MISSING\",\"detail\":\"A valid URL must end with a trailing slash. Please, redirect requests to /api/database/tables/database/71/\"}","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/app/code/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/code/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/code/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"timestamp":1657389939857,"node":{"parameters":{"resource":"row","operation":"create","databaseId":71,"tableId":"","dataToSend":"defineBelow","fieldsUi":{}},"name":"Temp-Node","type":"n8n-nodes-base.baserow","typeVersion":1,"position":[0,0],"credentials":{"baserowApi":{"id":"1","name":"Baserow account"}}},"httpCode":"404","description":"URL_TRAILING_SLASH_MISSING","stack":"NodeApiError: The resource you are requesting could not be found\n    at Object.baserowApiRequest (/app/code/node_modules/n8n-nodes-base/dist/nodes/Baserow/GenericFunctions.js:27:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.getTableIds (/app/code/node_modules/n8n-nodes-base/dist/nodes/Baserow/Baserow.node.js:99:36)\n    at async /app/code/node_modules/n8n/dist/src/ResponseHelper.js:90:26"}

**Comment by draglabs** [comment]
![Screen Shot 2022-07-09 at 1 52 13 PM](https://user-images.githubusercontent.com/17034358/178120915-58cca4e3-85d7-4d8c-aa67-863a5943f3c5.png)

**Comment by draglabs** [comment]
hey @Joffcom I would have made this commit myself but I am not familiar enough with the dev process at n8n if you are available to entertain working on this together over zoom I can make similar pull requests in the future.

**Comment by Joffcom** [comment]
Hey @draglabs,

The process isn't that bad, If you make a fork of n8n then create a new branch and make the changes. Once that is done commit it and open a pull request then we do our internal review process and merge it in.

I have this one down to fix later today.

**Comment by Joffcom** [comment]
Hey @draglabs,

Did some digging and it turns out with release 1.10.2 of Baserow they started to return an error when the / was missing, This wasn't an issue with earlier versions of Baserow. The original issue report can be found here: https://gitlab.com/bramw/baserow/-/issues/405

**Comment by janober** [comment]
Got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.187.1`
