### ISSUE TITLE
Connect to Github OAuth 2 - N8N_HOST is ignored

### ISSUE THREAD

**Issue by jory3** [n8n-io/n8n#3707]
**Describe the bug**
I have n8n running behind a reverse proxy, making it available to the outside world on https port 443. It's running in a docker container, where N8N_HOST is set to https://n8n.mydomain.com. Everything works fine so far, but when I try to add a credential for Github OAuth 2 the OAuth redirect URL is displayed as follows: 

https://n8n.mydomain.com:5678/rest/oauth2-credential/callback [Port 5678 is added]

When I try to remove the port number or add 443 connecting to Github doesn't work, I get the error message "The redirect_uri MUST match the registered callback URL for this application." - full output below. 

My guess is, that somehow N8N_HOST is ignored when the redirect URL is generated. 

```
ERROR RESPONSE
ResponseError: Insufficient parameters for OAuth2 callback. Received following query parameters: {"error":"redirect_uri_mismatch","error_description":"The redirect_uri MUST match the registered callback URL for this application.","error_uri":"https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch","state":"eyJ0b2tlbiI6IkV0dnpFMzR3LThhd0RHVjNKWkpieXRhNURwMFU4NUxzZXBtMCIsImNpZCI6IjIifQ=="}
    at /usr/local/lib/node_modules/n8n/dist/src/Server.js:1178:43
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:280:10)
    at /usr/local/lib/node_modules/n8n/dist/src/UserManagement/routes/index.js:126:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:280:10)
    at /usr/local/lib/node_modules/n8n/dist/src/UserManagement/routes/index.js:96:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:280:10)
    at /usr/local/lib/node_modules/n8n/dist/src/UserManagement/routes/index.js:84:20
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5) {
  httpStatusCode: 503
}
```

**To Reproduce**
Run n8n behind a reverse proxy with N8N_HOST set correctly. Try to add Github OAuth 2. 

**Expected behavior**
When the redirect URL is generated, N8N_HOST should be respected, including port

**Environment**
n8n 0.186.0 in docker
Nginx reverse proxy

**Comment by Joffcom** [comment]
Hey @jory3,

Have you set `WEBHOOK_URL` as well?

The URL tends to be the value of host and port unless webhook url is configured as well.

**Comment by jory3** [comment]
Hi @Joffcom,

thank you, setting `WEBHOOK_URL` to the same value as `N8N_HOST` did the trick, the redirect URL is now correct. 

I'll close the issue, I guess in that case it's expected behaviour and not a bug.
