### ISSUE TITLE
Mautic Node fails adding URL to path

### ISSUE THREAD

**Issue by kromonos** [n8n-io/n8n#3971]
**Describe the bug**
The Mautic fails to add the URL part to the path, what ends up in a 404 error:
```
2022-08-29T21:13:02.472Z | debug    | Credential test failed UNKNOWN ERROR - check the detailed error for more information "{\n  context: { runIndex: 0, itemIndex: 0 },\n  name: 'NodeApiError',\n  cause: NodeApiError: The resource you are requesting could not be found\n      at Object.httpRequestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/NodeExecuteFunctions.js:839:15)\n      at processTicksAndRejections (node:internal/process/task_queues:96:5)\n      at async RoutingNode.rawRoutingRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/RoutingNode.js:200:29)\n      at async RoutingNode.makeRoutingRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/RoutingNode.js:290:28)\n      at async RoutingNode.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/RoutingNode.js:77:32)\n      at async CredentialsHelper.testCredentials (/usr/local/lib/node_modules/n8n/dist/src/CredentialsHelper.js:328:24)\n      at async /usr/local/lib/node_modules/n8n/dist/src/ResponseHelper.js:90:26 {\n    context: { runIndex: 0, itemIndex: 0 },\n    cause: Error: Request failed with status code 404\n        at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n        at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n        at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n        at IncomingMessage.emit (node:events:525:35)\n        at IncomingMessage.emit (node:domain:489:12)\n        at endReadableNT (node:internal/streams/readable:1358:12)\n        at processTicksAndRejections (node:internal/process/task_queues:83:21) {\n      config: [Object],\n      request: [ClientRequest],\n      response: [Object],\n      isAxiosError: true,\n      toJSON: [Function: toJSON]\n    },\n    timestamp: 1661807582471,\n    node: {\n      id: 'temp',\n      parameters: [Object],\n      name: 'Temp-Node',\n      type: 'n8n-nodes-base.noOp',\n      typeVersion: 1,\n      position: [Array],\n      credentials: [Object]\n    },\n    httpCode: '404',\n    description: 'Requested URL not found: /api/users/self'\n  },\n  timestamp: 1661807582471,\n  node: {\n    id: 'temp',\n    parameters: { temp: '' },\n    name: 'Temp-Node',\n    type: 'n8n-nodes-base.noOp',\n    typeVersion: 1,\n    position: [ 0, 0 ],\n    credentials: { mauticApi: [Object] }\n  },\n  httpCode: null,\n  description: 'Request failed with status code 404',\n  file: 'CredentialsHelper.js ,\n  function: 'testCredentials'\n}"
```
![](https://mws.bka.li/sharex/2022/08/firefox_20220829_232711.png)

**To Reproduce**
Create new credentials for Mautic API

**Environment:**

- OS: Debian 11
- n8n Version: 0.192.2
- Node.js Version v16.17.0
- Database system SQLite
- Operation mode own

**Comment by kromonos** [comment]
It has been taken care of. At the end, Mautic and its “interesting” concept of caching was to blame.  
If anyone notes a similar problem:

* Clear Mautic's cache with `bin/console cache:clear`.
* First address the API, e.g., with Postman

After that, everything is usable again normally.
