### ISSUE TITLE
Unable to build custom node with n8n-node-dev

### ISSUE THREAD

**Issue by DmitryZakharov** [n8n-io/n8n#4133]
**Describe the bug**
Following instructions to create a custom node and include it into the ~/.n8n/custom from [https://github.com/n8n-io/n8n/blob/b22ff1f5c17ecfcafd7bb8739b311fd0b88d37e8/packages/node-dev/README.md](readme.md)

I get the following: 

```
**@**:~/projects/n8n$ n8n-node-dev build

Build credentials and nodes
=========================

GOT ERROR: "Unexpected token } in JSON at position 85"
====================================
SyntaxError: Unexpected token } in JSON at position 85
    at JSON.parse (<anonymous>)
    at createCustomTsconfig (**/npm/node_modules/n8n-node-dev/dist/src/Build.js:17:27)
    at async buildFiles (**/npm/node_modules/n8n-node-dev/dist/src/Build.js:41:26)
    at async Build.run (**/npm/node_modules/n8n-node-dev/dist/commands/build.js:20:37)
    at async Build._run (**/npm/node_modules/n8n-node-dev/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (**/npm/node_modules/n8n-node-dev/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (**/npm/node_modules/n8n-node-dev/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (**/npm/node_modules/n8n-node-dev/node_modules/@oclif/command/lib/command.js:43:20)

```
**To Reproduce**
In an empty folder run :

` n8n-node-dev new`
` n8n-node-dev build`

**Expected behavior**
Build is successful 

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 20.04.5 LTS (Win10 WLS2)]
- n8n Version [n8n@0.194.0]
- Node.js Version [16.17.0]
- Database system [SQLite]
- Operation mode [ `own`]

**Comment by Phu96** [comment]
I have got the same problem, does anyone know how to fix this?

**Comment by ivov** [comment]
@DmitryZakharov @Phu96 Thank you for your report. Please roll back to the previous version `npm i -g n8n-node-dev@0.72.1` or preferably use the starter: https://github.com/n8n-io/n8n-nodes-starter/ 

@netroy This very likely comes from [here](https://github.com/n8n-io/n8n/pull/4049/files#diff-0ebca073d2579480233b133b27b02248d6c36b1e79551f5d826f879e30b296bd ). A global install of this package needs a full tsconfig.

**Comment by netroy** [comment]
The `Unexpected token }` is coming from the trailing comma in the `tsconfig-build.json`, that's allowed by `tsc` but not by `JSON.parse`.
I'm investigating we can use the `tsconfig` package instead for parsing the config.

**Comment by netroy** [comment]
Fixed in https://github.com/n8n-io/n8n/pull/4148
