### ISSUE TITLE
Microsoft To Do Get Many Tasks, return all error

### ISSUE THREAD

**Issue by albertopasqualetto** [n8n-io/n8n#4203]
**Describe the bug**
Microsoft To Do node with Task - Get Many - Return All gives back "ERROR: Bad request - please check your parameters"

**To Reproduce**

1. Create a new MS To Do node
2. Select Task, Get Many and activate Return All

**Expected behavior**
No errors

**Environment (please complete the following information):**

- OS: 22.04.1 LTS
- n8n Version: 0.195.5, Docker
- Database system: SQLite
- Operation mode: own

**Additional context**
Error in specific:
Query option '$top' was specified more than once, but it must be specified at most once.
Cause:
```
{"message":"400 - {\"error\":{\"code\":\"BadRequest\",\"message\":\"Query option '$top' was specified more than once, but it must be specified at most once.\",\"innerError\":{\"date\":\"2022-09-26T18:47:01\",\"request-id\":\"removed\",\"client-request-id\":\"removed\"}}}","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
```
Stack:
```
	NodeApiError: Bad request - please check your parameters
    at Object.microsoftApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/ToDo/GenericFunctions.js:26:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.microsoftApiRequestAllItems (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/ToDo/GenericFunctions.js:36:24)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/ToDo/MicrosoftToDo.node.js:177:44)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:619:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:557:53
```

**Comment by Joffcom** [comment]
Hey @albertopasqualetto,

I have just opened a PR that will fix this one, Thanks again for letting us know about this one.
