### ISSUE TITLE
Trying to build a custom node throws: Error: Cannot find module 'n8n-node-dev/src'

### ISSUE THREAD

**Issue by distante** [n8n-io/n8n#4297]
**Describe the bug**
Trying to build a custom node throws Error: Cannot find module 'n8n-node-dev/src'

**To Reproduce**

1. Go to any empty folder
2. Run `n8n-node-dev new`
3. Run `n8n-node-dev build`

**Expected behavior**
The node example build

**Current behavior**
The build process fails
```
npx n8n-node-dev build

Build credentials and nodes
=========================

GOT ERROR: "Cannot find module 'n8n-node-dev/src'
Require stack:
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/Build.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/commands/build.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/plugin.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/config.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/command/lib/command.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/command/lib/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/bin/n8n-node-dev"
====================================
Error: Cannot find module 'n8n-node-dev/src'
Require stack:
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/Build.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/commands/build.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/plugin.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/config.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/config/lib/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/command/lib/command.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/command/lib/index.js
- /Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/bin/n8n-node-dev
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at createCustomTsconfig (/Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/Build.js:14:71)
    at buildFiles (/Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/src/Build.js:32:32)
    at Build.run (/Users/my-user/dev/n8n/n8n-check-email-node/node_modules/n8n-node-dev/dist/commands/build.js:20:64)
    at Build._run (/Users/my-user/dev/n8n/n8n-check-email-node/node_modules/@oclif/command/lib/command.js:43:31)
```

**Environment (please complete the following information):**

- OS: macOS Monterrey 12.6 (21G115)
- n8n Version: 0.196.0
- Node.js Version v16.15.1
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @distante,

Have your tried our starter template instead? You can find it here: https://github.com/n8n-io/n8n-nodes-starter

**Comment by distante** [comment]
Hi, thanks the starter builds correctly. 

Although the npm linking to the global n8n install does not work but I suppose that is another problem...
