### ISSUE TITLE
Registering Errors Out and hangs

### ISSUE THREAD

**Issue by cyberofficial** [n8n-io/n8n#4593]
How can we use the app with out registering?

* when building and running and skipping registering, just doesn't work, just hangs.

Only error in console comes up with this

```js
ERROR RESPONSE
Error: Not logged in
    at I:\Projects\n8n\packages\cli\src\UserManagement\routes\auth.ts:80:19
    at I:\Projects\n8n\packages\cli\src\ResponseHelper.ts:152:23
    at Layer.handle [as handle_request] (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at next (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:346:12)
    at next (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:280:10)
    at refreshExpiringCookie (I:\Projects\n8n\packages\cli\src\UserManagement\middlewares\auth.ts:54:2)
    at Layer.handle [as handle_request] (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:328:13)
    at I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:346:12)
    at next (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:280:10)
    at I:\Projects\n8n\packages\cli\src\UserManagement\routes\index.ts:73:4
    at Layer.handle [as handle_request] (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:328:13)
    at I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:346:12)
    at next (I:\Projects\n8n\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\router\index.js:280:10)
    at I:\Projects\n8n\packages\cli\src\UserManagement\routes\index.ts:52:11 {
  httpStatusCode: 401
}
```

Env Info:
```json
{
  n8n: '0.202.1',
  npm: '8.19.2',
  node: '17.9.0',
  v8: '9.6.180.15-node.16',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.2+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
Windows 11
Database is default which ever it's set to.

**Comment by netroy** [comment]
> How can we use the app with out registering?

@cyberofficial to use n8n without user-management features, please try setting an environment variable `N8N_USER_MANAGEMENT_DISABLED` to `true` as documented [here](https://docs.n8n.io/hosting/user-management/#skipping-or-disabling-user-management)?

**Comment by cyberofficial** [comment]
> > How can we use the app with out registering?
> 
> @cyberofficial to use n8n without user-management features, please try setting an environment variable `N8N_USER_MANAGEMENT_DISABLED` to `true` as documented [here](https://docs.n8n.io/hosting/user-management/#skipping-or-disabling-user-management)?

Didn't see that in the docs. I have tried that and works. Thanks!

It's not being used outside of lan and its behind a strict firewall so I'm not worried about security of login / password for it which.

but still the error is an error when clicking skip register with out the setting
