### ISSUE TITLE
The "streams" argument must be specified

### ISSUE THREAD

**Issue by j-norwood-young** [n8n-io/n8n#4929]
**Describe the bug**
After upgrading to 0.207.1 (not sure from what version, it was two months old) I got the following error on startup:
```
Initializing n8n process
 ›   Error: There was an error: The "streams" argument must be specified
Migrations in progress, please do NOT stop the process.
```

**Environment (please complete the following information):**

- OS: Debian Bionic
- n8n Version 0.207.1
- Node.js Version v16.13.0
- Database system SQLite
- Operation mode own

**Comment by j-norwood-young** [comment]
Correct. To update I ran `npm update -g n8n` as per https://docs.n8n.io/hosting/updating/npm/

**Comment by netroy** [comment]
@j-norwood-young Node.js has [this](https://github.com/nodejs/node/issues/40663) issue between `16.10` and `16.17` that causes this. Can you please upgrade to `16.18` or higher 🙏🏽 ?

**Comment by j-norwood-young** [comment]
@netroy Thanks! That solved it!

```bash
> # n
> # n 16.18
  installing : node-v16.18.1
       mkdir : /usr/local/n/versions/node/16.18.1
       fetch : https://nodejs.org/dist/v16.18.1/node-v16.18.1-linux-x64.tar.xz
   installed : v16.18.1 (with npm 8.19.2)
> # node -v
v16.18.1
> # systemctl restart n8n
> # journalctl -u n8n -f
-- Logs begin at Tue 2022-11-29 22:35:01 CET. --
systemd[1]: Stopping n8n...
n8n[22263]: Stopping n8n...
n8n[22263]: There was an error shutting down n8n. Error: InternalHooks not initialized
n8n[22263]:     at Function.getInstance (/usr/local/lib/node_modules/n8n/src/InternalHooksManager.ts:13:9)
n8n[22263]:     at process.stopProcess (/usr/local/lib/node_modules/n8n/src/commands/start.ts:124:31)
n8n[22263]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
systemd[1]: Stopped n8n.
systemd[1]: Started n8n.
n8n[23137]: Initializing n8n process
n8n[23137]: Last session crashed

n8n[23137]: n8n ready on 0.0.0.0, port 5678
n8n[23137]: Version: 0.207.1
n8n[23137]:  ================================
n8n[23137]:    Start Active Workflows:
n8n[23137]:  ================================
n8n[23137]:    - Subscription Callback (ID: 1)
n8n[23137]:      => Started
n8n[23137]: Editor is now accessible via:
n8n[23137]: https://xxxxxxx:5678/
```
