### ISSUE TITLE
Can't execute ANY Google Sheet Request (READ, UPDATE, INSERT, UPSERT)

### ISSUE THREAD

**Issue by KaylanDigital** [n8n-io/n8n#4942]
Can't run an Google Sheets Node Operations
Gatting the error

**ERROR: UNKNOWN ERROR - check the detailed error for more information**

_HTTP Code
ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY_ 

`NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.apiRequest (/app/code/node_modules/n8n-nodes-base/nodes/Google/Sheet/v2/transport/index.ts:72:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at GoogleSheet.spreadsheetGetSheetNameById (/app/code/node_modules/n8n-nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts:116:20)
    at Object.router (/app/code/node_modules/n8n-nodes-base/nodes/Google/Sheet/v2/actions/router.ts:50:18)
    at Workflow.runNode (/app/code/node_modules/n8n-workflow/src/Workflow.ts:1270:19)
    at /app/code/node_modules/n8n-core/src/WorkflowExecute.ts:939:29`

using "Service Account" credentials.

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.207.1]
- Hosted via CLoudron

**Comment by KaylanDigital** [comment]
I haven't tried with Oath Authentication ('cause what I'm doing I believe needs a Service Account credentials : Moving data from MySQL to Sheets)

Not entirely sure about how Cloudron does it. since their PaaS is more of 'Plug & Play'

**Comment by KaylanDigital** [comment]
Is there a way to downgrade to the previous version on N8N?

**Comment by Joffcom** [comment]
Hey @KaylanDigital,

I am going to close this one and we can work on it from the support forum so that neither of us have to bounce between the 2 :)
