### ISSUE TITLE
Error in Notion Trigger nodes

### ISSUE THREAD

**Issue by mskog** [n8n-io/n8n#5194]
**Describe the bug**
When a Notion Trigger node runs it throws an error:

`Cannot read properties of null (reading 'replace')`

Detailed:
```javascript
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.notionApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Notion/GenericFunctions.js:38:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.poll (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Notion/NotionTrigger.node.js:176:33)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:664:32)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:53
```

**To Reproduce**

1. Add a workflow with a Notion Trigger node
2. Use the Fetch Test Event button or let it run on a schedule.

**Environment:**

- OS: Ubuntu Linux 22.04
- n8n Version 0.211.2
- Node.js Version 16.18.1
- Database system Postgres
- Operation mode main

**Additional context**
This works in 0.210.0. I tried downgrading.
I'm guessing that this was introduced in https://github.com/n8n-io/n8n/commit/6608e69457819a79b728253ff75edb788f0bb548

**Comment by Joffcom** [comment]
Hey @mskog 

Thanks for the report, we created an internal ticket earlier today which we are tracking as `NODE-180`

We will let you know when this is fixed.

**Comment by Joffcom** [comment]
Hey @mskog,

It looks like this was solved a couple of months ago, I am going to mark this as closed for now and if you are still seeing this issue let me know and I will open it again.
