### ISSUE TITLE
Asana Trigger Node Issue

### ISSUE THREAD

**Issue by mtahiue** [n8n-io/n8n#531]
**Describe the bug**

n8n execution shows : 

```ERROR: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at new Hmac (internal/crypto/hash.js:113:9)
    at Object.createHmac (crypto.js:141:10)
    at Object.webhook (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Asana/AsanaTrigger.node.js:143:44)
    at Workflow.runWebhook (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:505:33)
    at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/WebhookHelpers.js:47:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The console of the server show 

`ERROR RESPONSE
Error: Workflow Webhook Error: Workflow could not be started!                                   
    at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/src/WebhookHelpers.js:51:30) 
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)                         
`

**To Reproduce**
1. Add a Asana Trigger Node to a workflow
2. Publish this workflow
3. Do some related stuff on Asana

**Expected behavior**
The workflow should be launched as soon as Asana call the n8n webhook

**Environment (please complete the following information):**
 - OS: debian 10
 - n8n Version  0.62.1 
 - Node.js Version , using docker image

**Comment by janober** [comment]
@RicardoE105 did research the issue and found the issue. Thanks a lot!

Please make sure to rename the Trigger-Node that it does not contain any spaces. Guess the name is currently "Asana Trigger", please change it to "Asana-Trigger", it should then work. Already changed the default name that this does not happen again in the future.

**Comment by janober** [comment]
New n8n@0.65.0 with different default-name and check if node contains space got released.
