### ISSUE TITLE
Intermittent DNS errors are not retried in GMail Trigger node

### ISSUE THREAD

**Issue by mark-monteiro** [n8n-io/n8n#5397]
**Describe the bug**
The GMail trigger node occasionally returns an `getaddrinfo EAI_AGAIN` error, which appears to be a [temporary DNS resolution error that should be retried](https://stackoverflow.com/a/57775849/1988326), but is not. Here is an example in my logs from this occuring. It happens fairly regularly (multiple times per day):

```log
n8n                | 2023-02-07T01:39:39.055Z | error    | There was a problem in 'Gmail Trigger' node in workflow '10': 'getaddrinfo EAI_AGAIN www.googleapis.com' "{\n  node: 'Gmail Trigger',\n  workflowId: '10',\n  error: NodeApiError: UNKNOWN ERROR - check the detailed error for more information\n      at Object.googleApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/GenericFunctions.js:137:15)\n      at runMicrotasks (<anonymous>)\n      at processTicksAndRejections (node:internal/process/task_queues:96:5)\n      at Object.poll (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/GmailTrigger.node.js:213:28)\n      at CronJob.executeTrigger (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:58:38) {\n    context: {},\n    timestamp: 1675733979055,\n    node: {\n      parameters: [Object],\n      id: '798c997b-bf66-44e1-89a1-17660366ffef',\n      name: 'Gmail Trigger',\n      type: 'n8n-nodes-base.gmailTrigger',\n      typeVersion: 1,\n      position: [Array],\n      credentials: [Object]\n    },\n    description: 'getaddrinfo EAI_AGAIN www.googleapis.com',\n    httpCode: null,\n    [cause]: NodeApiError: UNKNOWN ERROR - check the detailed error for more information\n        at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1021:19)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n        at Object.googleApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/GenericFunctions.js:84:26)\n        at Object.poll (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/GmailTrigger.node.js:213:28)\n        at CronJob.executeTrigger (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:58:38) {\n      context: {},\n      timestamp: 1675733979055,\n      node: [Object],\n      httpCode: 'EAI_AGAIN',\n      description: 'getaddrinfo EAI_AGAIN www.googleapis.com',\n      [cause]: [Error]\n    }\n  },\n  file: 'GmailTrigger.node.js',\n  function: 'poll'\n}"
```

Presumably this could happen in any other node making web requests, but I have been noticing it in the Gmail Trigger node specifically.

Additionally, the error information provided to the error trigger node with this error occurs is empty. I would expect the `error` property to be populated with something here:

```json
[
  {
    "trigger": {
      "error": {},
      "mode": "trigger"
    },
    "workflow": {
      "id": "21",
      "name": "Mozilla Addon Release Notifications"
    }
  }
]
```

**To Reproduce**

1. Create a workflow with a GMail trigger node, and a workflow with the error trigger node
2. Occasionally it will fail with the error above. This is intermittent and is likely environment specific
3. View the execution of the error trigger node and see that no error details are provided

**Expected behavior**
The failed DNS request should be retried. If retries fail, then the error information should be provided to the Error Trigger node.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version: 0.214.2
- Node.js Version: Version included with Docker image
- Database system: PostgreSQL
- Operation mode: own

**Additional context**
N/A

**Comment by Joffcom** [comment]
Hey @mark-monteiro 

Does the workflow stop working or does it carry on working on the next schedule?

If it is happening multiple times it sounds like it is still running and working as expected to a point. We should really do a better job with the error though 🤔

**Comment by mark-monteiro** [comment]
I'm not sure about that. My error handling workflow automatically restarts the workflow when a trigger error occurs (had to set that up to deal with #3607). I'll disable the error handling for this workflow though and see what happens. Like I said, it's a bit intermittent, but I can get back to you once it occurs again.

**Comment by Joffcom** [comment]
That is the fun thing with DNS the errors often are intermittent which makes it tricky to catch them, I would expect the workflow to eventually try again unless we are disabling it.

Is the node set to always output data or continue on error?

**Comment by mark-monteiro** [comment]
No, 'always output data' and 'continue on error' are both left at their default values of `false`

**Comment by mark-monteiro** [comment]
Okay yes, the workflow doesn't get disabled and continues to retry later on, which makes this less of an issue.

This does still end up spamming my error handling workflow a bit though (which sends me notifications). And the lack of an error message makes it impossible to filter out these DNS errors from other ones

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

That is good to hear, So it sounds like having the error passed would be the solution here.

**Comment by mark-monteiro** [comment]
@Joffcom Yes, having access to the error details in the error workflow would be good enough for me

**Comment by Joffcom** [comment]
Moving this issue to closed as it isn't a bug with n8n as such and is environmental and around error handling, I do plan to spend some time working on on our errors this year so the notitication should improve as part of that.
