### ISSUE TITLE
Migrations Stuck in 0.217.0

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5566]
When updating the container with 0.217.0, the container stops when running migrations.

It doesn't generate an error, it just gets stuck at that point.

NOTE: It happens using `n8n start`, `n8n webhook` or `n8n worker`.

```
UserSettings were generated and saved to: /home/node/.n8n/config
Migrations in progress, please do NOT stop the process.
```

I waited over 10 minutes.

When I ran the process again, the same thing happened on different installations (using MySQL).

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system : MySQL
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by luizeof** [comment]
@Joffcom could you check please?

**Comment by Joffcom** [comment]
Hey @luizeof,

No need to tag we get notifications, Looking at the migration for 217 it updates records in the execution_entity which could take time. How many records do you have in the database?

**Comment by luizeof** [comment]
< 2k rows ... an AWS RDS Database.

I'm going to run it again and wait more to see if it reaches the end.

**Comment by luizeof** [comment]
now the container dies and doesn't run anymore. :(

**Comment by Joffcom** [comment]
Hey @luizeof,

Did the container log any errors?

**Comment by netroy** [comment]
@luizeof what version are you upgrading from?

**Comment by luizeof** [comment]
@netroy 

I tested with 0.217.0, 0.217.1 and 0.217.2 and the same problem happens.

It doesn't generate any error, but the container starts for 5 seconds and ends with "exit 1".

I'm running in queue mode.

I'm running on a mysql 5.7 database on AWS RDS. My table `execution_entity` has 818 records at this point (I use the prune option on it keeping it 12 hours).

It was in version 0.216.2 (if I downgrade to 0.216.2 it runs normally).

This is my migrations table:

![Captura de Tela 2023-02-28 às 08 05 15](https://user-images.githubusercontent.com/257004/221836317-fcfb2bf2-4bbb-4531-8b88-cbc2576a73ee.png)

**Comment by netroy** [comment]
@luizeof I've created a custom docker image with the tag `log-db-error`, to log the error that's crashing n8n.
[It's](https://github.com/n8n-io/n8n/compare/n8n%400.217.2...log-db-error?expand=1) just a `console.log` on top of `0.217.2`. Can you please try this image?

Also, can you please set these env variables to get more debug information?
- `N8N_LOG_LEVEL=debug`
- `DB_LOGGING_ENABLED=true`
- `DB_LOGGING_OPTIONS=all`

Thanks 🙏🏽

**Comment by luizeof** [comment]
@netroy 

```
/bin/busybox:1
ELF
^
SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by netroy** [comment]
@luizeof if you have a custom `command` defined, can you please remove that so that the container uses the default command from the image?

**Comment by luizeof** [comment]
@netroy 

I got!

Should I manually remove or wait for some treatment in the migrations?

```
UserSettings were generated and saved to: /home/node/.n8n/config
2023-02-28T17:39:14.249Z | debug    | Lazy Loading credentials and nodes from n8n-nodes-base "{\n  credentials: 311,\n  nodes: 394,\n  file: 'DirectoryLoader.js',\n  function: 'loadAll'\n}"
query: SELECT VERSION() AS `version`
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'sync_promovaweb_com' AND `TABLE_NAME` = 'migrations'
query: SELECT * FROM `sync_promovaweb_com`.`migrations` `migrations` ORDER BY `id` DESC
33 migrations are already loaded in the database.
36 migrations were found in the source code.
PurgeInvalidWorkflowConnections1675940580449 is the last executed migration. It was executed on Thu Feb 09 2023 11:03:00 GMT+0000 (Coordinated Universal Time).
3 migrations are new migrations must be executed.
query: START TRANSACTION
2023-02-28T17:39:14.974Z | warn     | Migrations in progress, please do NOT stop the process. "{ file: 'migrationHelpers.js', function: 'logMigrationStart' }"
2023-02-28T17:39:14.974Z | debug    | Starting migration AddStatusToExecutions1674138566000 "{ file: 'migrationHelpers.js', function: 'logMigrationStart' }"
query: ALTER TABLE `execution_entity`	ADD COLUMN `status` VARCHAR(255)
query failed: ALTER TABLE `execution_entity`	ADD COLUMN `status` VARCHAR(255)
error: Error: Duplicate column name 'status'
query: ROLLBACK
QueryFailedError: Duplicate column name 'status'
    at Query.onResult (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/typeorm@0.3.12_pgelcv6ef3switkrteavpif3pq/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:37)
    at Query.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  query: 'ALTER TABLE `execution_entity`\tADD COLUMN `status` VARCHAR(255)',
  parameters: undefined,
  driverError: Error: Duplicate column name 'status'
      at Packet.asError (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    code: 'ER_DUP_FIELDNAME',
    errno: 1060,
    sqlState: '42S21',
    sqlMessage: "Duplicate column name 'status'",
    sql: 'ALTER TABLE `execution_entity`\tADD COLUMN `status` VARCHAR(255)'
  },
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlState: '42S21',
  sqlMessage: "Duplicate column name 'status'",
  sql: 'ALTER TABLE `execution_entity`\tADD COLUMN `status` VARCHAR(255)'
}
```

**Comment by luizeof** [comment]
manually remove the status field and truncate the table and the migration ran successfully. thanks for your time ;)
