### ISSUE TITLE
AWS Lambda Unknown Error

### ISSUE THREAD

**Issue by ScaleIan** [n8n-io/n8n#5594]
**Describe the bug**
AWS Lambda node is failing with `ERROR: UNKNOWN ERROR - check the detailed error for more information`, logs seem to indicate a Typescript error.

**To Reproduce**

1. Create a workflow, add a webhook trigger
2. Add an AWS Lambda node with appropriately permissioned credentials, forward the body of the webhook trigger to the lambda node.
3. Test the workflow with a valid JSON body

**Expected behavior**

Lambda should be invoked

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.217.2
- Node.js Version: Whatever comes with the docker image
- Database system: SQLite
- Operation mode: own I think?

**Additional context**
AWS IAM permissioning is as follows:
- Lambda has resource-based invoke permissions to allow the user associated with n8n credentials to invoke
- User associated with n8n credentials has lambda:InvokeFunction, lambda:GetFunction for the specific function.
- User associated with n8n credentials has lambda:ListFunctions:*

Logs
```
2023-03-02T00:01:15.068Z | verbose  | Workflow execution started "{\n  workflowId: '3',\n  file: 'WorkflowExecute.js',\n  function: 'processRunExecutionData'\n}"
TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.byteLength (node:buffer:740:11)
    at RequestSigner.prepareRequest (/usr/local/lib/node_modules/n8n/node_modules/aws4/aws4.js:152:44)
    at RequestSigner.sign (/usr/local/lib/node_modules/n8n/node_modules/aws4/aws4.js:172:30)
    at aws4.sign (/usr/local/lib/node_modules/n8n/node_modules/aws4/aws4.js:380:50)
    at Aws.authenticate (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/credentials/Aws.credentials.js:341:29)
    at CredentialsHelper.authenticate (/usr/local/lib/node_modules/n8n/dist/CredentialsHelper.js:79:39)
    at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1005:65)
    at Object.awsApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/GenericFunctions.js:20:16)
    at Object.awsApiRequestREST (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/GenericFunctions.js:28:22)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsLambda.node.js:156:38)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:590:53 {
  code: 'ERR_INVALID_ARG_TYPE'
}
2023-03-02T00:01:15.186Z | verbose  | Workflow execution finished with error "{\n  error: {\n    context: {},\n    name: 'NodeApiError',\n    timestamp: 1677715275183,\n    node: {\n      parameters: [Object],\n      id: 'd60f3457-9302-47b3-bf77-0c27f3814d12',\n      name: 'AWS Lambda',\n      type: 'n8n-nodes-base.awsLambda',\n      typeVersion: 1,\n      position: [Array],\n      credentials: [Object]\n    },\n    httpCode: null,\n    message: 'UNKNOWN ERROR - check the detailed error for more information',\n    stack: 'NodeApiError: UNKNOWN ERROR - check the detailed error for more information\\n' +\n      '    at Object.awsApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/GenericFunctions.js:23:15)\\n' +\n      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n      '    at Object.awsApiRequestREST (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/GenericFunctions.js:28:22)\\n' +\n      '    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsLambda.node.js:156:38)\\n' +\n      '    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)\\n' +\n      '    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:590:53'\n  },\n  workflowId: '3',\n  file: 'WorkflowExecute.js',\n  function: 'processSuccessExecution'\n}"
```

**Comment by Joffcom** [comment]
Hey @ScaleIan,

I have just given this a test and I have not been able to reproduce it, Can you share a screenshot of what the nodes settings look like for you?

**Comment by ScaleIan** [comment]
<img width="281" alt="Screen Shot 2023-03-02 at 9 11 35 AM" src="https://user-images.githubusercontent.com/111899173/222502357-0193cd92-2cab-4601-932c-c6b224835965.png">

Hey @Joffcom , thanks for the quick response. Above is a screenshot of my lambda node settings. I've validated the JSON I'm receiving and forwarding is correct as well. Please let me know if there are any other troubleshooting steps or info I can provide.

**Comment by Joffcom** [comment]
Hey @ScaleIan 

Can you try changing it from an object to a string that should sort it based on that error message.

**Comment by ScaleIan** [comment]
Hi Jon, going from `{{json.body}}` to `"{{json.body}}" I was able to trigger the lambda , thank you.

This does seem like a strange design choice - I assumed nodes would encode their outputs to external APIs as strings regardless.

I'm running into some errors on the lambda side so I'm going to work that for a bit to make sure I'm receiving the appropriate info and I'll update the thread once I'm certain everything is working.

**Comment by ScaleIan** [comment]
The better solution was to use `{{ JSON.stringify($json.body) }}`

**Comment by ScaleIan** [comment]
Everything's working now with `{{ JSON.stringify($json.body) }}`, thanks for the help! We are experimenting using n8n in some of our workflows and I look forward to seeing what I can do with going forward.
