### ISSUE TITLE
Throwing `LoggerProxy not initialized` when used in custom nodes

### ISSUE THREAD

**Issue by Yann-J** [n8n-io/n8n#5662]
**Describe the bug**

I've developed a custom node, which worked well locally and on my server. However, when moving my logs from `console.log` to `LoggerProxy`, all calls to my node fail, throwing the error `LoggerProxy not initialized`.

Here's the stack:

```
Error: LoggerProxy not initialized
    at getInstance (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/node_modules/n8n-workflow/src/LoggerProxy.ts:12:9)
    at Object.debug (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/node_modules/n8n-workflow/src/LoggerProxy.ts:25:2)
    at Object.cloudConvertApiRequest (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/nodes/CloudConvert/GenericFunctions.ts:37:9)
    at Object.execute (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/nodes/CloudConvert/CloudConvert.node.ts:495:21)
    at Workflow.runNode (/Users/yannjouanique/.nvm/versions/node/v18.15.0/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1270:19)
    at /Users/yannjouanique/.nvm/versions/node/v18.15.0/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:949:29
```

**To Reproduce**

1. Build a custom node with some logging such as:

```
import {
  ...
  LoggerProxy as Logger,
} from 'n8n-workflow';

...
Logger.debug(`Custom node invoked`);
...
```

2. Install the custom node with `npm link`
3. Run n8n and start a workflow with the custom node

**Expected behavior**

No error thrown

**Environment (please complete the following information):**

- OS: Mac M1
- n8n Version 0.219.0
- Node.js Version v18.15.0
- Database system SQLite
- Operation mode `own`

**Additional context**

This is not #5318 because I'm using n8n 0.219.0 which has the fix.

**Comment by Joffcom** [comment]
Hey @Yann-J,

Thanks for reporting this one, I will give it a test tomorrow. I was sure we had fixed this as you had noticed but maybe it has come back. I take it you get the same issue on node 16 as well which is the one we officially support?

**Comment by Yann-J** [comment]
Yes, same thing with node 16:

```
$ node --version
v16.19.1
$ N8N_LOG_LEVEL=debug n8n
2023-03-17T11:55:31.354Z | debug    | Lazy Loading credentials and nodes from n8n-nodes-base "{\n  credentials: 311,\n  nodes: 395,\n  file: 'DirectoryLoader.js',\n  function: 'loadAll'\n}"
2023-03-17T11:55:31.357Z | debug    | Can't enable lazy-loading "{ file: 'DirectoryLoader.js', function: 'loadAll' }"
2023-03-17T11:55:31.404Z | debug    | No codex available for: CloudConvert.node.js "{ file: 'DirectoryLoader.js', function: 'addCodex' }"
2023-03-17T11:55:31.406Z | debug    | No codex available for: CloudConvertTrigger.node.js "{ file: 'DirectoryLoader.js', function: 'addCodex' }"
2023-03-17T11:55:31.406Z | debug    | Loaded all credentials and nodes from n8n-nodes-cloudconvert "{\n  credentials: 1,\n  nodes: 2,\n  file: 'DirectoryLoader.js',\n  function: 'loadAll'\n}"
2023-03-17T11:55:31.945Z | info     | Initializing n8n process "{ file: 'start.js', function: 'init' }"
2023-03-17T11:55:31.947Z | debug    | [license] initializing for deviceFingerprint 58d7250c2188a9d97e07e142579ba7fb94bf93d96675773e5edd1e70f32b8c9d "{ file: 'LicenseManager.js', function: 'log' }"
2023-03-17T11:55:32.470Z | debug    | Wait tracker querying database for waiting executions "{ file: 'WaitTracker.js', function: 'getWaitingExecutions' }"
2023-03-17T11:55:33.149Z | debug    | Initializing event bus... "{ file: 'MessageEventBus.js', function: 'initialize' }"
2023-03-17T11:55:33.150Z | debug    | Initializing event writer "{ file: 'MessageEventBus.js', function: 'initialize' }"
2023-03-17T11:55:33.152Z | debug    | Checking for unsent event messages "{ file: 'MessageEventBus.js', function: 'initialize' }"
2023-03-17T11:55:33.182Z | debug    | Start logging into /Users/yannjouanique/.n8n/n8nEventLog.log  "{ file: 'MessageEventBus.js', function: 'initialize' }"
2023-03-17T11:55:33.182Z | debug    | MessageEventBus initialized "{ file: 'MessageEventBus.js', function: 'initialize' }"
n8n ready on 0.0.0.0, port 5678
Version: 0.220.0
2023-03-17T11:55:33.187Z [Rudder] debug: in flush
2023-03-17T11:55:33.188Z [Rudder] debug: batch size is 1
2023-03-17T11:55:33.189Z [Rudder] debug: no existing flush timer, creating new one

Editor is now accessible via:
http://localhost:5678/

Press "o" to open in Browser.
2023-03-17T11:55:42.939Z | debug    | Add editor-UI session "{ sessionId: '32uye069j7d', file: 'abstract.push.js', function: 'add' }"
2023-03-17T11:55:52.349Z | debug    | Received child process message of type start for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.372Z | verbose  | Initializing n8n sub-process "{\n  pid: 93640,\n  workflowId: '6',\n  file: 'WorkflowRunnerProcess.js',\n  function: 'runWorkflow'\n}"
2023-03-17T11:55:52.447Z | debug    | Lazy Loading credentials and nodes from n8n-nodes-base "{\n  credentials: 311,\n  nodes: 395,\n  file: 'DirectoryLoader.js',\n  function: 'loadAll'\n}"
2023-03-17T11:55:52.448Z | debug    | Can't enable lazy-loading "{ file: 'DirectoryLoader.js', function: 'loadAll' }"
2023-03-17T11:55:52.482Z | debug    | No codex available for: CloudConvert.node.js "{ file: 'DirectoryLoader.js', function: 'addCodex' }"
2023-03-17T11:55:52.483Z | debug    | No codex available for: CloudConvertTrigger.node.js "{ file: 'DirectoryLoader.js', function: 'addCodex' }"
2023-03-17T11:55:52.483Z | debug    | Loaded all credentials and nodes from n8n-nodes-cloudconvert "{\n  credentials: 1,\n  nodes: 2,\n  file: 'DirectoryLoader.js',\n  function: 'loadAll'\n}"
2023-03-17T11:55:52.645Z | debug    | [license] initializing for deviceFingerprint 58d7250c2188a9d97e07e142579ba7fb94bf93d96675773e5edd1e70f32b8c9d "{ file: 'LicenseManager.js', function: 'log' }"
2023-03-17T11:55:52.655Z | verbose  | Workflow execution started "{\n  workflowId: '6',\n  file: 'WorkflowExecute.js',\n  function: 'processRunExecutionData'\n}"
2023-03-17T11:55:52.656Z | debug    | Start processing node "On clicking 'execute'" "{\n  node: \"On clicking 'execute'\",\n  workflowId: '6',\n  file: 'WorkflowExecute.js'\n}"
2023-03-17T11:55:52.656Z | debug    | Running node "On clicking 'execute'" started "{\n  node: \"On clicking 'execute'\",\n  workflowId: '6',\n  file: 'WorkflowExecute.js'\n}"
2023-03-17T11:55:52.657Z | debug    | Running node "On clicking 'execute'" finished successfully "{\n  node: \"On clicking 'execute'\",\n  workflowId: '6',\n  file: 'WorkflowExecute.js'\n}"
2023-03-17T11:55:52.658Z | debug    | Start processing node "CloudConvert" "{ node: 'CloudConvert', workflowId: '6', file: 'WorkflowExecute.js' }"
2023-03-17T11:55:52.658Z | debug    | Running node "CloudConvert" started "{ node: 'CloudConvert', workflowId: '6', file: 'WorkflowExecute.js' }"
2023-03-17T11:55:52.658Z | debug    | Received child process message of type processHook for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.659Z | debug    | Executing hook (hookFunctionsPush) "{\n  executionId: '285',\n  sessionId: '32uye069j7d',\n  workflowId: '6',\n  file: 'WorkflowExecuteAdditionalData.js',\n  function: 'workflowExecuteBefore'\n}"
2023-03-17T11:55:52.660Z | debug    | Send data of type "executionStarted" to editor-UI "{\n  dataType: 'executionStarted',\n  sessionId: '32uye069j7d',\n  file: 'abstract.push.js',\n  function: 'send'\n}"
2023-03-17T11:55:52.663Z | debug    | Received child process message of type processHook for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.664Z | debug    | Executing hook on node "On clicking 'execute'" (hookFunctionsPush) "{\n  executionId: '285',\n  sessionId: '32uye069j7d',\n  workflowId: '6',\n  file: 'WorkflowExecuteAdditionalData.js',\n  function: 'nodeExecuteBefore'\n}"
2023-03-17T11:55:52.664Z | debug    | Send data of type "nodeExecuteBefore" to editor-UI "{\n  dataType: 'nodeExecuteBefore',\n  sessionId: '32uye069j7d',\n  file: 'abstract.push.js',\n  function: 'send'\n}"
2023-03-17T11:55:52.664Z | debug    | Received child process message of type processHook for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.665Z | debug    | Executing hook on node "On clicking 'execute'" (hookFunctionsPush) "{\n  executionId: '285',\n  sessionId: '32uye069j7d',\n  workflowId: '6',\n  file: 'WorkflowExecuteAdditionalData.js',\n  function: 'nodeExecuteAfter'\n}"
2023-03-17T11:55:52.665Z | debug    | Send data of type "nodeExecuteAfter" to editor-UI "{\n  dataType: 'nodeExecuteAfter',\n  sessionId: '32uye069j7d',\n  file: 'abstract.push.js',\n  function: 'send'\n}"
2023-03-17T11:55:52.665Z | debug    | Received child process message of type processHook for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.665Z | debug    | Executing hook on node "CloudConvert" (hookFunctionsPush) "{\n  executionId: '285',\n  sessionId: '32uye069j7d',\n  workflowId: '6',\n  file: 'WorkflowExecuteAdditionalData.js',\n  function: 'nodeExecuteBefore'\n}"
2023-03-17T11:55:52.675Z | debug    | Send data of type "nodeExecuteBefore" to editor-UI "{\n  dataType: 'nodeExecuteBefore',\n  sessionId: '32uye069j7d',\n  file: 'abstract.push.js',\n  function: 'send'\n}"
2023-03-17T11:55:52.691Z | debug    | Running node "CloudConvert" finished with error "{ node: 'CloudConvert', workflowId: '6', file: 'WorkflowExecute.js' }"
2023-03-17T11:55:52.692Z | debug    | Received child process message of type processHook for execution ID 285. "{ executionId: '285', file: 'WorkflowRunner.js' }"
2023-03-17T11:55:52.692Z | debug    | Executing hook on node "CloudConvert" (hookFunctionsPush) "{\n  executionId: '285',\n  sessionId: '32uye069j7d',\n  workflowId: '6',\n  file: 'WorkflowExecuteAdditionalData.js',\n  function: 'nodeExecuteAfter'\n}"
2023-03-17T11:55:52.692Z | debug    | Send data of type "nodeExecuteAfter" to editor-UI "{\n  dataType: 'nodeExecuteAfter',\n  sessionId: '32uye069j7d',\n  file: 'abstract.push.js',\n  function: 'send'\n}"
2023-03-17T11:55:52.692Z | verbose  | Workflow execution finished with error "{\n  error: {\n    message: 'LoggerProxy not initialized',\n    stack: 'Error: LoggerProxy not initialized\\n' +\n      '    at getInstance (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/node_modules/n8n-workflow/src/LoggerProxy.ts:12:9)\\n' +\n      '    at Object.debug (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/node_modules/n8n-workflow/src/LoggerProxy.ts:25:2)\\n' +\n      '    at Object.cloudConvertApiRequest (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/nodes/CloudConvert/GenericFunctions.ts:37:9)\\n' +\n      '    at Object.execute (/Users/yannjouanique/Dev/n8n-nodes-cloudconvert/nodes/CloudConvert/CloudConvert.node.ts:494:21)\\n' +\n      '    at Workflow.runNode (/Users/yannjouanique/.nvm/versions/node/v16.19.1/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1270:19)\\n' +\n      '    at /Users/yannjouanique/.nvm/versions/node/v16.19.1/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:949:29'\n  },\n  workflowId: '6',\n  file: 'WorkflowExecute.js',\n  function: 'processSuccessExecution'\n}"
```

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
