### ISSUE TITLE
HTTP body parameters using UI messes up formatting

### ISSUE THREAD

**Issue by Chaoscontrol** [n8n-io/n8n#5700]
**Describe the bug**
I'm quite a newbie here, but I honestly believe there's a bug here. When making a HTTP request to Toggl's new v9 API, I need to send a body parameter in order to paginate. 

If I send this using the UI, I get a response with an error with the key is recognised as a string. 
If instead I paste the json using the same key, the request works fine. 

I'm pasting both nodes below. I already noticed the one where I'm using the UI has some weird formatting resembling regex, which I am guessing is what's causing the issue. 

**To Reproduce**

`{
  "meta": {
    "instanceId": "078d7dadbc95842b972e58c4ddc55c3b655b3113d8e0c625a849da38b995ef2b"
  },
  "nodes": [
    {
      "parameters": {
        "method": "POST",
        "url": "https://api.track.toggl.com/reports/api/v3/workspace/5670114/search/time_entries",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpBasicAuth",
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n\t\"start_date\": \"2021-01-01\",\n\t\"end_date\": \"2021-12-31\",\n    \"first_row_number\": 51\n}",
        "options": {
          "response": {
            "response": {}
          }
        }
      },
      "id": "228610bf-a7e1-4800-9fd3-858d6d509e19",
      "name": "HTTP Request2",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        2180,
        80
      ],
      "credentials": {
        "httpBasicAuth": {
          "id": "1",
          "name": "Toggl API"
        }
      }
    },
    {
      "parameters": {
        "method": "POST",
        "url": "https://api.track.toggl.com/reports/api/v3/workspace/5670114/search/time_entries",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpBasicAuth",
        "sendBody": true,
        "bodyParameters": {
          "parameters": [
            {
              "name": "start_date",
              "value": "2021-01-01"
            },
            {
              "name": "end_date",
              "value": "2021-12-31"
            },
            {
              "name": "first_row_number",
              "value": "51"
            }
          ]
        },
        "options": {
          "response": {
            "response": {}
          }
        }
      },
      "id": "aa035034-eaef-48fa-bbbf-c86101b9f1d7",
      "name": "HTTP Request1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        2180,
        260
      ],
      "credentials": {
        "httpBasicAuth": {
          "id": "1",
          "name": "Toggl API"
        }
      }
    }
  ],
  "connections": {}
}`

1. Create these 2 nodes (you'll need some credentials for Toggl API). They are identical except for how the body parameters are passed. UI vs JSON.
2. Run both. Using JSON returns a succesful response. Using n8n UI returns an error about the the body parameter "first_row_number".

This is the error returned:
`{"status":"rejected","reason":{"message":"400 - \"\\\"Unexpected \\\\\\\"first_row_number\\\\\\\" type string, offset=74\\\"\"","name":"Error","stack":"Error: 400 - \"\\\"Unexpected \\\\\\\"first_row_number\\\\\\\" type string, offset=74\\\"\"\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}`

**Expected behavior**
Passing the keys using the UI should have the same behaviour as passing them using JSON. 

**Environment (please complete the following information):**

- OS: Home Assistant OS
- n8n Version 0.218.0
- Node.js Version [e.g. 16.17.0]
- Database system MariaDB
- Operation mode own

**Additional context**

**Comment by Joffcom** [comment]
Hey @Chaoscontrol,

Looking at this the issue is where Toggl is not expecting a string for the first_row_number and we treat any value sent as a string in the body. To get around this it would be a case of using the raw option like you are doing or trying a set node first to set the correct data type, You could also change it to an expression.

Currently this is expected behaviour but perhaps as a possible feature request could be to allow setting the datatype for the values.

**Comment by Chaoscontrol** [comment]
I understand. I agree with the possible feature requests. In the meantime, to avoid frustration it could be a good idea to add a small note saying "Using this option will always send parameters as strings, which might not work with some APIs."

**Comment by Joffcom** [comment]
Hey @Chaoscontrol,

That is not a bad idea, I have put the feature request in so it can be prioritised. I guess with the note it is tricky as it isn't always a string only if you are typing it in, I think a documentation update could be a good solution to explain what happens.

**Comment by Chaoscontrol** [comment]
Also as an additional note, just checked and (only) switching to an expression doesn't make a difference. It is still sent as a string and returns the error.

**Comment by Joffcom** [comment]
I spotted that and just raised it as something to sort out. Switching to an expression would also involve using an expression the workflow below using both the set and a more manual expression way to correctly send the data.

```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {
        "method": "POST",
        "url": "https://webhook.site/b124e315-4bd1-442b-8492-f7c4abf7d763",
        "sendBody": true,
        "bodyParameters": {
          "parameters": [
            {
              "name": "my-bool",
              "value": "={{ $json[\"my-bool\"] }}"
            },
            {
              "name": "my-string",
              "value": "={{ $json[\"my-string\"] }}"
            },
            {
              "name": "my-number",
              "value": "={{ $json[\"my-number\"] }}"
            }
          ]
        },
        "options": {
          "response": {
            "response": {}
          }
        }
      },
      "id": "746c88e4-76ef-4546-9118-bbc3d97c2579",
      "name": "HTTP Request1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        1120,
        560
      ]
    },
    {
      "parameters": {},
      "id": "a4326d04-96b0-4827-b5f8-a01c59b262ce",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        700,
        560
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "boolean": [
            {
              "name": "my-bool"
            }
          ],
          "string": [
            {
              "name": "my-string",
              "value": "abc"
            }
          ],
          "number": [
            {
              "name": "my-number",
              "value": 123
            }
          ]
        },
        "options": {}
      },
      "id": "36dcac28-2d08-4c7e-8283-52f299240ba5",
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        920,
        560
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "https://webhook.site/b124e315-4bd1-442b-8492-f7c4abf7d763",
        "sendBody": true,
        "bodyParameters": {
          "parameters": [
            {
              "name": "exp-bool",
              "value": "={{ true }}"
            },
            {
              "name": "exp-string",
              "value": "=still a string"
            },
            {
              "name": "exp-number",
              "value": "={{ 10 }}"
            }
          ]
        },
        "options": {
          "response": {
            "response": {}
          }
        }
      },
      "id": "071ad6a9-ec8b-4a41-8b8f-92834d252ca7",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        920,
        340
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          },
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "HTTP Request1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by Joffcom** [comment]
Hey @Chaoscontrol,

Looks like I forgot to close this one, We still have the requests in the backlog to tackle at some point but we have now fixed that `Asasas` value :)

I will pop a note on here when we do add the extra options for the json content.
