### ISSUE TITLE
Type Error when using AWS Lambda node JSON input

### ISSUE THREAD

**Issue by HazemSayad** [n8n-io/n8n#5722]
**Describe the bug**
Setting up the node correctly with the exception of the JSON input being fed a JSON object as expected, fails with the below error printed in the terminal:
```
TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.byteLength (node:buffer:740:11)
    at RequestSigner.prepareRequest (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/aws4/aws4.js:152:44)
    at RequestSigner.sign (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/aws4/aws4.js:172:30)
    at aws4.sign (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/aws4/aws4.js:380:50)
    at Aws.authenticate (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-nodes-base/credentials/Aws.credentials.ts:356:8)
    at CredentialsHelper.authenticate (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/src/CredentialsHelper.ts:114:27)
    at Object.requestWithAuthentication (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-core/src/NodeExecuteFunctions.ts:1563:59)
    at Object.awsApiRequest (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Aws/GenericFunctions.ts:35:10)
    at Object.awsApiRequestREST (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Aws/GenericFunctions.ts:49:19)
    at Object.execute (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Aws/AwsLambda.node.ts:177:26)
    at Workflow.runNode (/home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1270:19)
    at /home/USER/.nvm/versions/node/v16.19.0/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:949:29 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**To Reproduce**

1. Add the AWS Lambda node (`n8n-nodes-base.awsLambda`)
2. Fill it with what it needs
3. In the JSON input field, add a JSON object
4. See error in terminal
_picture for reference_ 
        ![image](https://user-images.githubusercontent.com/94578938/226106675-f3ba566f-7d3c-4a78-a7e6-b05a32b30629.png)

**Expected behavior**
Expected behavior is for the node to accept the json object being fed or some way to feed it a json object and not a string

**Comment by Joffcom** [comment]
Hey @HazemSayad 

Just to unblock you quickly if you stringify the expression does that work?

**Comment by HazemSayad** [comment]
Hi @Joffcom technically yes, the node works if i pass a stringified JSON object to it (using `JSON.stringify()`), or if i pass a normal string. As long as I am passing a string to the _"JSON input"_ field, the node works

**Comment by Joffcom** [comment]
Perfect, so I think we have 2 options there... either make it clear it needs to be a string or we just convert it internally which will be less hassle for anyone using the node.

**Comment by HazemSayad** [comment]
@Joffcom Even though the field says JSON object, it should be a string? But lambda functions take events which can be JSON objects. Can you elaborate more please?

**Comment by Joffcom** [comment]
@HazemSayad the field doesn't say json object from your screenshot but the expression shows it is an object.

The error message is saying we are expecting a string but have an object so there are a couple of possible internal things we can do I will need to check the code properly on Monday to see what we are doing. It could be that we convert the string to an object in which case we need to check the datatype first.

**Comment by Joffcom** [comment]
Hey @HazemSayad,

This will be looked at in the future but for now this is working how we would expect, In the future we are going to change the input to use a new field type but I am not sure when that will be.

For now though I am going to mark this as closed.
