### ISSUE TITLE
'getOwnPropertyDescriptor' on proxy error

### ISSUE THREAD

**Issue by vetaljanos** [n8n-io/n8n#5847]
**Describe the bug**
After upgrade on version 0.222.0 (community) I found that some workflows fail with error:

Problem in node ‘Code1‘
'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property '__rowNum__' that is incompatible with the existing property in the proxy target

In the details stack trace:
```
TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property '__rowNum__' that is incompatible with the existing property in the proxy target
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/AugmentObject.js:110:44)
    at Function.entries (<anonymous>)
    at standardizeOutputRecursive (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Code/utils.js:13:43)
    at standardizeOutput (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Code/utils.js:29:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Code/Code.node.js:83:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:653:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:590:53
```
It happens in Code node and can be reproduced even on totally clean docker run

**Steps to reproduce the behavior**

1. Run docker n8n
```bash
docker run --rm -it -p 5678:5678 n8nio/n8n
```
2. Import this example workflow:
```json
{
  "meta": {
    "instanceId": "86e61fb189796a69fc700ec4b8fa5b903e99380c45e8452d90d884c2358594a9"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "d4ccd71b-f336-4184-bb28-0c8a928cf30e",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        300,
        260
      ]
    },
    {
      "parameters": {
        "jsCode": "// Loop over input items and add a new field\n// called 'myNewField' to the JSON of each one\nfor (const item of $input.all()) {\n  item.json.myNewField = 1;\n}\n\nreturn $input.all();"
      },
      "id": "2bda8b91-1c15-4a81-924f-6c8e1cb1eb8a",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        540,
        260
      ]
    },
    {
      "parameters": {
        "jsCode": "// Loop over input items and add a new field\n// called 'myNewField' to the JSON of each one\nfor (const item of $input.all()) {\n  item.json.zxc = 1;\n}\n\nreturn $input.all();"
      },
      "id": "3d5ac2d9-2886-47d8-9307-138f4db0a3c6",
      "name": "Code1",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1640,
        260
      ]
    },
    {
      "parameters": {
        "fileName": "/tmp/1.csv",
        "dataPropertyName": "={{ $json }}",
        "options": {
          "append": false
        }
      },
      "id": "50b681a6-8c8d-44f6-875c-0e755290d85f",
      "name": "Write Binary File",
      "type": "n8n-nodes-base.writeBinaryFile",
      "typeVersion": 1,
      "position": [
        980,
        260
      ]
    },
    {
      "parameters": {
        "operation": "toFile",
        "fileFormat": "csv",
        "binaryPropertyName": "={{ $json }}",
        "options": {}
      },
      "id": "0d5a1f8a-4eec-4425-b7b4-bf774e7e382e",
      "name": "Spreadsheet File",
      "type": "n8n-nodes-base.spreadsheetFile",
      "typeVersion": 1,
      "position": [
        760,
        260
      ]
    },
    {
      "parameters": {
        "fileSelector": "/tmp/1.csv"
      },
      "id": "4144d401-2b66-4126-a514-6fd715569c04",
      "name": "Read Binary Files",
      "type": "n8n-nodes-base.readBinaryFiles",
      "typeVersion": 1,
      "position": [
        1200,
        260
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "82b0e535-58f1-47ed-a0cf-68e5328c7505",
      "name": "Spreadsheet File1",
      "type": "n8n-nodes-base.spreadsheetFile",
      "typeVersion": 1,
      "position": [
        1420,
        260
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "Spreadsheet File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Write Binary File": {
      "main": [
        [
          {
            "node": "Read Binary Files",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Spreadsheet File": {
      "main": [
        [
          {
            "node": "Write Binary File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Read Binary Files": {
      "main": [
        [
          {
            "node": "Spreadsheet File1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Spreadsheet File1": {
      "main": [
        [
          {
            "node": "Code1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```
3. Execute Workflow
4. See error on last error node

**Environment**

- OS: Ubuntu Linux 22.04 / MacOS 13.1
- n8n Version: 0.222.0 (docker latest)
- No other changes in docker or n8n envs

**Comment by firehist** [comment]
Thanks for this issue, I got the exact same error on node code right after a Spreadsheet Node.

*   n8n Version: 221.2

![](https://user-images.githubusercontent.com/449520/228958495-ed1262bc-20bd-4346-a32b-20c11a339f31.png)

![](https://user-images.githubusercontent.com/449520/228958496-fdaeeca9-8046-44a7-a1a0-eadebe6bec82.png)

**Comment by firehist** [comment]
Quick update

1.  I tested on our k8s stack for version: **n8n@0.222.0, n8n@0.221.2, n8n@0.221.1, n8n@0.221.0** and it still fails
2.  It works like a charm on **n8n@0.220.1**

**Comment by firehist** [comment]
Thanks a lot for all you work @netroy .  
Awaiting a release to package it and test it again!
