### ISSUE TITLE
Jira Node (self-hosted) - type of undefined

### ISSUE THREAD

**Issue by mvhirsch** [n8n-io/n8n#585]
**Describe the bug**
I wanted to create a new, using Jira self-hosted version.
After adding credentials, it states:

> Cannot read property 'type' of undefined

on "project" and "issue type". Setting them manually and testing the node, the answer after execution is still the same. Seems like it's broken :-(

**To Reproduce**
1. Create new Jira node
2. Select "Server"-Version and fill credentials
3. Try setting "project" or "issue type"

**Expected behavior**
I'm able to select my projects and issue types, also executing the node works.

**Environment (please complete the following information):**
 - Docker `n8nio/n8n:0.67.3`

**Comment by mvhirsch** [comment]
Just found a stack trace in logs:

```ERROR RESPONSE
TypeError: Cannot read property 'type' of undefined
at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
at new LoadNodeParameterOptions (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/LoadNodeParameterOptions.js:9:36)
at /usr/local/lib/node_modules/n8n/dist/src/Server.js:321:38
at /usr/local/lib/node_modules/n8n/dist/src/ResponseHelper.js:70:32
at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:335:12)```

**Comment by mvhirsch** [comment]
Due to the fact that I started creating a new workflow, upgrading n8n in-between while keeping my browser window open ... I cannot reproduce this issue anymore.
