### ISSUE TITLE
Error using with postgresql

### ISSUE THREAD

**Issue by rdlu** [n8n-io/n8n#60]
I've created a docker-compose file to use n8n with postgresql as follows:

```
version: '3'
services:
  n8n:
    image: n8nio/n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_AUTH-true}
      N8N_BASIC_AUTH_USER: ${N8N_USER-dlucomposer}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PW-dlucomposer}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${N8N_PG_DB-n8n}
      DB_POSTGRESDB_HOST: ${N8N_PG_HOST-n8n_db}
      DB_POSTGRESDB_PORT: ${N8N_PG_PORT-5432}
      DB_POSTGRESDB_USER: ${N8N_PG_USER-n8n}
      DB_POSTGRESDB_PASSWORD: ${N8N_PG_PW-n8n}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.localhost`)
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    networks:
      - default
      - traefik_net
  db:
    image: postgres
    container_name: n8n_db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${N8N_PG_PW-n8n}
      POSTGRES_USER: ${N8N_PG_USER-n8n}
      POSTGRES_DB: ${N8N_PG_DB-n8n}
networks:
  default:
  traefik_net:
    external: true
volumes:
  pgdata:
```

But n8n does not start with following errors on docker log:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1),
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
(node:1) UnhandledPromiseRejectionWarning: Error: There was an error: column cnst.consrc does not exist,
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:22:17),
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:105:22,
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

And the following on postgres docker log:

```
2019-10-10 19:14:38.561 UTC [152] ERROR:  current transaction is aborted, commands ignored until end of transaction block,
2019-10-10 19:14:38.561 UTC [152] STATEMENT:  SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "i"."relname" AS "constraint_name", "a"."attname" AS "column_name", CASE "ix"."indisunique" WHEN 't' THEN 'TRUE' ELSE'FALSE' END AS "is_unique", pg_get_expr("ix"."indpred", "ix"."indrelid") AS "condition", "types"."typname" AS "type_name" FROM "pg_class" "t" INNER JOIN "pg_index" "ix" ON "ix"."indrelid" = "t"."oid" INNER JOIN "pg_attribute" "a" ON "a"."attrelid" = "t"."oid"  AND "a"."attnum" = ANY ("ix"."indkey") INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "t"."relnamespace" INNER JOIN "pg_class" "i" ON "i"."oid" = "ix"."indexrelid" INNER JOIN "pg_type" "types" ON "types"."oid" = "a"."atttypid" LEFT JOIN "pg_constraint" "cnst" ON "cnst"."conname" = "i"."relname" WHERE "t"."relkind" = 'r' AND "cnst"."contype" IS NULL AND (("ns"."nspname" = 'public' AND "t"."relname" = 'credentials_entity') OR ("ns"."nspname" = 'public' AND "t"."relname" = 'execution_entity') OR ("ns"."nspname" = 'public' AND "t"."relname" = 'workflow_entity')),
2019-10-10 19:14:38.562 UTC [152] ERROR:  current transaction is aborted, commands ignored until end of transaction block,
2019-10-10 19:14:38.562 UTC [152] STATEMENT:  SELECT "con"."conname" AS "constraint_name", "con"."nspname" AS "table_schema", "con"."relname" AS "table_name", "att2"."attname" AS "column_name", "ns"."nspname" AS "referenced_table_schema", "cl"."relname" AS "referenced_table_name", "att"."attname" AS "referenced_column_name", "con"."confdeltype" AS "on_delete", "con"."confupdtype" AS "on_update", "con"."condeferrable" AS "deferrable", "con"."condeferred" AS "deferred" FROM ( SELECT UNNEST ("con1"."conkey") AS "parent", UNNEST ("con1"."confkey") AS "child", "con1"."confrelid", "con1"."conrelid", "con1"."conname", "con1"."contype", "ns"."nspname", "cl"."relname", "con1"."condeferrable", CASE WHEN "con1"."condeferred" THEN 'INITIALLY DEFERRED' ELSE 'INITIALLY IMMEDIATE' END as condeferred, CASE "con1"."confdeltype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confdeltype", CASE "con1"."confupdtype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confupdtype" FROM "pg_class" "cl" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_constraint" "con1" ON "con1"."conrelid" = "cl"."oid" WHERE "con1"."contype" = 'f' AND (("ns"."nspname" = 'public' AND "cl"."relname" = 'credentials_entity') OR ("ns"."nspname" = 'public' AND "cl"."relname" = 'execution_entity') OR ("ns"."nspname" = 'public' AND "cl"."relname" = 'workflow_entity')) ) "con" INNER JOIN "pg_attribute" "att" ON "att"."attrelid" = "con"."confrelid" AND "att"."attnum" = "con"."child" INNER JOIN "pg_class" "cl" ON "cl"."oid" = "con"."confrelid" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_attribute" "att2" ON "att2"."attrelid" = "con"."conrelid" AND "att2"."attnum" = "con"."parent",
2019-10-10 19:15:40.365 UTC [155] ERROR:  column cnst.consrc does not exist at character 194,
2019-10-10 19:15:40.365 UTC [155] HINT:  Perhaps you meant to reference the column "cnst.conkey" or the column "cnst.conbin".,
2019-10-10 19:15:40.365 UTC [155] STATEMENT:  SELECT "ns"."nspname" AS "table_schema", "t"."relname" AS "table_name", "cnst"."conname" AS "constraint_name", CASE "cnst"."contype" WHEN 'x' THEN pg_get_constraintdef("cnst"."oid", true) ELSE "cnst"."consrc" END AS "expression", CASE "cnst"."contype" WHEN 'p' THEN 'PRIMARY' WHEN 'u' THEN 'UNIQUE' WHEN 'c' THEN 'CHECK' WHEN 'x' THEN 'EXCLUDE' END AS "constraint_type", "a"."attname" AS "column_name" FROM "pg_constraint" "cnst" INNER JOIN "pg_class" "t" ON "t"."oid" = "cnst"."conrelid" INNER JOIN "pg_namespace" "ns" ON "ns"."oid" = "cnst"."connamespace" LEFT JOIN "pg_attribute" "a" ON "a"."attrelid" = "cnst"."conrelid" AND "a"."attnum" = ANY ("cnst"."conkey") WHERE "t"."relkind" = 'r' AND (("ns"."nspname" = 'public' AND "t"."relname" = 'credentials_entity') OR ("ns"."nspname" = 'public' AND "t"."relname" = 'execution_entity') OR ("ns"."nspname" = 'public' AND "t"."relname" = 'workflow_entity')),
```

It seems to work fine when I comment out the DB_TYPE and friends from n8n environment to not use postgresql.

I think some migration or database creation routine is not right.

The versions I'm using are the ones with 'latest' tag (version 0.24 for n8n and 12 for postgres)

Thanks for this great project!

**Comment by janober** [comment]
Just checked your setup but everything also looks correct to me. Not sure what we are overlooking. But did you try it with that setup, because that one should work:
https://github.com/n8n-io/n8n/tree/master/docker/compose/withPostgres

The only difference I can see there is the Postgres version. Think until now I always used 11. Not sure if 12 could cause the problems you have.

**Comment by rdlu** [comment]
I'll try some postgres combinations, thanks!

**Comment by dimlev** [comment]
Same issues (without docker) with postgres 12. Works fine with postgres 11

**Comment by janober** [comment]
@dimlev Thanks for the update! That is good to know. Will add it my To-Do-List.

**Comment by lalitpagaria** [comment]
I think this issue can be closed now as this bug is fixed by upgrading [typeorm lib](https://github.com/typeorm/typeorm/issues/4332) in this [commit](https://github.com/n8n-io/n8n/commit/1aa51944a6a2077ad80e6d2a4b089cdc4aee5905).

**Comment by janober** [comment]
Thanks a lot @lalitpagaria yes makes sense. Has been changed up quite a bit recently. I Will close for now. If @rdlu @dimlev or anybody else still has problems please comment here again. Thanks!
