### ISSUE TITLE
NocoDB can't fetch projects

### ISSUE THREAD

**Issue by sudoexec** [n8n-io/n8n#6550]
**Describe the bug**
NocoDB can't fetch projects and tables.

**To Reproduce**

1. create a NocoDB node
2. create NocoDB credential
3. "Project Name or ID" and "Table Name or ID" field is empty

**Expected behavior**
"Project Name or ID" and "Table Name or ID" should show projects and tables list.

**Environment (please complete the following information):**
Self-hosted Docker container.

NocoDB Version: 0.109.2

- OS: NixOS 20.09
- n8n Version: 0.233.1
- Node.js Version: (use the official docker image)
- Database system: PostgreSQL
- Operation mode: (use default)

**Additional context**
n8n log:
```
error    | NodeOperationError: Error while fetching projects! "{ file: 'ErrorReporterProxy.js', function: 'report' }"
error    | Error: Error while fetching projects! "{ file: 'ErrorReporterProxy.js', function: 'report' }"
error    | NodeApiError: Bad request - please check your parameters "{ file: 'ErrorReporterProxy.js', function: 'report' }"
error    | Error: 400 - {"msg":"Undefined binding(s) detected for keys [0] when compiling RAW query: ?"} "{ file: 'ErrorReporterProxy.js', function: 'report' }"
```

NocoDB log:
```
[Nest] 11 ERROR [i] Undefined binding(s) detected for keys [0] when compiling RAW query: ?
Error: Undefined binding(s) detected for keys [0] when compiling RAW query: ?
    at Raw.toSQL (/usr/src/app/node_modules/knex/lib/raw.js:110:13)
    at unwrapRaw (/usr/src/app/node_modules/knex/lib/formatter/wrappingFormatter.js:116:19)
    at wrap (/usr/src/app/node_modules/knex/lib/formatter/wrappingFormatter.js:80:15)
    at QueryCompiler_PG.onBasic (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:910:7)
    at QueryCompiler_PG.join (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:445:40)
    at /usr/src/app/node_modules/knex/lib/query/querycompiler.js:133:40
    at Array.forEach (<anonymous>)
    at QueryCompiler_PG.select (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:132:16)
    at QueryCompiler_PG.toSQL (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:73:29)
    at QueryBuilder_PostgreSQL.toSQL (/usr/src/app/node_modules/knex/lib/query/querybuilder.js:83:44)
```

**Comment by Joffcom** [comment]
Hey @sudoexec,

I have just given this a go on NocoDB `0.109.2` and for me this is working as expected using either of the 2 authentication types. 

![image](https://github.com/n8n-io/n8n/assets/4688521/c7cc41b2-6b51-442b-ab7b-b9998efa3507)

Did you try refreshing the list using the refresh list option?

![image](https://github.com/n8n-io/n8n/assets/4688521/332a929d-e7bc-462c-a856-d74f6a4203ff)

**Comment by sudoexec** [comment]
@Joffcom Thanks for your help. It's the fault of NocoDB.
The api token I used is created in a previous version of NocoDB. After upgrading to recent versions, the api token has no owner.
I created a new api token, and it works fine.
