### ISSUE TITLE
Google Calendar Trigger - New Event

### ISSUE THREAD

**Issue by Pukabyte** [n8n-io/n8n#6983]
**Describe the bug**
Cannot get events from my calendars, A couple calendars work but not all of them, it comes up with this message:
{"message":"No data with the current filter could be found"}

NodeApiError: No data with the current filter could be found
    at Object.poll (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Calendar/GoogleCalendarTrigger.node.js:188:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:655:32)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:631:53

**To Reproduce**

1. Go to Trigger Event
2. Click on Google Calendar
3. Select Credentials, Calendar and Trigger on 'Event Created'
4. Click Fetch Test Event
5. See error

**Expected behavior**
It should pull a recent event from my calendar

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 1.3.1
- Node.js Version [e.g. 18.16.0]

**Additional context**
2 of my calendars work, the others do not parse any information
Failed
![image](https://github.com/n8n-io/n8n/assets/120460627/10dc071e-a009-45a3-8273-70bd948da8ab)
Working
![image](https://github.com/n8n-io/n8n/assets/120460627/5d9c468a-ee77-456e-9329-f7715aaa9b7e)

**Comment by Joffcom** [comment]
Hey @Pukabyte,

Does the Calendar you are connecting to have any events? Typically if it is working for some of them but not all then the issue is likely to be something in the calendar.

**Comment by Pukabyte** [comment]
Yes all calendars have events both past and future and current.

**Comment by Joffcom** [comment]
@Pukabyte is there anything different with it? If you use the normal node does that return events ok?

**Comment by Pukabyte** [comment]
Nothing is different from what I can see, they are both secondary calendars etc. not sure why it's not getting events from here

**Comment by Joffcom** [comment]
Hey @Pukabyte,

I am still not able to reproduce this, Are you still seeing an issue with this?

**Comment by yellowpizzav2** [comment]
I have this too. It started when I made changes to the event that was fetched as "Fetch Test Event"

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
