### ISSUE TITLE
Bootstrap problems on Linux (tested on Manjaro and Alpine) 

### ISSUE THREAD

**Issue by mindreframer** [n8n-io/n8n#705]
First: thank you for such a great automation tool! 

I wanted to setup a dev. environment locally and somehow lerna installation was failing. Maybe I forgot a step, it's a bit strange to get such issues right on installation... Reproducible in Docker (but with my local Linux kernel from Manjaro, should not matter that much though....)

**Describe the bug**
Running `npm run bootstrap` results in the following error message: 

```

npm ERR! Unexpected end of JSON input while parsing near '...CVj62Bc/WBOCN/R3GabWm'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-27T13_54_32_319Z-debug.log

lerna ERR! npm install exited 1 in 'n8n'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ bootstrap: `lerna bootstrap --hoist --no-ci`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-27T13_54_32_368Z-debug.log

```
Log output: 

```
/home/sand/n8n # tail -n 30  /root/.npm/_logs/2020-06-27T13_54_32_368Z-debug.log
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle n8n@~prebootstrap: n8n@
6 info lifecycle n8n@~bootstrap: n8n@
7 verbose lifecycle n8n@~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle n8n@~bootstrap: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sand/n8n/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle n8n@~bootstrap: CWD: /home/sand/n8n
10 silly lifecycle n8n@~bootstrap: Args: [ '-c', 'lerna bootstrap --hoist --no-ci' ]
11 silly lifecycle n8n@~bootstrap: Returned: code: 1  signal: null
12 info lifecycle n8n@~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: n8n@ bootstrap: `lerna bootstrap --hoist --no-ci`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid n8n@
15 verbose cwd /home/sand/n8n
16 verbose Linux 5.6.16-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error n8n@ bootstrap: `lerna bootstrap --hoist --no-ci`
22 error Exit status 1
23 error Failed at the n8n@ bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**To Reproduce**

```bash
# start Alpine in docker
docker run -it --rm alpine

# inside the container
apk add git nodejs npm
mkdir /home/sand && cd /home/sand
git clone https://github.com/n8n-io/n8n.git
cd n8n

# checkout state from 2020/06/26
git checkout d221f6dd97942e1377f5af28d16c56727433e13a 
npm i

# this should already error out
npm run bootstrap
```

**Expected behavior**
Should finish bootstrapping properly

**Environment (please complete the following information):**
```
$ cat /etc/alpine-release
3.12.0

$ node -v
v12.17.0

$  npm -v
6.14.4
```

**Comment by mindreframer** [comment]
On Manjaro the issue was happening with Node 10.x.x and 12.x.x.

**Comment by mindreframer** [comment]
Found this Dockerfile: https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/Dockerfile

`bootstrap` finishes properly with it, yet it is still interesting, why the plain Docker image with node + npm fails with such a cryptic error.

**Comment by janober** [comment]
I would check what is different. Maybe the: `npm_config_user=root`

**Comment by mindreframer** [comment]
@janober Thanks for the quick response! npm config user did improve the situation. 

```
 ~/w/n/n8n at master ✔ npm_config_user=root npm run bootstrap

> n8n@ bootstrap /home/roman/work/nodejs/n8n
> lerna bootstrap --hoist --no-ci

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 6 packages
lerna WARN EHOIST_PKG_VERSION "n8n-editor-ui" package depends on @types/express@^4.17.6, which differs from the hoisted @types/express@^4.16.1.
lerna WARN EHOIST_PKG_VERSION "n8n-editor-ui" package depends on @types/jest@^25.2.1, which differs from the hoisted @types/jest@^24.0.18.
lerna WARN EHOIST_PKG_VERSION "n8n-editor-ui" package depends on @types/node@12.12.22, which differs from the hoisted @types/node@^10.10.1.
lerna WARN EHOIST_PKG_VERSION "n8n-nodes-base" package depends on @types/request-promise-native@~1.0.15, which differs from the hoisted @types/request-promise-native@^1.0.15.
lerna WARN EHOIST_PKG_VERSION "n8n-editor-ui" package depends on ts-jest@^25.4.0, which differs from the hoisted ts-jest@^24.0.2.
lerna WARN EHOIST_PKG_VERSION "n8n-core" package depends on tslint@6.1.2, which differs from the hoisted tslint@^6.1.2.
lerna WARN EHOIST_PKG_VERSION "n8n-node-dev" package depends on tslint@^5.17.0, which differs from the hoisted tslint@^6.1.2.
lerna WARN EHOIST_PKG_VERSION "n8n-nodes-base" package depends on tslint@^5.17.0, which differs from the hoisted tslint@^6.1.2.
lerna WARN EHOIST_PKG_VERSION "n8n" package depends on inquirer@^7.0.1, which differs from the hoisted inquirer@^7.0.0.
lerna WARN EHOIST_PKG_VERSION "n8n-core" package depends on @types/cron@^1.7.1, which differs from the hoisted @types/cron@^1.6.1.
lerna WARN EHOIST_PKG_VERSION "n8n-node-dev" package depends on n8n-workflow@^0.28.0, which differs from the hoisted n8n-workflow@~0.32.0.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install exited 1 in 'n8n'
lerna ERR! npm install stderr:
npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/open@6.2.1: This is a stub types definition. open provides its own type definitions, so you do not need this installed.
npm WARN deprecated pg-promise@9.3.6: This version of pg-promise is obsolete. You should update to a newer version.
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '...hyxH5cp\nVQ38eGV3OfUC'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/roman/.npm/_logs/2020-06-27T17_19_13_413Z-debug.log

lerna ERR! npm install exited 1 in 'n8n'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ bootstrap: `lerna bootstrap --hoist --no-ci`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/roman/.npm/_logs/2020-06-27T17_19_13_445Z-debug.log
▲ ~/w/n/n8n at master ✔

```


I'll take a deeper look into it tomorrow :) 

Have a nice evening!

**Comment by K4ds3** [comment]
If anybody else has this error and finds this issue;

running `npm cache clean -f` fixed all problems for me and allowed me to successfully execute lerna bootstrap

**Comment by krynble** [comment]
Hey @mindreframer we got an update from @K4ds3 that might help you.

Would you mind giving it a try? 

I tried the steps you mentioned above to reproduce the error but I am getting new errors (missing python, missing make, etc.).

Again, using the node image as a base seems to work fine instead of using raw alpine.

**Comment by krynble** [comment]
Closing this issue as we have no more updates. Please feel free to reopen.
