### ISSUE TITLE
Excel 365 Node Query option $select error with filter parameter

### ISSUE THREAD

**Issue by jkirkpatrick** [n8n-io/n8n#7415]
**Describe the bug**
Query option '$select' was specified more than once, but it must be specified at most once.

**To Reproduce**

In the Excel 365 node...

1. Resource: Workbook
2. Operation: Get Many
3. Return All: true / on / enabled
4. Fields: id

**Expected behavior**
Return a list of workbook ids

**Environment (please complete the following information):**

- OS: docker image
- n8n: 1.9.1
- Node.js Version [e.g. 18.16.0]: image default v18.18.0
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: image default
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]: image default

**Additional context**
This workflow works fine with previous version 1.6 - error occurs when upgrading to 1.9.1

Stack Error
```
NodeApiError: Bad request - please check your parameters
    at Object.microsoftApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Excel/v2/transport/index.js:23:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.microsoftApiRequestAllItems (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Excel/v2/transport/index.js:33:24)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Excel/v2/actions/workbook/getAll.operation.js:66:32)
    at Object.router (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Excel/v2/actions/router.js:45:26)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:19)
```

**Comment by jkirkpatrick** [comment]
Note that Setting `Return All` to off/false/disabled and removing the `Filter` works properly

**Comment by jkirkpatrick** [comment]
Narrowed down the issue - it only occurs when the `Filter` parameter is enabled; does not matter if there is one field (`id`) or a comma-delim list of fields (`id, parentReference, name, webUrl`)

**Comment by Joffcom** [comment]
Hey @jkirkpatrick,

Thanks for the report, I have just tried to follow your instructions to reproduce this and I have not been able to.

![image](https://github.com/n8n-io/n8n/assets/4688521/ae2dea84-1012-46e1-a840-5ce7eef05b86)

I have also tried with multiple items with no luck.

![image](https://github.com/n8n-io/n8n/assets/4688521/7ce711dd-5c95-49eb-acc8-af38b42141b0)

Out of interest how many sheets do you have available, Is it over 100? I think this could be a pagination issue.

**Comment by jkirkpatrick** [comment]
Yes, over 100 sheets - but under 10000.

**Comment by Joffcom** [comment]
Hey @jkirkpatrick,

Perfect in that case this will be the Pagination issue, I will add this to the internal ticket we have for this with another Microsoft 365 node.

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
