### ISSUE TITLE
NocoDB node: two issues with attachments

### ISSUE THREAD

**Issue by naamval** [n8n-io/n8n#7613]
**Describe the bugs**
_Bug 1: Attachment upload via NocoDB node_
When uploading attachments to NocoDB, the files cannot be seen in NocoDB's interface. A row with an attachment uploaded via n8n's NocoDB node (option selected: API version v.0.90.0 onwards) will look like row 1 here. The attachment cannot be downloaded or viewed.
![NocoDB](https://github.com/n8n-io/n8n/assets/21039324/2a5e712a-e2ef-43fe-a15a-9756f07ef45d)

I think that this is caused by the n8n node uploading the file to the 'wrong' folder. 
- When using NocoDB node in n8n, the file ends up in /nc/uploads/{filename.extension}.
- When using NocoDB's own UI, the attachment is uploaded to /nc/uploads/noco/{projectid}/{tableid}/{columnid}/{filename.extension}. In that case, the attachment can be viewed and downloaded (see row 2 in the image above). This seems to be the 'correct' way, although I cannot find this stated clearly in NocoDB's documentation.

_Bug 2: Attachment download via NocoDB node_
'Download Attachments' in the NocoDB node (get/get many) does not work. It returns **ERROR: Unexpected token o in JSON at position 1** with the following details:
```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at jsonParse (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/utils.js:62:21)
    at Object.downloadRecordAttachments (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/NocoDB/GenericFunctions.js:55:80)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/NocoDB/NocoDB.node.js:370:97)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:670:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:652:53
```

**Environment (please complete the following information):**
- n8n Version 1.14.2 (Docker)
- Database system Postgres
- Operation mode Queue

**Comment by Joffcom** [comment]
Hey @naamval 

There is a PR in that resolves the first issue, I will give it a test to see if it fixes the second issue as well.

**Comment by naamval** [comment]
Great, thank you!

**Comment by zblesk** [comment]
I've also gotten  the "Unexpected token o in JSON at position 1". I got rid of it by adding quotes; so instead of `File` I wrote `"File"`. 

I do get a JSON response, but I don't see the file anywhere - I'm trying to pass it to a CSV reader node, but the data don't seem to be there.

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
