### ISSUE TITLE
Problems with ?= when requesting http request

### ISSUE THREAD

**Issue by dalso0418** [n8n-io/n8n#7694]
**Describe the bug**

**When putting the preceding variable using http request

The api call is not successful because ?= has been added.**

ref. https://phpipam.net/api/api_documentation/

request url
https://phpipam/api/test/addresses/search/{{ $json.ip }}

```
{
"status": 
"rejected",
"reason": 
{
"message": 
"400 - "{\"code\":400,\"success\":false,\"message\":\"Invalid address\",\"time\":0.012}"",
"name": 
"Error",
"stack": 
"Error: 400 - "{\"code\":400,\"success\":false,\"message\":\"Invalid address\",\"time\":0.012}" at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:238:9) at RedirectableRequest.emit (node:events:529:35) at RedirectableRequest.emit (node:domain:489:12) at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:368:10) at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:65:10) at Object.onceWrapper (node:events:632:26) at ClientRequest.emit (node:events:517:28) at ClientRequest.emit (node:domain:489:12)"
}
}
```
If {{json.ip}} is entered manually, api will be called normally.

The access log of the phpipam.

`[n8n ip] - - [13/Nov/2023:14:22:23 +0900] "GET /api/test/addresss/search/1.2.3.4?= HTTP/1.1" 400 83 "-" "axios/0.21.4"
`
Type error occurs because of ?= above.

Please check. Thank you.

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] rocky linux 8.6
- n8n Version [e.g. 1.0.1] 1.16.0
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by dalso0418** [comment]
Failed to resolve by turning on Opntions -> Response -> Never Error option.
