### ISSUE TITLE
N8N docker version: cannot use sqlite in AI Agent

### ISSUE THREAD

**Issue by kmkarakaya** [n8n-io/n8n#7799]
**Describe the bug**
1. I load an SQLite file by Read Binary Files .
2. Then, I connect  Read Binary Files to AI Agent.
3. When executed, AI Agent arises error message: 
_**Problem running workflow
Request failed with status code 413**_
Please see the screenshots below.

**To Reproduce**

![image](https://github.com/n8n-io/n8n/assets/41159849/ec88043c-eb73-4b1f-9227-a7aaddf31ebb)

![chrome_opz0uYux60](https://github.com/n8n-io/n8n/assets/41159849/5a62fca4-0806-44d3-a2f7-8bbc28250879)

![image](https://github.com/n8n-io/n8n/assets/41159849/df640b97-4b30-4265-ad0f-9042db74846c)

**Expected behavior**
AI Agent should be able to use SQLite file to answer the prompt.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] Ubuntu WSL2 
- n8n Version [e.g. 1.0.1] ai-beta
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by netroy** [comment]
This sounds like the binary-data is being kept in memory and being re-uploaded on every manual execution. Hence the 413, because the sqlite file is now too large for the incoming request body parser.

Can you check if the env variable `N8N_DEFAULT_BINARY_DATA_MODE` is set to `filesystem` or not? if it's not set, can you please try setting it, and then trying again?

**Comment by kmkarakaya** [comment]
I run the command:
docker run -it --rm --name n8n **-e N8N_DEFAULT_BINARY_DATA_MODE=filesystem**  --network ollam
a-n8n-network  -p 5678:5678 -v ~/.n8n:/home/node/.n8n -v $(pwd):/tmp docker.n8n.io/n8nio/n8n:ai-beta

But this time I got **another error** message:
_ERROR: SQLITE_NOTADB: file is not a database
 Details
Stack
QueryFailedError: SQLITE_NOTADB: file is not a database
    at handler (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/typeorm@0.3.17_mssql@8.1.4_pg@8.11.3_redis@4.6.10_sqlite3@5.1.6/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at replacement (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/sqlite3@5.1.6/node_modules/sqlite3/lib/sqlite3.js:15:21)_

The screenshot:
![image](https://github.com/n8n-io/n8n/assets/41159849/1b55b377-8315-4636-b2d3-c3f0202e88df)

Thank you for your help in advance!

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
