### ISSUE TITLE
Error ERR_OSSL_BAD_DECRYPT

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#7887]
**Describe the bug**

This error appears when a workflow is executed in production (worker service)

When run in the editor, it works normally.
**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 1.18.0
- Node.js Version [e.g. 18.16.0]
- Database system Postgres
- Operation mode queue

**Additional context**

Output log:

```
2023-11-30T13:29:15.723Z | verbose  | Workflow execution finished with error "{\n  error: {\n    context: {},\n    severity: 'warning',\n    name: 'NodeApiError',\n    timestamp: 1701350955720,\n    node: {\n      parameters: [Object],\n      id: '585cfc5e-15a8-461e-acd3-c1ea70f6aad0',\n      name: 'Google Sheets',\n      type: 'n8n-nodes-base.googleSheets',\n      typeVersion: 4.2,\n      position: [Array],\n      credentials: [Object]\n    },\n    httpCode: 'ERR_OSSL_BAD_DECRYPT',\n    description: undefined,\n    message: 'error:1C800064:Provider routines::bad decrypt',\n    stack: 'NodeApiError: error:1C800064:Provider routines::bad decrypt\\n' +\n      '    at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Sheet/v2/transport/index.js:49:15)\\n' +\n      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\\n' +\n      '    at GoogleSheet.spreadsheetGetSheetNameById (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Sheet/v2/helpers/GoogleSheet.js:55:26)\\n' +\n      '    at Object.router (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Sheet/v2/actions/router.js:66:33)\\n' +\n      '    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:672:19)\\n' +\n      '    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:655:53'\n  },\n  workflowId: 'q854gdNm6zVHdeOk',\n  file: 'LoggerProxy.js',\n  function: 'exports.verbose'\n}"
```

**Comment by netroy** [comment]
Can you check if `N8N_ENCRYPTION_KEY` is passes to worker service, and it's the same value as the one passed into the main service?

**Comment by talkwaycombr** [comment]
> Can you check if `N8N_ENCRYPTION_KEY` is passes to worker service, and it's the same value as the one passed into the main service?

Yes! The N8N_ENCRYPTION_KEY is the same in [main] [webhook] and [worker.]

This error only returns in [worker] when it finds a node with Credentials for some service.

However, when these same credentials are called by [main], everything is ok in execution.

**Comment by talkwaycombr** [comment]
> **Describe the bug**
> 
> This error appears when a workflow is executed in production (worker service)
> 
> When run in the editor, it works normally.
>

OS: Docker (Ubuntu 20.04)
n8n Version 1.18.1
Node.js Version 18.18.2
Database system: Postgres
Operation mode:  queue

**Comment by Joffcom** [comment]
@luizeof are you seeing the same issue? There was a similar issue posted on the forum as well so I am trying to work out if we have 3 people with an issue, 2 people or just 1

**Comment by Joffcom** [comment]
Hey @luizeof,

Ah ok so you have opened the issue on behalf of someone else, That has caused a bit of confusion :) It is also more likely to be a configuration issue than a bug so the forum would be the correct place to post things like this.

@talkwaycombr Can you share how you have n8n configured and the workers?

**Comment by Joffcom** [comment]
Moving to closed for now, if this is still an issue let me know and we can open it again.
