### ISSUE TITLE
Docker n8n release doesn't work above 0.73.1

### ISSUE THREAD

**Issue by immanuelfodor** [n8n-io/n8n#818]
**Describe the bug**
I can't upgrade the Docker image above tag `0.73.1` as the newer images are stuck in a restart loop.

**To Reproduce**
1. `0.73.1` works fine
2. Update the image to `0.74.0` or `0.75.0` (this is equivalent of `latest` as of now)
3. The container is stuck in a restart loop
4. Downgrade to `0.73.1` it works fine again

**Expected behavior**
Latest Docker image works fine.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - n8n Version: `0.74.0` or `0.75.0` 
 - Node.js Version: whatever in official Docker image

**Additional context**
Logs of the restart loop:

```
Attaching to n8n
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n      | ln: /home/node/.n8n: File exists
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n      | ln: /home/node/.n8n: File exists
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n exited with code 0
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n exited with code 0
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n exited with code 0
n8n      | (node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
n8n      |     at NodeTypesClass.getByName (/usr/local/lib/node_modules/n8n/dist/src/NodeTypes.js:21:41)
n8n      |     at new Workflow (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:16:39)
n8n      |     at WebhookModel1592445003908.up (/usr/local/lib/node_modules/n8n/dist/src/databases/sqlite/migrations/1592445003908-WebhookModel.js:21:38)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
n8n      | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
n8n      | (node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
n8n      | (node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot read property 'type' of undefined
n8n      |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
n8n      |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
n8n      |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
n8n      | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
n8n exited with code 0
... over and over...
```

**Comment by janober** [comment]
Read about your issue and solution here:
https://community.n8n.io/t/error-docker-image-0-74-wont-start/1796

With the new version we will release in a few hours should it print out the name of the unknown node.

**Comment by immanuelfodor** [comment]
Wow, thank you so much, I missed this post! It really did help to deactivate all workflows, do the upgrade then reactivate all of them.

**Comment by janober** [comment]
Great to hear that it works now fine.

Hope the next release makes it easier to identify to unknown nodes to fix the root cause. Because if a node is not known the workflow will not operate correctly (after all then n8n does not know what to run).

**Comment by immanuelfodor** [comment]
The interesting thing here is that I've never installed anything besides what comes with n8n, so I don't really know why would a node be unknown to n8n.

**Comment by janober** [comment]
As mentioned in the forum were there breaking changes (node name had to get changed). So if you use any of those nodes that could be the issue. Here the link to the breaking changes:
https://github.com/n8n-io/n8n/blob/master/packages/cli/BREAKING-CHANGES.md#0670
