### ISSUE TITLE
Monday.com - Problem in node ‘Add update to item‘

### ISSUE THREAD

**Issue by niclm** [n8n-io/n8n#8531]
**Describe the bug**
When using the Monday.com `Add Update` operation using OAuth credentials, the following error occurs:
```
ERROR: Cannot read properties of undefined (reading 'create_update')
```

**To Reproduce**

1. Open nodes panel and search for `Monday.com`
2. Select the `Add an update to an item` action
3. Open the newly added node and enter in the following:
- **Credential to connect with:** Select an OAuth credential that has been given full scope permissions
- **Resource:** Select `Board Item`
- **Operation:** Select `Add Update`
- **Item ID:** Add a valid board item id
- **Update Text:** Add a string value of `Test`
5. Click `Test step`
6. See error

**Expected behaviour**
A new update should be created. **NB:** This works perfectly fine when using an API key, just not with OAuth.

**Environment:**

- OS: `Ubuntu Linux 22.04`
- n8n Version: `1.25.1`
- Node.js Version: `v18.19.0`
- Database system: `SQLite`
- Operation mode: `main`

**Additional context**
```
TypeError: Cannot read properties of undefined (reading 'create_update')
    at Object.execute (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/MondayCom/MondayCom.node.ts:479:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1322:8)
    at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1046:29
```

<img width="895" alt="image" src="https://github.com/n8n-io/n8n/assets/20701744/ca8a42a8-ee02-42a3-9547-fc5b937664cd">

**Comment by niclm** [comment]
<img width="895" alt="image" src="https://github.com/n8n-io/n8n/assets/20701744/d681522a-d08e-4084-8d66-afd7ac2586c4">

**Comment by Joffcom** [comment]
Hey @niclm,

Thanks for reporting this one, it looks like the api may no longer be returning the field we are expecting. I will dig into the api docs for Monday in the morning and see if I can spot what has changed.

**Comment by Joffcom** [comment]
Hey @niclm,

I have taken a look and at first I wasn't able to reproduce it but once I changed from API Token to OAuth that got it failing, I have created `NODE-1102` as the internal ticket to fix tthis. For now if possible if you use an API Token it should get you up and running.

**Comment by niclm** [comment]
I discovered something that may be worth looking into. I tried interacting with the Monday API directly using an HTTP Request node, however I noticed in the response that I lacked permissions to create an update:
<img width="802" alt="image" src="https://github.com/n8n-io/n8n/assets/20701744/87f4a371-8272-4e69-b34a-f3265fb2918d">

I went back to verify the scope in Monday.com and can see that I have enabled the permission correctly. I verified this by clicking on the OAuth Authorisation URL that Monday provides, I saw that the scope was within the list:
<img width="425" alt="image" src="https://github.com/n8n-io/n8n/assets/20701744/35312c2c-5b16-4bf4-a5ba-843a4a9af7dd">

When I connect via n8n I am presented with a different scope, which is missing `updates:write`:
<img width="428" alt="image" src="https://github.com/n8n-io/n8n/assets/20701744/c3a1e0cf-3a3a-4602-a767-97fee1b4bc90">

Is n8n using a different Authorisation URL ?

**Comment by Joffcom** [comment]
Hey @niclm,

That could be it, Our credential only sets `boards:write` and `boards:read` so when we connect to Monday this is all we will request. It makes sense for the error to be with the response not matching what we are using, I can get that updated shortly.

With the authorization url we use `https://auth.monday.com/oauth2/authorize` which is what the Monday docs point to for the OAuth flow.

**Comment by niclm** [comment]
Ah ha! Would it make sense to add checkboxes to specify the scope you need? Or would it make sense to just not set the scope at all from n8n, since that can be managed on Monday?

**Comment by Joffcom** [comment]
That is something I will need to check in their API docs to see what they recommend.

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
