### ISSUE TITLE
Google Drive Node's Create From Text Is Broken - Unknown Error

### ISSUE THREAD

**Issue by andyjoyous** [n8n-io/n8n#8532]
**Describe the bug**
I was originally on n8n version 1.7 and migrated to 1.26. After the migrating, the Google Drive node's `Create From Text` operation no longer works. 

The image below will have the settings and the error. Note that it does work in version 1.7 so it may have been broken anywhere in between.
![Screenshot 2024-02-01 at 3 00 41 PM](https://github.com/n8n-io/n8n/assets/156835992/3efde1ea-b828-4e9c-aef5-c041d8d8d5db)
![Screenshot 2024-02-01 at 3 03 01 PM](https://github.com/n8n-io/n8n/assets/156835992/7b99e347-a1cf-4ff4-bec7-4b19a2839997)
Call stack:
```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.googleApiRequest (/Users/andytran/Documents/original-n8n/n8n/packages/nodes-base/nodes/Google/Drive/v2/transport/index.ts:64:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.execute (/Users/andytran/Documents/original-n8n/n8n/packages/nodes-base/nodes/Google/Drive/v2/actions/file/createFromText.operation.ts:160:24)
    at Object.router (/Users/andytran/Documents/original-n8n/n8n/packages/nodes-base/nodes/Google/Drive/v2/actions/router.ts:30:26)
    at Object.execute (/Users/andytran/Documents/original-n8n/n8n/packages/nodes-base/nodes/Google/Drive/v2/GoogleDriveV2.node.ts:25:10)
    at Workflow.runNode (/Users/andytran/Documents/original-n8n/n8n/packages/workflow/src/Workflow.ts:1332:8)
    at /Users/andytran/Documents/original-n8n/n8n/packages/core/src/WorkflowExecute.ts:1046:29
    at /Users/andytran/Documents/original-n8n/n8n/packages/core/src/WorkflowExecute.ts:1722:11
```

**To Reproduce**

1. Create a Google Drive Node in a workflow to search a file/folder. It works properly with no issues
2. Create another Google Drive Node but to create a file. Use `Create From Text` operation. 
3. Run the node and you should see the error

**Expected behavior**
No errors and a file be created in your drive
**Environment (please complete the following information):**

- OS: MacOS Sonoma 14.3
- n8n Version 1.26
- Node.js Version 20.11.0
- Database system Postgres
- Operation mode: queue

**Comment by Joffcom** [comment]
Hey @andyjoyous,

Are you using a service account or oauth and have you changed the value of `N8N_DEFAULT_BINARY_DATA_MODE` at all?

**Comment by Kabraxist** [comment]
Hey @Joffcom, I'm having the same issue so I might be able to answer the questions.
I'm connected with "Google Drive OAuth2 API" and didn't changed `N8N_DEFAULT_BINARY_DATA_MODE `. Other binary files processing succesfully. Also [Google Drive > Upload a File] operation works without problems.

**Comment by Joffcom** [comment]
Hey @Kabraxist,

Thanks, I found the issue on the forum as well and I will get this fixed shortly.

**Comment by rwegrzyniak** [comment]
Hi @Joffcom any estimiation when it will be fixed?

**Comment by Joffcom** [comment]
Hey @rwegrzyniak,

It won't be fixed in the next release (today) but should be fixed for next weeks release. I have been caught up with higher priority issues.

**Comment by Joffcom** [comment]
Hey @rwegrzyniak,

This is going to be a bit longer, I have created `NODE-1184` as the dev ticket for this. For a work around you can use the v1 node which should work, To use the v1 node you can copy the node and paste it into a text editor and change the version.

**Comment by rwegrzyniak** [comment]
> Hey @rwegrzyniak,
> 
> This is going to be a bit longer, I have created `NODE-1184` as the dev ticket for this. For a work around you can use the v1 node which should work, To use the v1 node you can copy the node and paste it into a text editor and change the version.

Thanks, but I've managed to work around this with shell commands. So I can wait to do it in the proper way

**Comment by janober** [comment]
Fix got released with [`n8n@1.39.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.39.1)
