### ISSUE TITLE
Problem with the Google Calendar node for obtaining multiple events with recurrence

### ISSUE THREAD

**Issue by d1ceward** [n8n-io/n8n#8655]
### Bug Description

Hello,

I'm trying to retrieve several events with recurrence from a Google calendar with the node dedicated to this, except that when retrieving an error occurs, example: `ERROR: Unsupported RFC prop RDATE in RDATE;TZID=Europe/Paris:20210405T093000`.

Node configuration with error:
![image](https://github.com/n8n-io/n8n/assets/8332823/09087b1b-bce0-4eab-9c1b-c012c2ccbb3f)

<details>
<summary>Stacktrace</summary>
Error: Unsupported RFC prop RDATE in RDATE;TZID=Europe/Paris:20210405T093000
    at parseLine (/usr/local/lib/node_modules/n8n/node_modules/rrule/dist/es5/rrule.js:2184:19)
    at Array.map (<anonymous>)
    at Function.parseString (/usr/local/lib/node_modules/n8n/node_modules/rrule/dist/es5/rrule.js:2151:10)
    at Function.RRule.fromString (/usr/local/lib/node_modules/n8n/node_modules/rrule/dist/es5/rrule.js:3178:32)
    at addNextOccurrence (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Calendar/GenericFunctions.js:98:41)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Calendar/GoogleCalendar.node.js:350:85)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:706:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:656:53
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1058:20
</details>

### To Reproduce

1. Create Google Calendar node
2. Choose Event/Get many with the desired calendar
3. Add some recurrent event in calendar
4. Test node

### Expected behavior

Return a list of event without issue

### Operating System

Docker with Arch linux host kernel at 6.7.4

### n8n Version

1.27.3

### Node.js Version

v18.19.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @d1ceward,

Thanks for the report, I have managed to reproduce it and will check if an exsiting PR fixes this already.

**Comment by Joffcom** [comment]
Hey @d1ceward 

Good news the 1.30.0 release fixes this issue, give it a go and let me know how you get on.

If you are still having issues we can move this back to opened.

**Comment by d1ceward** [comment]
I've just updated my instance, I've done some tests and everything seems to be working perfectly. It's fixed. Thanks!
