### ISSUE TITLE
Can't read data form Chat Trigger

### ISSUE THREAD

**Issue by the-trading-ai** [n8n-io/n8n#8741]
### Bug Description

<img width="1276" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/0e2c7c05-2e80-4d11-967d-258d307413a5">

### To Reproduce

Look image

### Expected behavior

Variable working

### Operating System

hosted

### n8n Version

beta 1.30

### Node.js Version

hosted

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @the-trading-ai,

Can you share the full workflow and the exact version of n8n you are running?

We don't have a "beta" version of 1.30 but we do have 1.30.0 and 1.30.1

**Comment by the-trading-ai** [comment]
<img width="756" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/d40a3824-1611-4f42-ac30-11402dd95942">

I discover the problem first by testing this template :
https://n8n.io/workflows/2098-chat-with-openai-assistant-by-adding-a-memory/

<img width="821" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/df16d3a3-0612-4e56-99bd-6b41b83ca38a">

<img width="1276" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/800fe793-dee9-4041-a461-13f292b33cee">

<img width="1274" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/a4f1fb89-747f-4a24-9883-a280ede424da">

**Comment by the-trading-ai** [comment]
<img width="860" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/9f1f95b7-788d-450a-82f3-ff1dd3a49bff">

**Comment by the-trading-ai** [comment]
I renamed the node without the space to see. Nothing change. Not able to get the value of this variable.

**Comment by the-trading-ai** [comment]
NodeOperationError: Error in sub-node Window Buffer Memory
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1741:19
    at async Promise.all (index 0)
    at Object.getInputConnectionData (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1748:19)
    at Object.getInputConnectionData (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2154:24)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/nodes/memory/MemoryManager/MemoryManager.node.js:228:25)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:730:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:660:53
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1062:20

**Comment by the-trading-ai** [comment]
<img width="1255" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/1003eb6d-a5b1-4cfc-9129-4129e486007e">

The object look to be empty

**Comment by Joffcom** [comment]
Hey @the-trading-ai,

For now you can try using .first() instead of .item(). I have created an internal dev ticket to fix the missing paired item data which we are tracking as `NODE-1181`.

**Comment by ErroneousBosch** [comment]
I am trying this using the example from https://docs.n8n.io/advanced-ai/examples/api-workflow-tool/ and seeing the same error.

using ".first" does not solve the issue. I am 1.31.0 ce

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
