### ISSUE TITLE
Youtube Upload - 400 Bad Request

### ISSUE THREAD

**Issue by maximeb97** [n8n-io/n8n#8835]
### Bug Description

Hello,
I'm running into an error while trying to use the `Youtube Upload a Video` node, the request returns a 400 Bad Request error leading the execution to fail.

Error:
`ERROR: Request failed with status code 400`
Details:
```
AxiosError: Request failed with status code 400
    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.httpRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:713:18)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/YouTube/YouTube.node.js:610:50)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:730:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:662:53
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1064:20
```

I saw that someone ran into a similar issue recently on [n8n forum](https://community.n8n.io/t/title-error-400-with-upload-video-to-youtube-node/39827) , unfortunatly he had to use a workaround solution.

I verified that my Youtube credential were valid and that the API quota limitation wasn't exceeded.
Also verified that the format of my video is accepted by Youtube. 

### To Reproduce

1. Add the necessary Youtube Credentials to access the API
2. Create a "Youtube Upload Video" node on a workflow
3.  Fill the required fields to test the node
4. Test the node
5. Youtube API reply with 400 Bad Request

### Expected behavior

The API should reply 2xx

### Operating System

Docker Alpine Linux v3.19

### n8n Version

1.29.1

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @maximeb97,

How large is the video that you are uploading and have you tried setting `N8N_DEFAULT_BINARY_DATA_MODE` to `filesystem`?

**Comment by maximeb97** [comment]
Hello @Joffcom , I just tried to set `N8N_DEFAULT_BINARY_DATA_MODE` to `filesystem` and it is indeed working as expected.

Thanks a lot for you fast reply
