### ISSUE TITLE
[Docker - self hosted] Password verifies, but app returning "401 Unauthorized" errors

### ISSUE THREAD

**Issue by ErroneousBosch** [n8n-io/n8n#8850]
### Bug Description

Using 1.32.1 on TrueNas SCALE, using Community Helm that runs the official image. Fresh install, register new account and the password authenticates, but the console is full of 401 Unauthorized errors, and most of the dashboard does not load, and nothing is usable. 

Failed to load resource: the server responded with a status of 401 (Unauthorized)
:30068/rest/active-workflows:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:30068/rest/credentials:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:30068/rest/variables:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:30068/rest/external-secrets/secrets:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
:30068/rest/cta/become-creator:1 
        
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
n8n-uKoDE8Qf.js:7 Uncaught (in promise) ResponseError: Unauthorized
    at Rx (n8n-uKoDE8Qf.js:7:2682)
    at async Gr (n8n-uKoDE8Qf.js:7:2932)
    at async Ve (MainSidebar-_TrEfGUX.js:1:5142)
    at async x (MainSidebar-_TrEfGUX.js:1:5469)
    at async k (MainSidebar-_TrEfGUX.js:1:5558)

### To Reproduce

1. Bring up helm in Kubernetes
2. Navigate to appropriate address
3. Register
4. Enter dashboard

### Expected behavior

App should work normally, as it does in 1.31

### Operating System

TrueNAS-SCALE-23.10.2 + Docker

### n8n Version

1.32.1

### Node.js Version

Whatever is in image

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ErroneousBosch,

If you accessing n8n using http instead of https you will see this error, Can you set the env option `N8N_SECURE_COOKIE` to `false` and see if it helps.

**Comment by ErroneousBosch** [comment]
Let me try that @Joffcom

**Comment by ErroneousBosch** [comment]
That worked! I use it only via my local network, so https with a valid cert isn't really possible. nice to have a workaround

**Comment by Joffcom** [comment]
You could use HTTPS with a self signed certificate but I am glad it is working, I will mark this as closed.

**Comment by daniel-simpson** [comment]
Just had exactly the same issue, running on an address on my local network (a local docker server) over http.

```
environment:
- N8N_SECURE_COOKIE=false
```
made all the difference.

Thanks!
