### ISSUE TITLE
Error when starting n8n after an upgrade

### ISSUE THREAD

**Issue by amitbend** [n8n-io/n8n#898]
**Describe the bug**
I have a n8n instance running on heroku using docker with mongodb, version 0.65.0 used to work just fine.
After the upgrade, I cleaned the DB completely and keep getting this error that crashing the server no matter what:

```
Error: There was an error: Cannot create property 'name' on string 'webhookPath'
2020-08-27T11:28:19.579173+00:00 app[web.1]:     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
2020-08-27T11:28:19.579173+00:00 app[web.1]:     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
2020-08-27T11:28:19.579174+00:00 app[web.1]:     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
2020-08-27T11:28:19.579283+00:00 app[web.1]: (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-08-27T11:28:19.579347+00:00 app[web.1]: (node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise 
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version 0.78.0

**Comment by janober** [comment]
Never seen this issue before. Sadly does also not give much information where the error his happening exactly for you. So hard to know what is going wrong. Just fyi the usage of MongoDB is discouraged and I advise using Postgres.

Apart from that if you say you cleaned the database totally. Did you really delete everything? Because I wonder why n8n would do any webhook related things if it would not believe that there is an active workflow somewhere. So please check again if really all data is gone.

**Comment by amitbend** [comment]
Yes, I actually start a new database + a new instance and it still doesn't work.
Might be an env variable I'm missing?

**Comment by janober** [comment]
What you could try is not to set `DB_TYPE` at all. In this case it would fall back to SQLite. Like that you can at least find out if it is related to MongoDB or not.

**Comment by amitbend** [comment]
Now it's working, mongodb seems to be the problem.
It seems to me like there's a collection that needs to be created - right now I can see only "migrations" collection in the db

**Comment by janober** [comment]
Ok good that at least that is clear now.

n8n should actually set everything up automatically by itself. Is MongoDB a hard requirement? Because we have actually planned to deprecate it at some point. So switching to another database will be required anyway earlier or later.

**Comment by amitbend** [comment]
Actually yes in my case.
Any chance I can set it up manually?

**Comment by janober** [comment]
It should already do now everything automatically. So no idea what is going wrong for you.
As we want to drop support anyway, it does also sadly not make sense that our developers spend time on researching where the problem lies exactly and if something is wrong within n8n or somewhere else. Very sorry about that.  

You can maybe try if it works for you if run n8n together with MongoDB locally. Maybe with a different (older/newer) version.
