### ISSUE TITLE
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default).

### ISSUE THREAD

**Issue by jicho** [n8n-io/n8n#9172]
### Bug Description

After updating n8n to 1.37.3 I'm getting the following error:
```log
2024-04-19T07:06:34.937595991Z Editor is now accessible via:
2024-04-19T07:06:34.937696328Z http://localhost:5678/
2024-04-19T07:06:42.733403395Z ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
2024-04-19T07:06:42.734063694Z     at Object.xForwardedForHeader (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:166:13)
2024-04-19T07:06:42.734172643Z     at Object.wrappedValidations.<computed> [as xForwardedForHeader] (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:338:22)
2024-04-19T07:06:42.734274856Z     at Object.keyGenerator (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:593:20)
2024-04-19T07:06:42.734357124Z     at /usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:644:32
2024-04-19T07:06:42.734408806Z     at /usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:625:5 {
2024-04-19T07:06:42.734458262Z   code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
2024-04-19T07:06:42.734504821Z   help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
2024-04-19T07:06:42.734552491Z }
```

How can I solve this? It looks like something that is out reach by the config options.

Oh... and once started and when you click around in n8n no additional validation errors are added to the log.

### To Reproduce

Press update in Dockge to update the container to the latest version and login to n8n.

I am running n8n behind the Nginx Proxy Manager.
For what I can see I'm only doing the default stuff in NPM:

![image](https://github.com/n8n-io/n8n/assets/610740/af8a3555-3454-440d-a747-37035c7b86a0)

![image](https://github.com/n8n-io/n8n/assets/610740/e6c9cb60-f775-4ba5-bdab-137970286f53)

I'm not using the custom location or any advanced stuff.

Funny detail... n8n is working without any issues itself.

This is my compose file:
```yaml
version: "3.8"
services:
  n8n:
    container_name: n8n
    network_mode: bridge
    restart: always
    ports:
      - 5678:5678
    volumes:
      - /volume1/docker/n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - EXECUTIONS_DATA_PRUNE=true
      - WEBHOOK_URL=https://n8n.example.com/
    image: n8nio/n8n:latest
```

### Expected behavior

No error :)

### Operating System

docker install on Synology NAS

### n8n Version

1.37.3

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
Can you please try setting the env variable `N8N_PROXY_HOPS` to `1`?

**Comment by ahiggins1039** [comment]
We had the same problem and the above https://github.com/n8n-io/n8n/issues/9172#issuecomment-2066022705 seems to have fixed it.

**Comment by jicho** [comment]
It looks like this solves the problem, thanks for the quick responses!

**Comment by Morriz** [comment]
@netroy can somebody please update this in the code somewhere?
