### ISSUE TITLE
HTTP Request node outputs malformed json

### ISSUE THREAD

**Issue by sweenu** [n8n-io/n8n#9247]
### Bug Description

Here are the problematic nodes:

```json
{
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "4a8c4d3ed2f4423694f8ac022d1c321551900c7ab47e0c03549acecec1ab4a89"
  },
  "nodes": [
    {
      "parameters": {
        "method": "POST",
        "url": "https://bankaccountdata.gocardless.com/api/v2/token/refresh/",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "accept",
              "value": "application/json"
            },
            {
              "name": "content-type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "bodyParameters": {
          "parameters": [
            {
              "name": "refresh",
              "value": "token"
            }
          ]
        },
        "options": {}
      },
      "id": "2bf1c2d8-2da2-44b7-bc9f-705c5ed3ae4c",
      "name": "Refresh access token",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        860,
        680
      ],
      "onError": "continueErrorOutput"
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "strict"
          },
          "conditions": [
            {
              "id": "34f70204-828c-4966-b4ca-ef5b7120e847",
              "leftValue": "={{ $json.error.status }}",
              "rightValue": 401,
              "operator": {
                "type": "number",
                "operation": "equals"
              }
            }
          ],
          "combinator": "and"
        },
        "options": {}
      },
      "id": "c87369ea-cc21-4aa8-8c5a-1aa2cfde62c2",
      "name": "Failure is 401",
      "type": "n8n-nodes-base.if",
      "typeVersion": 2,
      "position": [
        840,
        900
      ],
      "retryOnFail": false,
      "executeOnce": true
    }
  ],
  "connections": {
    "Refresh access token": {
      "main": [
        null,
        [
          {
            "node": "Failure is 401",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

And here is the output received by the IF node:
```json
[
{
"refresh_token": "invalid_token",
"error": {
"message": "401 - "{\"summary\":\"Invalid token\",\"detail\":\"Token is invalid or expired\",\"status_code\":401}"",
"name": "AxiosError",
"stack": "AxiosError: Request failed with status code 401 at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12) at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:537:9) at RedirectableRequest.emit (node:events:529:35) at RedirectableRequest.emit (node:domain:489:12) at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:398:10) at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:91:12) at Object.onceWrapper (node:events:632:26) at ClientRequest.emit (node:events:517:28) at ClientRequest.emit (node:domain:489:12) at HTTPParser.parserOnIncomingClient (node:_http_client:700:27) at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at requestFn (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:565:33) at proxyRequestToAxios (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:568:26) at Object.request (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1957:50)",
"code": "ERR_BAD_REQUEST",
"status": 401
}
}
]
```
Because the `message` field has issues (unescaped double quotes). The IF node returns `false` even though `status` is clearly equal to 401.

The first issue is that the http node for some reason is able to output malformed json. And the second issue is that n8n fails silently with malformed json instead of throwing an error that would be helpful.

What is very strange though, is that if I then rerun the IF node manually ("Test step"), it will work fine. Which leads me to think that there might be something else to it.

### To Reproduce

Just run the above workflow.

### Expected behavior

The http node should be able to output malformed json that will bread the rest of the workflow.

### Operating System

NixOS 24.05 (Docker)

### n8n Version

1.34.1

### Node.js Version

Whatever the version is in the official Docker image for this version

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @sweenu,

For me the If returns true, It could be worth updating. I did also check the output and while the displayed error looks to be invalid when you copy it or try and use it the escapes are there.

**Comment by sweenu** [comment]
It works on the newest version! Sorry should have tried before opening the issue.

**Comment by Joffcom** [comment]
@sweenu no worries it happens :)
