### ISSUE TITLE
Docker-compose examples does not work

### ISSUE THREAD

**Issue by shyim** [n8n-io/n8n#962]
**Describe the bug**
Run docker-compose and n8n fails
```
(node:6) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
(node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot create property 'name' on string 'webhookPath'
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
    at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:126:22
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ln: /home/node/.n8n: File exists
(node:6) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot create property 'name' on string 'webhookPath'
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
    at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:126:22
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ln: /home/node/.n8n: File exists
(node:6) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'name' on string 'webhookPath'
    at CreateIndexesOperation.execute (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/operations/create_indexes.js:105:25)
    at /usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/operations/execute_operation.js:155:15
    at Server.selectServer (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/core/topologies/server.js:832:3)
    at Server.selectServer (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/topologies/topology_base.js:342:32)
    at executeWithServerSelection (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/operations/execute_operation.js:137:12)
    at executeOperation (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/operations/execute_operation.js:75:7)
    at Collection.createIndex (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/collection.js:1236:10)
    at MongoQueryRunner.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:81:85)
    at step (/usr/local/lib/node_modules/n8n/node_modules/tslib/tslib.js:139:27)
    at Object.next (/usr/local/lib/node_modules/n8n/node_modules/tslib/tslib.js:120:57)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(node:6) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot create property 'name' on string 'webhookPath'
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
    at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:126:22
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

**To Reproduce**
Run these files https://github.com/n8n-io/n8n/tree/master/docker/compose/withMongo

**Expected behavior**
It works

**Environment (please complete the following information):**
 - OS: NixOs

**Additional context**

**Comment by janober** [comment]
Thanks a lot for the info. Sadly will not be fixed if it is broke, as support for MongoDB will be removed soon. 

So to make sure that not more people go down this route did I now remove the compose file.
